'use strict';
(() => {
const $=id=>document.getElementById(id),cv=$('game'),ctx=cv.getContext('2d',{alpha:false}),mc=$('map').getContext('2d');
const TAU=Math.PI*2, WORLD=3200, STEP=400, OFFSET=200, ROAD=116, LANE=25;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),angle=a=>Math.atan2(Math.sin(a),Math.cos(a));
let seed=7719;function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
let W=innerWidth,H=innerHeight,D=1,zoom=1,clock=0,active=false,started=false,dead=false,night=false,frameTime=0,acc=0,uiTimer=0;
let cash=0,best=0,distance=0,wanted=0,lastCrime=-100,invincible=0,job=null,jobReady=0,toastUntil=0,shake=0,fireCooldown=0,mouseAim=false;
try{best=Number(localStorage.getItem('crimecity-best-v2'))||0;cash=Number(localStorage.getItem('crimecity-cash-v2'))||0;}catch{}
const mobile=matchMedia('(pointer:coarse)').matches||W<760||new URLSearchParams(location.search).get('controls')==='touch';document.body.classList.toggle('mobile',mobile);
if(mobile)$('help').textContent='Joystick — ruch i kierunek jazdy. W aucie wychyl joystick, aby jechać. STRZAŁ celuje w kierunku ruchu; GAZ pozwala jechać prosto. HAMULEC zatrzymuje auto.';
$('record').textContent='WARSZAWA / 3.0'+(best?' · REKORD $ '+best:'');
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,1.5);cv.width=Math.round(W*D);cv.height=Math.round(H*D);zoom=mobile?(H<W?.87:.83):1.12;}resize();addEventListener('resize',resize);
const player={x:1240,y:1873,a:0,hp:100,car:null};let camera={x:player.x,y:player.y};
const keys={},input={x:0,y:0,fire:false,brake:false,id:null,mouseX:0,mouseY:0};
const buildings=[],trees=[],cars=[],peds=[],bullets=[],particles=[],explosions=[],bodies=[],skids=[],pickups=[];
const garages=[{x:640,y:1530},{x:2640,y:2330},{x:1030,y:730}];const jobs=[{x:1240,y:1870},{x:2750,y:1850},{x:1500,y:1050}];
const palette=['#c95b42','#7e9fb3','#dcbf66','#6a9479','#d3d5c7','#515563','#ae7379','#e69554','#689b98'];
const types=[{name:'MONARCH',w:43,h:21,max:300,acc:175,grip:3.1},{name:'STINGER GT',w:44,h:20,max:420,acc:250,grip:3.6},{name:'BOXER VAN',w:49,h:25,max:235,acc:135,grip:2.6},{name:'CITY TAXI',w:44,h:22,max:310,acc:185,grip:3},{name:'HAULER',w:66,h:27,max:210,acc:100,grip:2.1},{name:'MINI',w:35,h:19,max:290,acc:205,grip:3.5},{name:'INTERCEPTOR',w:46,h:22,max:365,acc:220,grip:3.4},{name:'CITY BUS',w:79,h:27,max:195,acc:95,grip:2},{name:'AMBULANS',w:51,h:25,max:290,acc:170,grip:2.6}];
const weapons=[{name:'PISTOLET',rate:.25,count:1,spread:.025,damage:23,life:.65},{name:'SMG',rate:.085,count:1,spread:.075,damage:12,life:.60},{name:'STRZELBA',rate:.66,count:6,spread:.25,damage:14,life:.34}];let weapon=0,arrest=0;
function rect(g,x,y,w,h,c){g.fillStyle=c;g.fillRect(x,y,w,h);}function circle(g,x,y,r,c){g.fillStyle=c;g.beginPath();g.arc(x,y,r,0,TAU);g.fill();}
function textAt(g,t,x,y,size,color){g.fillStyle=color;g.font=`bold ${size}px Arial`;g.textAlign='center';g.fillText(t,x,y);}
function roadCenter(v){return OFFSET+Math.round((v-OFFSET)/STEP)*STEP;}function onRoad(x,y){return Math.abs(x-roadCenter(x))<ROAD/2||Math.abs(y-roadCenter(y))<ROAD/2;}
const mapCanvas=document.createElement('canvas');mapCanvas.width=WORLD;mapCanvas.height=WORLD;const mapCtx=mapCanvas.getContext('2d',{alpha:false});
const bridges=[{y:1000,name:'MOST ŚLĄSKO-DĄBROWSKI'},{y:1400,name:'MOST ŚWIĘTOKRZYSKI'},{y:1800,name:'MOST PONIATOWSKIEGO'},{y:2600,name:'MOST ŁAZIENKOWSKI'}];
const landmarks=[{x:1200,y:1600,name:'PAŁAC KULTURY',kind:'palace'},{x:800,y:2000,name:'DWORZEC CENTRALNY',kind:'station'},{x:1600,y:800,name:'STARE MIASTO',kind:'oldtown'},{x:1930,y:820,name:'ZAMEK KRÓLEWSKI',kind:'castle'},{x:1950,y:1230,name:'CENTRUM KOPERNIK',kind:'science'},{x:2800,y:1600,name:'STADION NARODOWY',kind:'stadium'},{x:1600,y:2800,name:'ŁAZIENKI KRÓLEWSKIE',kind:'garden'},{x:1200,y:1200,name:'OGRÓD SASKI',kind:'park'},{x:800,y:1200,name:'WOLA',kind:'towers'}];
function riverCenter(y){return 2160+80*Math.sin(y/WORLD*Math.PI*1.3);}
function water(x,y,r=0){return Math.abs(x-riverCenter(y))<135+r&&!bridges.some(b=>Math.abs(y-b.y)<ROAD/2-r);}
function edgeValid(ix,iy,d){let nx=ix+[1,0,-1,0][d],ny=iy+[0,1,0,-1][d];if(nx<0||ny<0||nx>7||ny>7)return false;const a={x:OFFSET+ix*STEP,y:OFFSET+iy*STEP},b={x:OFFSET+nx*STEP,y:OFFSET+ny*STEP};for(let t=0;t<=1;t+=.05)if(water(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,28))return false;return true;}
function district(p){if(p.x>riverCenter(p.y)+135)return p.y<1500?'PRAGA-PÓŁNOC':'PRAGA-POŁUDNIE';if(p.y<1000&&p.x>1400)return 'STARE MIASTO';if(p.y>2450)return 'MOKOTÓW';if(p.x<1000)return 'WOLA';if(p.x>1800)return 'POWIŚLE';return 'ŚRÓDMIEŚCIE';}
function ellipse(g,x,y,rx,ry,c){g.fillStyle=c;g.beginPath();g.ellipse(x,y,rx,ry,0,0,TAU);g.fill();}
function makeMap(){const g=mapCtx;rect(g,0,0,WORLD,WORLD,'#596c51');
for(let n=0;n<8;n++){let v=OFFSET+n*STEP;rect(g,v-76,0,152,WORLD,'#adb09c');rect(g,0,v-76,WORLD,152,'#adb09c');rect(g,v-58,0,116,WORLD,'#424d4e');rect(g,0,v-58,WORLD,116,'#424d4e');g.strokeStyle='#d6c391';g.lineWidth=1;g.setLineDash([18,18]);g.beginPath();g.moveTo(v,0);g.lineTo(v,WORLD);g.moveTo(0,v);g.lineTo(WORLD,v);g.stroke();g.setLineDash([]);}
for(let ix=0;ix<7;ix++)for(let iy=0;iy<7;iy++){const x=OFFSET+ix*STEP+83,y=OFFSET+iy*STEP+83,cx=x+117,cy=y+117;if(Math.abs(cx-riverCenter(cy))<260)continue;if(landmarks.some(l=>Math.abs(l.x-cx)<155&&Math.abs(l.y-cy)<155))continue;const old=cy<1050&&cx>1350&&cx<2050,praga=cx>2400,park=(ix*3+iy*7)%17===4;rect(g,x-5,y-5,244,244,park?'#668454':'#939d88');
if(park){rect(g,x+108,y,14,234,'#bdb299');for(let i=0;i<20;i++)trees.push({x:x+15+rng()*200,y:y+15+rng()*200,r:8+rng()*10});continue;}
for(let a=0;a<2;a++)for(let b=0;b<2;b++){let bx=x+a*126,by=y+b*126,w=old?98:104,h=104;buildings.push({x:bx,y:by,w,h});rect(g,bx+10,by+13,w,h,'#23342e55');rect(g,bx-2,by-2,w+4,h+4,old?'#d3b598':praga?'#a99a84':'#a4aba0');rect(g,bx+5,by+5,w-10,h-10,old?'#985d48':praga?'#686a5c':'#586a6d');if(old){for(let k=10;k<w-5;k+=11)rect(g,bx+k,by+7,2,h-14,'#bd795957');rect(g,bx+w/2,by+7,3,h-14,'#d19470');}else{rect(g,bx+14,by+15,26,18,'#a8b0a3');for(let k=0;k<4;k++)rect(g,bx+17,by+18+k*3,20,1,'#566459');circle(g,bx+72,by+67,15,'#3e514b');circle(g,bx+70,by+65,12,'#889887');if((a+b+ix)%2){for(let k=0;k<4;k++)rect(g,bx+15+k*19,by+50,13,26,'#73959b');}}
for(let k=12;k<w-8;k+=23){rect(g,bx+k,by-1,10,4,'#e3c98d');rect(g,bx+k,by+h-3,10,4,'#e3c98d');}if((ix+iy+a+b)%5===0){rect(g,bx,by+h-15,w,12,'#a55e49');textAt(g,['PIEKARNIA','KSIĘGARNIA','BAR MLECZNY','APTEKA'][(ix+iy)%4],bx+w/2,by+h-6,8,'#f5e6bb');}}
for(let i=0;i<4;i++)trees.push({x:x+20+i*62,y:y-11,r:9});}
// A continuous river replaces the underlying street grid. Only bridges cross it.
for(let y=0;y<WORLD;y+=4){const x=riverCenter(y);rect(g,x-158,y,316,4,'#b8b79a');rect(g,x-146,y,292,4,'#5c8d8b');rect(g,x-134,y,268,4,'#397b84');if(y%28===0)for(let k=-110;k<120;k+=45)rect(g,x+k,y,22,1,'#83b2aa50');rect(g,x-169,y,7,4,'#d1cbb0');}
for(const b of bridges){const x=riverCenter(b.y);rect(g,x-185,b.y-65,370,130,'#c7c6b4');rect(g,x-185,b.y-58,370,116,'#455257');for(let xx=x-180;xx<x+180;xx+=30)rect(g,xx,b.y,16,2,'#dbcfab');for(let yy of [b.y-62,b.y+62]){rect(g,x-184,yy,368,3,'#dad8c4');for(let xx=x-174;xx<x+180;xx+=32)rect(g,xx,yy-3,3,8,'#808c80');}if(b.y===1400){for(const side of [-1,1]){let px=x-15;rect(g,px,b.y+side*49-3,8,7,'#ecedd7');g.strokeStyle='#d8ddc488';g.lineWidth=1;for(let k=0;k<6;k++){g.beginPath();g.moveTo(px,b.y+side*49);g.lineTo(x-150+k*58,b.y+side*61);g.stroke();}}}textAt(g,b.name,x,b.y-77,10,'#e8ebcb');}
for(let ix=0;ix<8;ix++)for(let iy=0;iy<8;iy++){const x=OFFSET+ix*STEP,y=OFFSET+iy*STEP;if(water(x,y)||Math.abs(x-riverCenter(y))<160)continue;rect(g,x-57,y-57,114,114,'#424d4e');for(let k=-3;k<=3;k++){rect(g,x+k*12-4,y-82,7,19,'#d0d0b9');rect(g,x+k*12-4,y+63,7,19,'#d0d0b9');rect(g,x-82,y+k*12-4,19,7,'#d0d0b9');rect(g,x+63,y+k*12-4,19,7,'#d0d0b9');}circle(g,x+25,y+126,6,'#344640');}
for(const l of landmarks){const x=l.x,y=l.y;const square=['palace','oldtown','station','towers','stadium','park','garden'].includes(l.kind);if(square)rect(g,x-117,y-117,234,234,['garden','park'].includes(l.kind)?'#648252':'#b8b69c');
if(l.kind==='palace'){buildings.push({x:x-74,y:y-77,w:148,h:154});rect(g,x-70,y-63,145,160,'#34413444');rect(g,x-83,y-42,166,84,'#bfb49a');rect(g,x-55,y-70,110,140,'#cfc2a4');rect(g,x-36,y-55,72,110,'#a3937a');rect(g,x-27,y-43,54,86,'#e0d0ac');rect(g,x-18,y-28,36,56,'#bda885');rect(g,x-9,y-17,18,34,'#ece0ba');rect(g,x-2,y-42,4,46,'#f7edcb');circle(g,x,y-33,5,'#ecce82');for(let a=-65;a<70;a+=16){rect(g,x+a,y-35,5,10,'#6c756a');rect(g,x+a,y+28,5,10,'#6c756a');}textAt(g,'PLAC DEFILAD',x,y+107,10,'#5a6252');}
if(l.kind==='station'){buildings.push({x:x-98,y:y-55,w:196,h:110});rect(g,x-103,y-60,206,120,'#c5c8b4');rect(g,x-97,y-52,194,104,'#596d70');for(let k=-85;k<90;k+=18){rect(g,x+k,y-45,10,90,'#a2b6b0');}textAt(g,'WARSZAWA CENTRALNA',x,y+83,10,'#42564e');}
if(l.kind==='oldtown'){for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++){if(a===0&&b===0)continue;let bx=x+a*78-27,by=y+b*78-26;buildings.push({x:bx,y:by,w:54,h:52});rect(g,bx-2,by-2,58,56,'#d8c39d');rect(g,bx+3,by+3,48,46,['#a66c51','#8d5544','#b77b58'][(a+b+3)%3]);rect(g,bx+25,by+3,3,46,'#d5a578');}circle(g,x,y,20,'#a4a995');circle(g,x,y,11,'#56797a');textAt(g,'RYNEK',x,y+37,9,'#4f5e50');}
if(l.kind==='castle'){buildings.push({x:x-57,y:y-64,w:114,h:128});rect(g,x-57,y-64,114,128,'#b46c52');rect(g,x-40,y-45,80,87,'#d2bd98');rect(g,x-24,y-25,48,49,'#a3987a');rect(g,x-10,y+45,20,24,'#a0634e');circle(g,x,y+57,9,'#786b59');circle(g,x-78,y+86,7,'#d1c6a3');}
if(l.kind==='science'){buildings.push({x:x-65,y:y-38,w:130,h:76});rect(g,x-68,y-42,136,84,'#999a71');rect(g,x-60,y-34,120,68,'#859668');for(let k=-45;k<50;k+=25)circle(g,x+k,y,10,'#506c68');}
if(l.kind==='stadium'){buildings.push({x:x-101,y:y-79,w:202,h:158});ellipse(g,x+6,y+9,109,88,'#364e4244');ellipse(g,x,y,107,82,'#e7dcc2');for(let a=0;a<TAU;a+=Math.PI/16){g.strokeStyle=Math.floor(a*16/Math.PI)%2?'#d4d3be':'#bd4b47';g.lineWidth=9;g.beginPath();g.moveTo(x+Math.cos(a)*68,y+Math.sin(a)*46);g.lineTo(x+Math.cos(a)*99,y+Math.sin(a)*74);g.stroke();}ellipse(g,x,y,72,48,'#314b3f');rect(g,x-48,y-27,96,54,'#659655');g.strokeStyle='#d6dcc0';g.lineWidth=1;g.strokeRect(x-43,y-22,86,44);g.beginPath();g.moveTo(x,y-22);g.lineTo(x,y+22);g.stroke();circle(g,x,y,7,'#c1cfaa');}
if(l.kind==='park'||l.kind==='garden'){rect(g,x-6,y-117,12,234,'#c1b89b');rect(g,x-117,y-6,234,12,'#c1b89b');if(l.kind==='garden'){ellipse(g,x+30,y+22,40,87,'#4f9191');rect(g,x+2,y+12,55,23,'#d3c6a5');buildings.push({x:x+2,y:y+12,w:55,h:23});}else{circle(g,x,y,26,'#c6c7ae');circle(g,x,y,19,'#63959b');}for(let k=0;k<28;k++){let tx=x-104+rng()*208,ty=y-104+rng()*208;if(Math.abs(tx-x)>17&&Math.abs(ty-y)>18)trees.push({x:tx,y:ty,r:10+rng()*7});}}
if(l.kind==='towers'){for(let a=-1;a<=1;a++){buildings.push({x:x+a*65-22,y:y-72,w:44,h:144});rect(g,x+a*65-14,y-62,51,151,'#243c4240');rect(g,x+a*65-22,y-72,44,144,'#879d9c');rect(g,x+a*65-17,y-66,34,132,'#3e6977');for(let k=-60;k<65;k+=12)rect(g,x+a*65-17,y+k,34,2,'#8cacac');}}
textAt(g,l.name,x,y-125,11,'#edf0cb');}
for(const t of trees){if(water(t.x,t.y,20))continue;circle(g,t.x+4,t.y+6,t.r,'#243c3144');circle(g,t.x,t.y,t.r,'#355e43');circle(g,t.x-3,t.y-3,t.r*.65,'#5f8350');}
for(const p of garages){rect(g,p.x-28,p.y-23,56,46,'#779b69');textAt(g,'WARSZTAT',p.x,p.y+3,9,'#edf0c3');}
const vnames=['OBWODOWA','TOWAROWA','JANA PAWŁA II','MARSZAŁKOWSKA','KRAKOWSKIE PRZEDM.','','ZIELENIECKA','GROCHOWSKA'];const hnames=['ŻOLIBORZ','MURANÓW','AL. SOLIDARNOŚCI','ŚWIĘTOKRZYSKA','AL. JEROZOLIMSKIE','KOSZYKOWA','TRASA ŁAZIENKOWSKA','MOKOTÓW'];for(let i=0;i<8;i++){let v=OFFSET+i*STEP;for(let j=0;j<7;j++){let p=OFFSET+j*STEP+110;if(!water(v,p,70)&&vnames[i]){g.save();g.translate(v-46,p);g.rotate(-Math.PI/2);textAt(g,vnames[i],0,0,8,'#c9ccb29a');g.restore();}if(!water(p,v,70))textAt(g,hnames[i],p,v-43,8,'#c9ccb29a');}}
for(let n=0;n<8000;n++)rect(g,rng()*WORLD,rng()*WORLD,2,1,'#132d190b');
}makeMap();
function blocked(x,y,r=9){return x<r||y<r||x>WORLD-r||y>WORLD-r||water(x,y,r)||buildings.some(b=>x>b.x-r&&x<b.x+b.w+r&&y>b.y-r&&y<b.y+b.h+r);}
// Circle against the rotated body, including a small wheel clearance.
function pedestrianContact(x,y,c,r=8){const ca=Math.cos(c.a),sa=Math.sin(c.a),dx=x-c.x,dy=y-c.y,lx=dx*ca+dy*sa,ly=-dx*sa+dy*ca,hx=c.type.w/2+2,hy=c.type.h/2+2;const qx=clamp(lx,-hx,hx),qy=clamp(ly,-hy,hy);let nx=lx-qx,ny=ly-qy,d=Math.hypot(nx,ny),depth;if(d>=r)return null;if(d>.0001){nx/=d;ny/=d;depth=r-d;}else{const ex=hx-Math.abs(lx),ey=hy-Math.abs(ly);if(ex<ey){nx=lx>=0?1:-1;ny=0;depth=ex+r;}else{nx=0;ny=ly>=0?1:-1;depth=ey+r;}}return {x:nx*ca-ny*sa,y:nx*sa+ny*ca,depth};}
function pedestrianBlocked(x,y,ignore=null){return blocked(x,y,8)||cars.some(c=>c!==ignore&&pedestrianContact(x,y,c));}
function movePedestrian(mx,my){let x=player.x+mx,y=player.y+my;for(let pass=0;pass<3;pass++)for(const c of cars){const h=pedestrianContact(x,y,c);if(!h)continue;const into=mx*h.x+my*h.y;if(into<0){mx-=into*h.x;my-=into*h.y;x=player.x+mx;y=player.y+my;}}if(!pedestrianBlocked(x,y)){player.x=x;player.y=y;return;}if(!pedestrianBlocked(player.x+mx,player.y))player.x+=mx;if(!pedestrianBlocked(player.x,player.y+my))player.y+=my;}
function resolvePedestrianCars(){if(player.car)return;for(let pass=0;pass<3;pass++){let touched=false;for(const c of cars){const hit=pedestrianContact(player.x,player.y,c);if(!hit)continue;touched=true;const speed=Math.abs(c.s);if(speed>45)hurt(speed*.09);const x=player.x+hit.x*(hit.depth+.05),y=player.y+hit.y*(hit.depth+.05);if(!pedestrianBlocked(x,y,c)){player.x=x;player.y=y;}else c.s=0;}if(!touched)break;}}
function carBlocked(c,x,y,a=c.a){const ca=Math.cos(a),sa=Math.sin(a),l=c.type.w/2,w=c.type.h/2;for(const [u,v] of [[-l,-w],[-l,w],[l,-w],[l,w],[0,0]])if(blocked(x+u*ca-v*sa,y+u*sa+v*ca,2))return true;return false;}
function pathPoint(ix,iy,dir){const x=OFFSET+ix*STEP,y=OFFSET+iy*STEP;return {x:x+(dir===1?-LANE:dir===3?LANE:0),y:y+(dir===0?LANE:dir===2?-LANE:0)};}
const dx=[1,0,-1,0],dy=[0,1,0,-1];
function setNext(c,dir){c.dir=dir;c.ix+=dx[dir];c.iy+=dy[dir];c.target=pathPoint(c.ix,c.iy,dir);}
function chooseNext(c){const opts=[c.dir,(c.dir+1)%4,(c.dir+3)%4].filter(d=>edgeValid(c.ix,c.iy,d));if(!opts.length){if(edgeValid(c.ix,c.iy,(c.dir+2)%4))opts.push((c.dir+2)%4);else{c.s=0;return;}}let dir=opts.includes(c.dir)&&Math.random()<.62?c.dir:opts[Math.floor(Math.random()*opts.length)];if(c.police&&wanted>0){dir=opts.reduce((best,d)=>{const p=pathPoint(c.ix+dx[d],c.iy+dy[d],d),q=pathPoint(c.ix+dx[best],c.iy+dy[best],best);return dist(p,player)<dist(q,player)?d:best;},opts[0]);}setNext(c,dir);}
function spawnCar(i,police=false){let ix=Math.floor(rand(0,7)),iy=Math.floor(rand(0,7)),dir=Math.floor(rand(0,4));if(ix===0&&dir===2)dir=0;if(iy===0&&dir===3)dir=1;const valid=[0,1,2,3].filter(d=>edgeValid(ix,iy,d));if(!valid.length)return null;if(!valid.includes(dir))dir=valid[0];let p=pathPoint(ix,iy,dir),t=police?types[6]:types[[0,1,2,3,4,5,7,8][i%8]];let c={...p,a:dir*Math.PI/2,s:0,type:t,color:police?'#c1d0d2':t===types[7]?'#d6ae4d':palette[i%palette.length],hp:100,ai:true,police,ix,iy,dir,target:null,stuck:0,hit:0,age:0,parked:false,deadTime:0};setNext(c,dir);let f=rand(.05,.85);c.x+=(c.target.x-c.x)*f;c.y+=(c.target.y-c.y)*f;c.s=rand(65,110);if(!carBlocked(c,c.x,c.y)&&!cars.some(o=>dist(o,c)<85)&&dist(c,player)>130)cars.push(c);return c;}
for(let i=0;i<135;i++)spawnCar(i);const starter={x:1260,y:1852,a:0,s:0,type:types[1],color:'#d2b66b',hp:100,ai:false,police:false,hit:0,age:0,parked:true,deadTime:0};cars.push(starter);
function spawnPed(){let p={x:0,y:0,a:rand(0,TAU),color:palette[Math.floor(rand(0,palette.length))],s:rand(18,35),panic:0,hp:40,step:rand(0,6)};for(let i=0;i<100;i++){p.x=rand(100,WORLD-100);p.y=rand(100,WORLD-100);if(!blocked(p.x,p.y,9)&&!onRoad(p.x,p.y)){peds.push(p);return;}}}for(let i=0;i<145;i++)spawnPed();
function save(){best=Math.max(best,cash);try{localStorage.setItem('crimecity-best-v2',String(best));localStorage.setItem('crimecity-cash-v2',String(cash));}catch{}}
function toast(t){$('toast').textContent=t;$('toast').style.opacity='1';toastUntil=clock+3.7;}
function crime(n){wanted=clamp(wanted+n,0,5);lastCrime=clock;}
let audio=null,engine=null,engineGain=null,soundOn=false,musicOn=true,musicBus=null,noiseBuffer=null,nextMusicTime=0,musicStep=0;const musicVoices=new Set();
function initAudio(){if(audio)return;try{audio=new(window.AudioContext||window.webkitAudioContext)();engine=audio.createOscillator();engine.type='sawtooth';engineGain=audio.createGain();engineGain.gain.value=0;engine.connect(engineGain);engineGain.connect(audio.destination);engine.start();musicBus=audio.createGain();musicBus.gain.value=.7;musicBus.connect(audio.destination);noiseBuffer=audio.createBuffer(1,audio.sampleRate*.15,audio.sampleRate);const samples=noiseBuffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1)*(1-i/samples.length);nextMusicTime=audio.currentTime+.08;}catch{}}
function tone(freq,duration=.1,type='square',volume=.03){if(!soundOn||!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(25,freq*.45),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
// Original eight-bar synth-pop loop: A minor, F, C, G at 108 BPM.
const leadMelody=[76,0,79,81,0,79,76,72, 74,76,0,72,71,0,69,0, 72,0,76,77,0,76,72,69, 71,72,0,69,67,0,69,0, 76,0,79,84,0,83,79,76, 74,76,79,0,76,74,72,0, 74,0,79,81,0,79,74,71, 72,74,0,71,69,0,67,0];
const chords=[[57,60,64],[53,57,60],[48,52,55],[55,59,62]];
function rememberVoice(o){musicVoices.add(o);o.onended=()=>{musicVoices.delete(o);o.disconnect();};}
function musicNote(note,at,duration,volume,type='triangle'){const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=440*Math.pow(2,(note-69)/12);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(volume,at+.015);g.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(g);g.connect(musicBus);rememberVoice(o);o.onended=()=>{musicVoices.delete(o);o.disconnect();g.disconnect();};o.start(at);o.stop(at+duration+.02);}
function drum(at,kick=false,snare=false){const g=audio.createGain();g.connect(musicBus);const o=kick?audio.createOscillator():audio.createBufferSource();if(kick){o.frequency.setValueAtTime(130,at);o.frequency.exponentialRampToValueAtTime(42,at+.15);o.connect(g);}else{o.buffer=noiseBuffer;const filter=audio.createBiquadFilter();filter.type='highpass';filter.frequency.value=snare?1500:6500;o.connect(filter);filter.connect(g);}const dur=kick?.18:snare?.12:.045;g.gain.setValueAtTime(kick?.13:snare?.075:.025,at);g.gain.exponentialRampToValueAtTime(.001,at+dur);rememberVoice(o);o.onended=()=>{musicVoices.delete(o);o.disconnect();g.disconnect();};o.start(at);o.stop(at+dur);}
function stopMusic(){for(const o of musicVoices){try{o.stop();}catch{}}musicVoices.clear();if(audio)nextMusicTime=audio.currentTime+.05;}
function pumpMusic(){if(!audio||audio.state!=='running'||!musicOn||!active)return;const eighth=60/108/2;if(nextMusicTime<audio.currentTime)nextMusicTime=audio.currentTime+.04;while(nextMusicTime<audio.currentTime+.14){const step=musicStep%64,beat=step%8,chord=chords[Math.floor(step/16)],at=nextMusicTime;if(leadMelody[step]){musicNote(leadMelody[step],at,eighth*1.7,.042);musicNote(leadMelody[step],at+eighth*.75,eighth,.011,'sine');}if(beat%2===0)musicNote(chord[0]-12+(beat===6?7:0),at,eighth*1.6,.09,'sine');if(beat===0)for(const n of chord)musicNote(n,at,eighth*7.5,.014,'triangle');if(beat===0||beat===4)drum(at,true);if(beat===2||beat===6)drum(at,false,true);drum(at);musicStep++;nextMusicTime+=eighth;}}
$('music').addEventListener('click',()=>{initAudio();musicOn=!musicOn;$('music').textContent=musicOn?'MUZ. WŁ.':'MUZ. WYŁ.';$('music').setAttribute('aria-pressed',String(musicOn));$('music').setAttribute('aria-label',musicOn?'Wyłącz muzykę':'Włącz muzykę');if(!musicOn)stopMusic();else if(audio){nextMusicTime=audio.currentTime+.05;audio.resume().catch(()=>{});}});
function resetInput(){for(const k in keys)delete keys[k];input.x=input.y=0;input.fire=input.brake=false;input.id=null;$('stick').style.transform='';}
function pause(){if(!started||dead)return;active=!active;resetInput();$('overlay').style.display=active?'none':'flex';$('play').textContent='WRÓĆ NA ULICE →';$('intro').textContent='Gra wstrzymana. Miasto poczeka na Twój powrót.';if(!active){stopMusic();if(engineGain)engineGain.gain.value=0;}}
function start(){if(dead){player.car=null;player.x=1240;player.y=1873;player.hp=100;wanted=0;arrest=0;invincible=5;dead=false;job=null;officers.length=0;policeBullets.length=0;navRoute=[];for(const c of cars)if(c.police){c.ai=false;c.deployed=0;}toast('Wracasz na ulice. Uważaj na ruch.');}active=true;started=true;frameTime=0;acc=0;$('overlay').style.display='none';resetInput();initAudio();if(audio&&(soundOn||musicOn)){nextMusicTime=audio.currentTime+.05;audio.resume().catch(()=>{});}}
function die(reason){if(dead)return;dead=true;active=false;cash=Math.max(0,cash-150);save();resetInput();$('overlay').style.display='flex';$('intro').textContent=reason+' Koszt powrotu: do 150 zł. Zebrana gotówka i rekord są zapisywane na tym urządzeniu.';$('play').textContent='WRÓĆ DO MIASTA →';stopMusic();if(engineGain)engineGain.gain.value=0;}
function hurt(n){if(invincible>0||dead)return;player.hp=Math.max(0,player.hp-n);invincible=.65;shake=6;if(player.hp<=0)die('Koniec przejażdżki.');}
function nearestCar(){let best=null,d=64;for(const c of cars)if(c.hp>0){const dd=dist(c,player);if(dd<d){best=c;d=dd;}}return best;}
function action(){if(!active)return;if(player.car){const c=player.car;if(Math.abs(c.s)>110){toast('Zwolnij przed wysiadaniem.');return;}for(const side of [1,-1,2]){let a=c.a+Math.PI/2*side,x=c.x+Math.cos(a)*40,y=c.y+Math.sin(a)*40;if(!blocked(x,y,10)&&!cars.some(o=>o!==c&&Math.hypot(o.x-x,o.y-y)<26)){player.x=x;player.y=y;player.car=null;c.s*=.3;invincible=1;toast('Pieszo · mysz celuje, R zmienia broń');return;}}toast('Brak miejsca. Odsuń auto od przeszkody.');return;}let c=nearestCar();if(!c){toast('Podejdź bliżej sprawnego auta.');return;}if(c.ai)crime(c.police?1.2:.55);c.ai=false;c.parked=false;player.car=c;player.x=c.x;player.y=c.y;toast(c.type.name+' · Shift / HAMULEC = ręczny');tone(160,.12,'triangle');}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-75,75),vy:rand(-75,75),life:rand(.2,.6),max:.6,color});if(particles.length>260)particles.splice(0,particles.length-260);}
function damageCar(c,n){if(c.hp<=0)return;c.hp=Math.max(0,c.hp-n);if(c.hp<=0){c.ai=false;c.s=0;c.deadTime=clock;explosions.push({x:c.x,y:c.y,age:0,seed:rand(0,TAU)});if(explosions.length>18)explosions.shift();burst(c.x,c.y,'#ffcb75',42);tone(70,.4,'sawtooth',.06);shake=9;if(player.car===c){player.car=null;for(const a of [c.a+Math.PI/2,c.a-Math.PI/2,c.a+Math.PI]){let x=c.x+Math.cos(a)*48,y=c.y+Math.sin(a)*48;if(!blocked(x,y)){player.x=x;player.y=y;break;}}hurt(38);invincible=2;toast('Auto zniszczone. Znajdź następne.');}}}
function shoot(){if(!active||player.car||fireCooldown>0)return;const w=weapons[weapon];fireCooldown=w.rate;crime(.14);tone(weapon===2?85:180,.075,'sawtooth',.04);for(let i=0;i<w.count;i++){let a=player.a+rand(-w.spread,w.spread);bullets.push({x:player.x+Math.cos(a)*15,y:player.y+Math.sin(a)*15,a,life:w.life,damage:w.damage});}burst(player.x+Math.cos(player.a)*18,player.y+Math.sin(player.a)*18,'#fff1b0',3);for(const p of peds)if(dist(p,player)<230){p.panic=5;p.a=Math.atan2(p.y-player.y,p.x-player.x);}}
function cycle(){weapon=(weapon+1)%3;toast(weapons[weapon].name);}
const missionDefs=[
{id:'taxi',title:'01 / Pierwszy kurs',description:'Odbierz pasażera przy placu Defilad i przewieź go na stadion przez Wisłę.',reward:650,time:150,steps:[{x:1240,y:1870,label:'Odbierz pasażera przy placu Defilad',mode:'car'},{x:2750,y:1850,label:'Wysadź pasażera przy Stadionie Narodowym',mode:'car'}]},
{id:'courier',title:'02 / Kurier na Starówce',description:'Dwie dostawy: okolice Zamku Królewskiego i Centrum Nauki Kopernik. Ostatnie metry pokonaj pieszo.',reward:900,time:210,steps:[{x:1900,y:970,label:'Dostarcz paczkę pod Zamek — wysiądź',mode:'foot'},{x:1950,y:1350,label:'Dostarcz paczkę do Kopernika — wysiądź',mode:'foot'}]},
{id:'bridges',title:'03 / Warszawska pętla',description:'Przejedź przez trzy punkty po obu stronach rzeki. Liczy się czas i sprawne auto.',reward:1200,time:210,steps:[{x:2500,y:1425,label:'Przekrocz most Świętokrzyski',mode:'car'},{x:1900,y:1825,label:'Wróć mostem Poniatowskiego',mode:'car'},{x:2500,y:2625,label:'Przejedź mostem Łazienkowskim',mode:'car'}]},
{id:'escape',title:'04 / Zniknąć na Woli',description:'Zaczynasz z dwiema gwiazdkami. Zgub radiowozy i piesze patrole, potem dojedź do warsztatu.',reward:1500,time:240,steps:[{x:640,y:1530,label:'Zgub pościg, potem wróć do warsztatu',mode:'escape'}]},
{id:'explore',title:'05 / Miasto po godzinach',description:'Odwiedź rynek Starego Miasta, a potem zakończ spacer w Łazienkach. Bez limitu czasu.',reward:800,time:0,steps:[{x:1600,y:800,label:'Podejdź do fontanny na rynku',mode:'foot'},{x:1500,y:2670,label:'Dotrzyj pieszo do wejścia do Łazienek',mode:'foot'}]}
];
const completed=new Set();try{const a=JSON.parse(localStorage.getItem('crimecity-warsaw-missions')||'[]');if(Array.isArray(a))for(const id of a)if(missionDefs.some(m=>m.id===id))completed.add(id);}catch{}
let panelOpen=null,panelWasActive=false,navRoute=[],navRefresh=0;
function roadRoute(from,to){const available=[];for(let ix=0;ix<8;ix++)for(let iy=0;iy<8;iy++)if([0,1,2,3].some(d=>edgeValid(ix,iy,d)))available.push({ix,iy,x:OFFSET+ix*STEP,y:OFFSET+iy*STEP});const near=p=>available.reduce((a,b)=>dist(a,p)<dist(b,p)?a:b);const a=near(from),b=near(to),key=p=>p.ix+','+p.iy,queue=[a],previous=new Map([[key(a),null]]);let end=null;while(queue.length){const n=queue.shift();if(key(n)===key(b)){end=n;break;}for(let d=0;d<4;d++){if(!edgeValid(n.ix,n.iy,d))continue;const v={ix:n.ix+dx[d],iy:n.iy+dy[d]};v.x=OFFSET+v.ix*STEP;v.y=OFFSET+v.iy*STEP;if(!previous.has(key(v))){previous.set(key(v),n);queue.push(v);}}}if(!end)return [];const path=[to];while(end){path.push(end);end=previous.get(key(end));}path.push(from);return path.reverse();}
function pauseForPanel(name){if(!started||dead)return;if(panelOpen)closePanel();panelWasActive=active;active=false;resetInput();stopMusic();if(engineGain)engineGain.gain.value=0;panelOpen=name;$(name).hidden=false;if(name==='atlas')drawAtlas();else renderMissions();}
function closePanel(){if(!panelOpen)return;$(panelOpen).hidden=true;panelOpen=null;active=panelWasActive;frameTime=0;acc=0;if(active&&audio&&(musicOn||soundOn))audio.resume().catch(()=>{});}
function renderMissions(){$('missionList').innerHTML=missionDefs.map(m=>'<article class="missionCard"><div><b>'+m.title+'</b><p>'+m.description+'</p><small>'+m.reward+' zł · '+(m.time?m.time+' sekund':'bez limitu')+(completed.has(m.id)?' · UKOŃCZONA':'')+'</small></div><button class="small acceptMission" data-id="'+m.id+'">'+(job&&job.id===m.id?'AKTYWNA':'START')+'</button></article>').join('');$('missionProgress').textContent=completed.size+' / '+missionDefs.length+' misji ukończonych';$('cancelMission').hidden=!job;}
function beginMission(id){const m=missionDefs.find(v=>v.id===id);if(!m)return;if(job&&job.id===id){closePanel();return;}job={id:m.id,index:0,time:m.time||Infinity,reward:m.reward,target:m.steps[0]};navRoute=roadRoute(player,job.target);navRefresh=clock+2;closePanel();if(m.id==='escape'){crime(Math.max(0,2-wanted));dispatchPatrol();dispatchPatrol();}toast(m.title+' · '+job.target.label);hud();}
function advanceMission(dt){if(!job)return;const m=missionDefs.find(v=>v.id===job.id);job.time-=dt;if(job.time<=0){job=null;navRoute=[];toast('Czas minął. Misję możesz powtórzyć w panelu MISJE.');return;}const target=job.target,mode=target.mode,near=dist(player,target)<(mode==='foot'?30:58),stopped=!player.car||Math.abs(player.car.s)<28,valid=mode==='foot'?!player.car:mode==='escape'?!!player.car&&wanted===0:!!player.car;if(near&&stopped&&valid){job.index++;tone(620,.2,'triangle');if(job.index>=m.steps.length){cash+=job.reward;completed.add(m.id);try{localStorage.setItem('crimecity-warsaw-missions',JSON.stringify([...completed]));}catch{}save();toast('MISJA UKOŃCZONA · +'+job.reward+' zł');job=null;navRoute=[];}else{job.target=m.steps[job.index];navRoute=roadRoute(player,job.target);toast(job.target.label);}}if(job&&clock>navRefresh){navRefresh=clock+2;navRoute=roadRoute(player,job.target);}}
function takeJob(){pauseForPanel('missions');}
$('missionList').addEventListener('click',e=>{const button=e.target.closest('[data-id]');if(button)beginMission(button.dataset.id);});$('closeMissions').addEventListener('click',closePanel);$('closeAtlas').addEventListener('click',closePanel);$('cancelMission').addEventListener('click',()=>{job=null;navRoute=[];renderMissions();hud();});$('mapWrap').addEventListener('click',()=>pauseForPanel('atlas'));$('mapWrap').addEventListener('keydown',e=>{if(e.code==='Enter'||e.code==='Space'){e.preventDefault();pauseForPanel('atlas');}});
function drawAtlas(){const g=$('atlasCanvas').getContext('2d'),size=800,s=size/WORLD;g.drawImage(mapCanvas,0,0,size,size);g.fillStyle='#0b242a25';g.fillRect(0,0,size,size);g.lineJoin='round';if(job&&navRoute.length){g.strokeStyle='#ffe596';g.lineWidth=3;g.beginPath();navRoute.forEach((p,i)=>i?g.lineTo(p.x*s,p.y*s):g.moveTo(p.x*s,p.y*s));g.stroke();circle(g,job.target.x*s,job.target.y*s,8,'#f2bd65');}for(const l of landmarks){circle(g,l.x*s,l.y*s,3,'#faf0c8');const label=l.name;g.font='bold 10px Arial';g.textAlign='center';const width=g.measureText(label).width+10;rect(g,l.x*s-width/2,l.y*s-24,width,15,'#10241eef');textAt(g,label,l.x*s,l.y*s-13,10,'#eff0ce');}for(const b of bridges)textAt(g,b.name,riverCenter(b.y)*s,b.y*s-5,7,'#fff2bd');for(const p of garages){circle(g,p.x*s,p.y*s,7,'#d5ea91');textAt(g,'G',p.x*s,p.y*s+3,9,'#203c24');}circle(g,player.x*s,player.y*s,7,'#fff');circle(g,player.x*s,player.y*s,4,'#d86c40');textAt(g,'TY',player.x*s,player.y*s+20,11,'#fff');$('atlasGoal').textContent=job?job.target.label:'Dotknij MISJE, aby wybrać zadanie. Zielone G oznacza warsztat.';}
const officers=[],policeBullets=[];
function clearPath(a,b,r=9){const n=Math.ceil(dist(a,b)/16);for(let i=1;i<=n;i++)if(blocked(a.x+(b.x-a.x)*i/n,a.y+(b.y-a.y)*i/n,r))return false;return true;}
function walkRoute(a,b){const S=40,N=WORLD/S;const nearest=p=>{let best=null,score=Infinity;for(let x=Math.round(p.x/S)-2;x<=Math.round(p.x/S)+2;x++)for(let y=Math.round(p.y/S)-2;y<=Math.round(p.y/S)+2;y++){let q={x:x*S,y:y*S,gx:x,gy:y};if(x<1||y<1||x>=N||y>=N||blocked(q.x,q.y,9)||!clearPath(p,q))continue;let d=dist(p,q);if(d<score){score=d;best=q;}}return best;};let start=nearest(a),goal=nearest(b);if(!start||!goal)return [];const key=p=>p.gx+','+p.gy,open=[{...start,cost:0,score:dist(start,goal)}],prev=new Map(),costs=new Map([[key(start),0]]);let found=null;for(let count=0;open.length&&count<1800;count++){open.sort((a,b)=>a.score-b.score);const n=open.shift();if(n.gx===goal.gx&&n.gy===goal.gy){found=n;break;}for(const [xx,yy] of [[1,0],[-1,0],[0,1],[0,-1]]){const q={gx:n.gx+xx,gy:n.gy+yy,x:(n.gx+xx)*S,y:(n.gy+yy)*S},k=key(q),cost=n.cost+S;if(blocked(q.x,q.y,9)||!clearPath(n,q)||cost>=(costs.get(k)??Infinity))continue;costs.set(k,cost);prev.set(k,n);open.push({...q,cost,score:cost+dist(q,goal)});}}if(!found)return [];const path=[b];while(found){path.push(found);found=prev.get(key(found));}return path.reverse();}
function dispatchPatrol(){let c=null;for(let i=0;i<12&&!c;i++)c=spawnCar(cars.length,true);if(!c)return;const slots=[];for(let ix=0;ix<8;ix++)for(let iy=0;iy<8;iy++)for(let d=0;d<4;d++){if(!edgeValid(ix,iy,d))continue;const p=pathPoint(ix,iy,d),distance=dist(p,player);if(distance>480&&distance<900&&!cars.some(o=>o!==c&&dist(o,p)<85))slots.push({ix,iy,d,...p});}if(!slots.length)return;const p=slots[Math.floor(rand(0,slots.length))];c.x=p.x;c.y=p.y;c.ix=p.ix;c.iy=p.iy;c.a=p.d*Math.PI/2;c.s=70;setNext(c,p.d);if(!cars.includes(c))cars.push(c);}
function dismount(c){if(c.deployed||clock<(c.nextDismount||0)||officers.length>=12)return;c.s=0;c.deployed=0;for(const side of [-1,1]){const a=c.a+side*Math.PI/2,p={x:c.x+Math.cos(a)*31,y:c.y+Math.sin(a)*31};if(pedestrianBlocked(p.x,p.y))continue;officers.push({...p,a,home:c,hp:70,color:'#31516b',s:103,path:[],repath:0,shot:clock+2,step:0,grab:0});c.deployed++;}c.nextDismount=clock+8;}
function updateOfficers(dt){for(const c of cars)if(c.police&&c.ai&&c.hp>0&&wanted>=.5&&!player.car&&dist(c,player)<165&&Math.abs(c.s)<75)dismount(c);
for(let i=officers.length-1;i>=0;i--){const o=officers[i];if(o.hp<=0){bodies.push({x:o.x,y:o.y,a:o.a,color:o.color});if(bodies.length>120)bodies.shift();o.home.deployed=Math.max(0,(o.home.deployed||1)-1);officers.splice(i,1);continue;}const returning=wanted===0||(player.car&&dist(o,player)>430),target=returning?o.home:player;if(returning&&dist(o,o.home)<46&&o.home.hp>0){o.home.deployed=Math.max(0,(o.home.deployed||1)-1);o.home.nextDismount=clock+6;officers.splice(i,1);continue;}if(dist(o,player)>1200){o.home.deployed=Math.max(0,(o.home.deployed||1)-1);officers.splice(i,1);continue;}
let goal=target;if(!clearPath(o,target)){if(clock>o.repath){o.path=walkRoute(o,target);o.repath=clock+1.1;}while(o.path.length&&dist(o,o.path[0])<18)o.path.shift();goal=o.path[0]||o;}else o.path=[];const a=Math.atan2(goal.y-o.y,goal.x-o.x),speed=returning?80:103;for(const offset of [0,.6,-.6,1.2,-1.2]){const x=o.x+Math.cos(a+offset)*speed*dt,y=o.y+Math.sin(a+offset)*speed*dt;if(!pedestrianBlocked(x,y)){o.x=x;o.y=y;o.a=a+offset;break;}}o.step+=dt*9;
if(!returning&&dist(o,player)<23&&!player.car){o.grab+=dt;toastUntil=Math.max(toastUntil,clock+.2);$('toast').textContent='POLICJA · uciekaj sprintem!';$('toast').style.opacity='1';if(o.grab>1.8)die('Zatrzymany przez pieszy patrol.');}else o.grab=Math.max(0,o.grab-dt*2);
if(!returning&&wanted>=3&&dist(o,player)<210&&dist(o,player)>45&&clock>o.shot&&clearPath(o,player)){o.shot=clock+1.5;const a=Math.atan2(player.y-o.y,player.x-o.x)+rand(-.1,.1);policeBullets.push({x:o.x+Math.cos(a)*14,y:o.y+Math.sin(a)*14,a,life:.7});tone(125,.06,'square',.018);}
}
for(let i=policeBullets.length-1;i>=0;i--){const b=policeBullets[i];b.x+=Math.cos(b.a)*430*dt;b.y+=Math.sin(b.a)*430*dt;b.life-=dt;let hit=blocked(b.x,b.y,1);for(const c of cars)if(pedestrianContact(b.x,b.y,c,1)){damageCar(c,7);hit=true;break;}if(!player.car&&dist(b,player)<10){hurt(10);hit=true;}if(hit||b.life<=0)policeBullets.splice(i,1);}}
$('play').addEventListener('click',start);$('pause').addEventListener('click',pause);$('sound').addEventListener('click',()=>{initAudio();soundOn=!soundOn;$('sound').textContent='DŹW. '+(soundOn?'WŁ.':'WYŁ.');$('sound').setAttribute('aria-pressed',String(soundOn));$('sound').setAttribute('aria-label',soundOn?'Wyłącz dźwięk':'Włącz dźwięk');if(soundOn&&audio)audio.resume().catch(()=>{});});$('night').addEventListener('click',()=>{night=!night;$('night').textContent=night?'DZIEŃ':'NOC';$('night').setAttribute('aria-pressed',String(night));});
$('enter').addEventListener('pointerdown',e=>{e.preventDefault();action();});$('switch').addEventListener('pointerdown',e=>{e.preventDefault();cycle();});$('job').addEventListener('pointerdown',e=>{e.preventDefault();takeJob();});
for(const [id,prop] of [['fire','fire'],['brake','brake']]){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);input[prop]=true;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>input[prop]=false);}
function joyMove(e){const r=$('joy').getBoundingClientRect(),m=r.width*.34;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y);if(l>m){x*=m/l;y*=m/l;}input.x=x/m;input.y=y/m;$('stick').style.transform=`translate(${x}px,${y}px)`;mouseAim=false;}
$('joy').addEventListener('pointerdown',e=>{if(input.id!==null)return;e.preventDefault();input.id=e.pointerId;$('joy').setPointerCapture(e.pointerId);joyMove(e);});$('joy').addEventListener('pointermove',e=>{if(e.pointerId===input.id)joyMove(e);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('joy').addEventListener(ev,e=>{if(e.pointerId===input.id){input.id=null;input.x=input.y=0;$('stick').style.transform='';}});
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'&&panelOpen){closePanel();return;}if(e.code==='KeyM'){pauseForPanel('atlas');return;}if(e.code==='Escape'||e.code==='KeyP'){pause();return;}if(panelOpen)return;keys[e.code]=true;if(e.code==='KeyE')action();if(e.code==='KeyR')cycle();if(e.code==='KeyF')takeJob();});addEventListener('keyup',e=>{keys[e.code]=false;});addEventListener('blur',()=>{if(active)pause();else resetInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)pause();});
cv.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){input.mouseX=e.clientX;input.mouseY=e.clientY;mouseAim=true;}});cv.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'){cv.setPointerCapture(e.pointerId);input.fire=true;}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])cv.addEventListener(ev,()=>input.fire=false);cv.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
function lightGreen(c){const phase=(clock+((c.ix+c.iy)%3)*2)%14;return c.dir%2===0?phase<6.4:phase>7&&phase<13.4;}
function traffic(c,dt){c.age+=dt;if(c.deployed){c.s=0;return;}if(c.hp<=0)return;const d=dist(c,c.target);if(d<35){chooseNext(c);c.stuck=0;}let desired=Math.atan2(c.target.y-c.y,c.target.x-c.x),diff=angle(desired-c.a);if(c.police&&wanted>=.5&&dist(c,player)<440){let clear=true;for(let i=1;i<=12;i++)if(blocked(c.x+(player.x-c.x)*i/12,c.y+(player.y-c.y)*i/12,20)){clear=false;break;}if(clear){desired=Math.atan2(player.y-c.y,player.x-c.x);diff=angle(desired-c.a);}}c.a+=clamp(diff,-2.8*dt,2.8*dt);let target=c.police&&wanted>0?175+Math.ceil(wanted)*17:105+(c.type.max-200)*.10;if(Math.abs(diff)>.35)target*=.6;
if(!c.police&&d>57&&d<106&&!lightGreen(c))target=0;
for(const o of cars){if(c===o)continue;let xx=o.x-c.x,yy=o.y-c.y,forward=xx*Math.cos(c.a)+yy*Math.sin(c.a),side=Math.abs(-xx*Math.sin(c.a)+yy*Math.cos(c.a));if(forward>0&&forward<(c.type.w+o.type.w)/2+35+c.s*.25&&side<(c.type.h+o.type.h)/2+3)target=Math.min(target,Math.max(0,o.s-20));}
if(c.police&&wanted>=.5&&!player.car&&dist(c,player)<185)target=Math.min(target,30);c.s+=(target-c.s)*Math.min(1,dt*2.5);let nx=c.x+Math.cos(c.a)*c.s*dt,ny=c.y+Math.sin(c.a)*c.s*dt;if(!carBlocked(c,nx,ny)){c.x=nx;c.y=ny;}else{c.s=0;c.stuck+=dt;}
if(c.s<8)c.stuck+=dt;else c.stuck=0;if(c.stuck>12&&dist(c,player)>700){const p=pathPoint(c.ix,c.iy,c.dir);if(!cars.some(o=>o!==c&&dist(o,p)<100)){c.x=p.x;c.y=p.y;c.a=c.dir*Math.PI/2;chooseNext(c);c.stuck=0;}}
}
function overlap(a,b){const axes=[{x:Math.cos(a.a),y:Math.sin(a.a)},{x:-Math.sin(a.a),y:Math.cos(a.a)},{x:Math.cos(b.a),y:Math.sin(b.a)},{x:-Math.sin(b.a),y:Math.cos(b.a)}];let min=Infinity,normal=null;for(const n of axes){let ra=Math.abs(n.x*Math.cos(a.a)+n.y*Math.sin(a.a))*a.type.w/2+Math.abs(-n.x*Math.sin(a.a)+n.y*Math.cos(a.a))*a.type.h/2,rb=Math.abs(n.x*Math.cos(b.a)+n.y*Math.sin(b.a))*b.type.w/2+Math.abs(-n.x*Math.sin(b.a)+n.y*Math.cos(b.a))*b.type.h/2,delta=(a.x-b.x)*n.x+(a.y-b.y)*n.y,o=ra+rb-Math.abs(delta);if(o<=0)return null;if(o<min){min=o;normal={x:n.x*(delta>=0?1:-1),y:n.y*(delta>=0?1:-1)};}}return {n:normal,d:min};}
function carCollisions(){const buckets=new Map();for(const c of cars){let k=Math.floor(c.x/100)+','+Math.floor(c.y/100);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(c);}const checked=new Set();for(let i=0;i<cars.length;i++){const a=cars[i],gx=Math.floor(a.x/100),gy=Math.floor(a.y/100);for(let xx=-1;xx<=1;xx++)for(let yy=-1;yy<=1;yy++)for(const b of buckets.get((gx+xx)+','+(gy+yy))||[]){if(a===b)continue;const j=cars.indexOf(b),key=Math.min(i,j)+':'+Math.max(i,j);if(checked.has(key))continue;checked.add(key);if(dist(a,b)>(a.type.w+b.type.w)/2)continue;const hit=overlap(a,b);if(!hit)continue;const move=hit.d*.51;if(!carBlocked(a,a.x+hit.n.x*move,a.y+hit.n.y*move)){a.x+=hit.n.x*move;a.y+=hit.n.y*move;}if(!carBlocked(b,b.x-hit.n.x*move,b.y-hit.n.y*move)){b.x-=hit.n.x*move;b.y-=hit.n.y*move;}let impact=Math.abs((Math.cos(a.a)*a.s-Math.cos(b.a)*b.s)*hit.n.x+(Math.sin(a.a)*a.s-Math.sin(b.a)*b.s)*hit.n.y);if(impact>32&&clock>a.hit&&clock>b.hit){a.hit=b.hit=clock+.45;damageCar(a,impact*.065);damageCar(b,impact*.065);burst((a.x+b.x)/2,(a.y+b.y)/2,'#e9c27b',7);if(a===player.car||b===player.car){crime(.12);shake=Math.min(10,impact/24);tone(80,.12,'sawtooth');}}a.s*=.65;b.s*=.65;}}}
function update(dt){pumpMusic();clock+=dt;invincible=Math.max(0,invincible-dt);fireCooldown=Math.max(0,fireCooldown-dt);shake*=.9;if(clock>toastUntil)$('toast').style.opacity='0';
let ax=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),ay=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0),braking=keys.ShiftLeft||keys.ShiftRight||input.brake;
if(player.car){const c=player.car;let gas=-ay,steer=ax;if(Math.hypot(input.x,input.y)>.12){const desired=Math.atan2(input.y,input.x),dif=angle(desired-c.a);steer=clamp(dif*1.6,-1,1);gas=Math.max(.3,Math.hypot(input.x,input.y));}else if(input.fire)gas=1;let speed=Math.abs(c.s),turn=steer*c.type.grip*clamp(speed/110,0,1)*(c.s<0?-1:1)*dt;let na=c.a+turn*(braking?1.5:1);if(!carBlocked(c,c.x,c.y,na))c.a=na;c.s+=gas*c.type.acc*dt;c.s*=Math.exp(-(braking?5:gas? .23:1.2)*dt);c.s=clamp(c.s,-95,c.type.max*(c.hp<25?.65:1));let nx=c.x+Math.cos(c.a)*c.s*dt,ny=c.y+Math.sin(c.a)*c.s*dt;if(!carBlocked(c,nx,ny)){c.x=nx;c.y=ny;distance+=Math.abs(c.s)*dt;}else{if(speed>35&&clock>c.hit){damageCar(c,speed*.07);c.hit=clock+.45;shake=speed/30;burst(c.x+Math.cos(c.a)*c.type.w/2,c.y+Math.sin(c.a)*c.type.w/2,'#e8bd72');tone(75,.12,'sawtooth');}c.s*=-.24;}if(speed>90&&(braking||Math.abs(steer)>.6)&&Math.random()<.5){skids.push({x:c.x,y:c.y,a:c.a,t:clock,w:c.type.h});if(skids.length>220)skids.shift();}if(player.car){player.x=c.x;player.y=c.y;player.a=c.a;}}
else{ax+=input.x;ay+=input.y;const length=Math.hypot(ax,ay),speed=braking?175:115;if(length>.1){ax/=Math.max(1,length);ay/=Math.max(1,length);if(!mouseAim)player.a=Math.atan2(ay,ax);movePedestrian(ax*speed*dt,ay*speed*dt);}if(mouseAim)player.a=Math.atan2((input.mouseY-H/2)/zoom+camera.y-player.y,(input.mouseX-W/2)/zoom+camera.x-player.x);if(input.fire||keys.Space)shoot();}
for(const c of cars)if(c.ai)traffic(c,dt);else if(c!==player.car&&c.hp>0&&Math.abs(c.s)>1){let nx=c.x+Math.cos(c.a)*c.s*dt,ny=c.y+Math.sin(c.a)*c.s*dt;if(!carBlocked(c,nx,ny)){c.x=nx;c.y=ny;}c.s*=Math.exp(-3*dt);}carCollisions();if(player.car){player.x=player.car.x;player.y=player.car.y;}
for(let i=peds.length-1;i>=0;i--){const p=peds[i];p.panic=Math.max(0,p.panic-dt);p.step+=dt*(p.panic?12:5);if(Math.random()<dt*.5)p.a+=rand(-1,1);let nx=p.x+Math.cos(p.a)*p.s*(p.panic?3:1)*dt,ny=p.y+Math.sin(p.a)*p.s*(p.panic?3:1)*dt;if(!blocked(nx,ny,7)&&(!onRoad(nx,ny)||p.panic)){p.x=nx;p.y=ny;}else p.a+=2;for(const c of cars){if(dist(p,c)<c.type.w/2+8&&Math.abs(c.s)>60){p.hp=0;if(c===player.car)crime(.4);break;}}if(p.hp<=0){bodies.push({x:p.x,y:p.y,a:p.a,color:p.color});if(bodies.length>120)bodies.shift();peds.splice(i,1);}}
resolvePedestrianCars();
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];let hit=false;for(let step=0;step<3&&!hit;step++){b.x+=Math.cos(b.a)*670*dt/3;b.y+=Math.sin(b.a)*670*dt/3;if(blocked(b.x,b.y,1)){hit=true;burst(b.x,b.y,'#b9b5a0',3);break;}for(const c of cars){const xx=b.x-c.x,yy=b.y-c.y,ca=Math.cos(c.a),sa=Math.sin(c.a);if(Math.abs(xx*ca+yy*sa)<c.type.w/2&&Math.abs(-xx*sa+yy*ca)<c.type.h/2){damageCar(c,b.damage);hit=true;burst(b.x,b.y,'#e5c684',4);break;}}if(!hit)for(const o of officers)if(dist(o,b)<10){o.hp-=b.damage;crime(.35);hit=true;break;}if(!hit)for(const p of peds)if(dist(p,b)<9){p.hp-=b.damage;crime(.2);hit=true;break;}}b.life-=dt;if(hit||b.life<=0)bullets.splice(i,1);}
updateOfficers(dt);let cops=cars.filter(c=>c.police&&c.ai&&c.hp>0);if(wanted>=.5&&cops.length<Math.ceil(wanted)+1&&Math.random()<dt*.4)dispatchPatrol();
let visiblePolice=cops.some(c=>dist(c,player)<430)||officers.some(o=>dist(o,player)<340&&clearPath(o,player));if(wanted>0&&clock-lastCrime>10&&!visiblePolice){wanted=Math.max(0,wanted-dt*.11);if(wanted===0){cash+=100;save();toast('POŚCIG ZGUBIONY · +100 zł');}}
let cornered=cops.some(c=>dist(c,player)<65);if(cornered&&player.car&&Math.abs(player.car.s)<35){arrest+=dt;if(arrest>=4)die('Policja Cię zatrzymała.');}else arrest=Math.max(0,arrest-dt*2);
for(const g of garages)if(player.car&&dist(g,player)<64&&Math.abs(player.car.s)<22&&player.car.hp<99){player.car.hp=100;player.hp=100;toast('Warsztat · auto i zdrowie przywrócone');tone(450,.2,'triangle');}
advanceMission(dt);
for(let i=explosions.length-1;i>=0;i--){explosions[i].age+=dt;if(explosions[i].age>3.2)explosions.splice(i,1);}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.life<=0)particles.splice(i,1);}if(peds.length<135&&Math.random()<dt*2)spawnPed();for(let i=cars.length-1;i>=0;i--)if(cars[i].hp<=0&&clock-cars[i].deadTime>20&&dist(cars[i],player)>650){cars.splice(i,1);spawnCar(i);}
if(engineGain){engineGain.gain.setTargetAtTime(soundOn&&player.car ? .018 : 0,audio.currentTime,.08);engine.frequency.setTargetAtTime(player.car?45+Math.abs(player.car.s)*.6:40,audio.currentTime,.08);if(soundOn&&visiblePolice&&Math.floor(clock*3)!==Math.floor((clock-dt)*3))tone(Math.floor(clock*3)%2?650:850,.25,'sine',.016);}
uiTimer+=dt;if(uiTimer>.1){uiTimer=0;hud();}}
function hud(){const c=player.car;$('mission').classList.toggle('job-active',!!job);$('switch').textContent=weapons[weapon].name;$('health').textContent=Math.ceil(player.hp);$('healthbar').style.width=player.hp+'%';$('healthbar').style.background=player.hp<30?'#ed8b70':'#cdeb8b';$('wanted').textContent='★ '.repeat(Math.ceil(wanted))+'☆ '.repeat(5-Math.ceil(wanted));$('money').textContent=String(cash).padStart(5,'0')+' zł';$('speed').innerHTML=(c?Math.round(Math.abs(c.s)*.48):0)+' <small>KM/H</small>';$('enter').textContent=arrest>.2?'ZATRZYMANIE '+Math.min(100,Math.round(arrest*25))+'%':c?'WYJDŹ Z AUTA':'WEJDŹ DO AUTA';$('fire').textContent=c?'GAZ':'STRZAŁ';$('brake').textContent=c?'HAMULEC':'BIEG';$('district').textContent=district(player);if(job)$('mission').innerHTML='<b>'+missionDefs.find(m=>m.id===job.id).title+'</b>'+job.target.label+'<br>'+(Number.isFinite(job.time)?Math.ceil(job.time)+' s · ':'')+(job.index+1)+' / '+missionDefs.find(m=>m.id===job.id).steps.length;else $('mission').innerHTML='<b>WARSZAWA / '+completed.size+' Z 5 MISJI</b>MISJE / F — wybór zadania.<br>Dotknij minimapy — plan miasta.';}
function visible(p,r=80){return Math.abs(p.x-camera.x)<W/(2*zoom)+r&&Math.abs(p.y-camera.y)<H/(2*zoom)+r;}
function drawCar(c){const g=ctx,t=c.type;g.save();g.translate(c.x,c.y);g.rotate(c.a);rect(g,-t.w/2+4,-t.h/2+5,t.w,t.h,'#0b171960');rect(g,-t.w*.36,-t.h/2-3,t.w*.2,t.h+6,'#1a2120');rect(g,t.w*.2,-t.h/2-3,t.w*.2,t.h+6,'#1a2120');rect(g,-t.w/2,-t.h/2,t.w,t.h,c.hp<=0?'#333c38':c.color);rect(g,-t.w/2+3,-t.h/2+2,t.w-7,2,'#fff4');rect(g,-t.w*.15,-t.h*.40,t.w*.37,t.h*.80,'#29434b');rect(g,-t.w*.06,-t.h*.40,t.w*.17,t.h*.80,c.hp<=0?'#464a43':c.color);rect(g,-t.w*.36,-t.h*.34,t.w*.15,t.h*.68,'#344a4e');if(t===types[4]){rect(g,-t.w*.44,-t.h*.45,t.w*.58,t.h*.9,'#a7a89b');for(let x=-t.w*.4;x<t.w*.1;x+=7)rect(g,x,-t.h*.4,1,t.h*.8,'#777d73');}if(t===types[7]){for(let x=-28;x<28;x+=10){rect(g,x,-t.h/2,7,3,'#263e43');rect(g,x,t.h/2-3,7,3,'#263e43');}}if(t===types[3])rect(g,-4,-4,8,8,'#edce63');if(t===types[8]){rect(g,-7,-2,12,4,'#d4634b');rect(g,-3,-6,4,12,'#d4634b');}if(c.police){rect(g,-12,-t.h/2,10,t.h,'#253b47');rect(g,-3,-8,5,8,Math.sin(clock*12)>0?'#f57863':'#8d4946');rect(g,-3,0,5,8,Math.sin(clock*12)<0?'#85bdf1':'#48618b');}rect(g,t.w/2-2,-t.h/2+3,3,4,'#f1e7bd');rect(g,t.w/2-2,t.h/2-7,3,4,'#f1e7bd');rect(g,-t.w/2,-t.h/2+3,2,4,'#c4543c');rect(g,-t.w/2,t.h/2-7,2,4,'#c4543c');if(c.hp<30){circle(g,-t.w*.25,0,8+Math.sin(clock*5)*3,'#262b2780');}g.restore();}
// Bodies remain below live actors; bounded count protects long mobile sessions.
function drawBody(b){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.a);circle(ctx,1,3,12,'#13231c50');rect(ctx,-12,-5,12,4,'#29332d');rect(ctx,-12,2,12,4,'#29332d');rect(ctx,-2,-6,12,12,b.color);rect(ctx,0,-10,4,6,b.color);rect(ctx,4,5,4,6,b.color);circle(ctx,13,0,4,'#c3aa8b');ctx.restore();}
function drawExplosion(e){const t=e.age;ctx.save();ctx.translate(e.x,e.y);
if(t<.85){const k=t/.85,r=12+70*Math.sin(k*Math.PI/2);ctx.globalAlpha=(1-k)*.8;circle(ctx,0,0,r*1.3,'#f5b552');ctx.strokeStyle='#ffe7a2';ctx.lineWidth=3*(1-k);ctx.beginPath();ctx.arc(0,0,15+k*112,0,TAU);ctx.stroke();for(let i=0;i<7;i++){const a=e.seed+i*TAU/7;circle(ctx,Math.cos(a)*r*.38,Math.sin(a)*r*.38,r*.47,i%2?'#ff973f':'#ffd57a');}circle(ctx,0,0,r*.33,'#fff4c4');}
if(t>.18){const k=(t-.18)/3.02;ctx.globalAlpha=Math.min(1,k*6)*(1-k)*.7;for(let i=0;i<5;i++){const a=e.seed+i*TAU/5;circle(ctx,Math.cos(a)*(12+k*25)+k*22,Math.sin(a)*14-k*45,13+k*26,i%2?'#333b36':'#586059');}}
ctx.restore();}
function drawPed(p,hero=false){const g=ctx;g.save();g.translate(p.x,p.y);g.rotate(p.a);circle(g,3,4,hero?9:7,'#15241966');let step=hero?Math.sin(clock*12)*2:Math.sin(p.step)*2;rect(g,-5+step,-5,8,3,'#263633');rect(g,-5-step,2,8,3,'#263633');rect(g,-4,-6,9,12,hero?'#d7e39a':p.color);circle(g,1,0,4,hero?'#e3c79e':'#c3aa8b');if(hero){rect(g,5,3,13,3,'#252f2d');if(invincible>0){g.strokeStyle='#e0f9b0';g.lineWidth=1;g.beginPath();g.arc(0,0,14,0,TAU);g.stroke();}}g.restore();}
function marker(p,label,color){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,32+Math.sin(clock*3)*3,0,TAU);ctx.stroke();circle(ctx,p.x,p.y,13,'#122b20dc');textAt(ctx,label,p.x,p.y+5,15,color);}
function draw(){ctx.setTransform(D,0,0,D,0,0);rect(ctx,0,0,W,H,'#263d33');const targetX=clamp(player.x,Math.min(WORLD/2,W/(2*zoom)),Math.max(WORLD/2,WORLD-W/(2*zoom))),targetY=clamp(player.y,Math.min(WORLD/2,H/(2*zoom)),Math.max(WORLD/2,WORLD-H/(2*zoom)));camera.x+=(targetX-camera.x)*.12;camera.y+=(targetY-camera.y)*.12;ctx.save();ctx.translate(W/2+(active?rand(-shake,shake):0),H/2+(active?rand(-shake,shake):0));ctx.scale(zoom,zoom);ctx.translate(-camera.x,-camera.y);const sx=clamp(camera.x-W/zoom/2-20,0,WORLD),sy=clamp(camera.y-H/zoom/2-20,0,WORLD),sw=Math.min(WORLD-sx,W/zoom+40),sh=Math.min(WORLD-sy,H/zoom+40);ctx.drawImage(mapCanvas,sx,sy,sw,sh,sx,sy,sw,sh);
for(const s of skids)if(visible(s)){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);rect(ctx,-7,-s.w/2,14,2,'#202a2380');rect(ctx,-7,s.w/2,14,2,'#202a2380');ctx.restore();}
for(let ix=0;ix<8;ix++)for(let iy=0;iy<8;iy++){const p={x:OFFSET+ix*STEP,y:OFFSET+iy*STEP};if(!visible(p)||Math.abs(p.x-riverCenter(p.y))<170)continue;const phase=(clock+((ix+iy)%3)*2)%14;circle(ctx,p.x-65,p.y-63,4,phase<6.4?'#b8d37c':'#d87a64');circle(ctx,p.x+65,p.y+63,4,phase>7&&phase<13.4?'#b8d37c':'#d87a64');}
for(const g of garages)if(visible(g))marker(g,'G','#ceec92');if(job&&visible(job.target))marker(job.target,'↓','#fff1a9');
for(const b of bodies)if(visible(b))drawBody(b);for(const p of peds)if(visible(p))drawPed(p);for(const c of cars)if(visible(c))drawCar(c);for(const o of officers)if(visible(o)){drawPed(o);textAt(ctx,'POLICJA',o.x,o.y-16,7,'#aecde9');}for(const b of policeBullets){circle(ctx,b.x,b.y,2,'#f69378');}if(!player.car)drawPed(player,true);
if(!player.car&&active){const c=nearestCar();if(c&&visible(c)){ctx.strokeStyle='#d7ec99';ctx.lineWidth=1;ctx.beginPath();ctx.arc(c.x,c.y,36,0,TAU);ctx.stroke();textAt(ctx,mobile?'AUTO':'[ E ]',c.x,c.y-42,10,'#ecf4c6');}}
for(const b of bullets){ctx.strokeStyle='#ffeba6';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-Math.cos(b.a)*11,b.y-Math.sin(b.a)*11);ctx.stroke();}for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);rect(ctx,p.x,p.y,3,3,p.color);}ctx.globalAlpha=1;for(const e of explosions)if(visible(e,160))drawExplosion(e);ctx.restore();
if(night){rect(ctx,0,0,W,H,'#06112088');ctx.save();ctx.translate(W/2,H/2);ctx.scale(zoom,zoom);ctx.translate(-camera.x,-camera.y);ctx.globalCompositeOperation='screen';for(const c of cars)if(visible(c)&&c.hp>0){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.a);let grad=ctx.createLinearGradient(15,0,160,0);grad.addColorStop(0,'#f5e7a340');grad.addColorStop(1,'#f5e7a300');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(15,-9);ctx.lineTo(160,-48);ctx.lineTo(160,48);ctx.lineTo(15,9);ctx.fill();ctx.restore();}ctx.restore();}drawMap();}
function drawMap(){const g=mc,s=180/WORLD;g.drawImage(mapCanvas,0,0,180,180);rect(g,0,0,180,180,'#0c29272b');for(const p of garages)circle(g,p.x*s,p.y*s,3,'#d5f192');if(job){g.strokeStyle='#ffe399';g.lineWidth=1.5;g.beginPath();navRoute.forEach((p,i)=>i?g.lineTo(p.x*s,p.y*s):g.moveTo(p.x*s,p.y*s));g.stroke();circle(g,job.target.x*s,job.target.y*s,4,'#ffd782');}for(const c of cars)if(c.police&&c.ai&&wanted>0)circle(g,c.x*s,c.y*s,2,'#eb8b78');for(const o of officers)circle(g,o.x*s,o.y*s,1.7,'#82c2ed');g.save();g.translate(player.x*s,player.y*s);g.rotate(player.a);g.fillStyle='#fff9d2';g.beginPath();g.moveTo(6,0);g.lineTo(-4,-4);g.lineTo(-2,0);g.lineTo(-4,4);g.closePath();g.fill();g.restore();}

function frame(t){if(!frameTime)frameTime=t;let delta=Math.min((t-frameTime)/1000,.1);frameTime=t;if(active){acc+=delta;while(acc+1e-9>=1/60){update(1/60);acc-=1/60;if(!active){acc=0;break;}}}else acc=0;draw();requestAnimationFrame(frame);}
addEventListener('error',e=>{$('error').style.display='block';$('error').textContent='Błąd gry: '+e.message;});hud();requestAnimationFrame(frame);
})();
