'use strict';
(() => {
const $=id=>document.getElementById(id),cv=$('game'),ctx=cv.getContext('2d',{alpha:false}),mc=$('map').getContext('2d');
const TAU=Math.PI*2, WORLD=3200, STEP=400, OFFSET=200, ROAD=116, LANE=25;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),angle=a=>Math.atan2(Math.sin(a),Math.cos(a));
let seed=7719;function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
let W=innerWidth,H=innerHeight,D=1,zoom=1,clock=0,active=false,started=false,dead=false,night=false,frameTime=0,acc=0,uiTimer=0;
let cash=0,best=0,distance=0,wanted=0,lastCrime=-100,invincible=0,job=null,jobReady=0,toastUntil=0,shake=0,fireCooldown=0,mouseAim=false;
try{best=Number(localStorage.getItem('crimecity-best-v2'))||0;cash=Number(localStorage.getItem('crimecity-cash-v2'))||0;}catch{}
const mobile=matchMedia('(pointer:coarse)').matches||W<760||new URLSearchParams(location.search).get('controls')==='touch';document.body.classList.toggle('mobile',mobile);
if(mobile)$('help').textContent='Joystick — ruch i kierunek jazdy. W aucie wychyl joystick, aby jechać. STRZAŁ celuje w kierunku ruchu; GAZ pozwala jechać prosto. HAMULEC zatrzymuje auto.';
$('record').textContent='STREET EDITION / 2.2'+(best?' · REKORD $ '+best:'');
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,1.5);cv.width=Math.round(W*D);cv.height=Math.round(H*D);zoom=mobile?(H<W?.87:.83):1.12;}resize();addEventListener('resize',resize);
const player={x:1640,y:1873,a:0,hp:100,car:null};let camera={x:player.x,y:player.y};
const keys={},input={x:0,y:0,fire:false,brake:false,id:null,mouseX:0,mouseY:0};
const buildings=[],trees=[],cars=[],peds=[],bullets=[],particles=[],explosions=[],bodies=[],skids=[],pickups=[];
const garages=[{x:240,y:1530},{x:2640,y:2330},{x:1030,y:730}];const jobs=[{x:1640,y:1870},{x:2430,y:1070},{x:430,y:2670}];
const palette=['#c95b42','#7e9fb3','#dcbf66','#6a9479','#d3d5c7','#515563','#ae7379','#e69554','#689b98'];
const types=[{name:'MONARCH',w:43,h:21,max:300,acc:175,grip:3.1},{name:'STINGER GT',w:44,h:20,max:420,acc:250,grip:3.6},{name:'BOXER VAN',w:49,h:25,max:235,acc:135,grip:2.6},{name:'CITY TAXI',w:44,h:22,max:310,acc:185,grip:3},{name:'HAULER',w:66,h:27,max:210,acc:100,grip:2.1},{name:'MINI',w:35,h:19,max:290,acc:205,grip:3.5},{name:'INTERCEPTOR',w:46,h:22,max:365,acc:220,grip:3.4},{name:'CITY BUS',w:79,h:27,max:195,acc:95,grip:2},{name:'AMBULANS',w:51,h:25,max:290,acc:170,grip:2.6}];
const weapons=[{name:'PISTOLET',rate:.25,count:1,spread:.025,damage:23,life:.65},{name:'SMG',rate:.085,count:1,spread:.075,damage:12,life:.60},{name:'STRZELBA',rate:.66,count:6,spread:.25,damage:14,life:.34}];let weapon=0,arrest=0;
function rect(g,x,y,w,h,c){g.fillStyle=c;g.fillRect(x,y,w,h);}function circle(g,x,y,r,c){g.fillStyle=c;g.beginPath();g.arc(x,y,r,0,TAU);g.fill();}
function textAt(g,t,x,y,size,color){g.fillStyle=color;g.font=`bold ${size}px Arial`;g.textAlign='center';g.fillText(t,x,y);}
function roadCenter(v){return OFFSET+Math.round((v-OFFSET)/STEP)*STEP;}function onRoad(x,y){return Math.abs(x-roadCenter(x))<ROAD/2||Math.abs(y-roadCenter(y))<ROAD/2;}
const mapCanvas=document.createElement('canvas');mapCanvas.width=WORLD;mapCanvas.height=WORLD;const mapCtx=mapCanvas.getContext('2d',{alpha:false});
function makeMap(){const g=mapCtx;rect(g,0,0,WORLD,WORLD,'#526653');
for(let x=OFFSET;x<WORLD;x+=STEP){rect(g,x-ROAD/2-18,0,ROAD+36,WORLD,'#aaa997');rect(g,0,x-ROAD/2-18,WORLD,ROAD+36,'#aaa997');rect(g,x-ROAD/2,0,ROAD,WORLD,'#41494a');rect(g,0,x-ROAD/2,WORLD,ROAD,'#41494a');}
for(let x=OFFSET;x<WORLD;x+=STEP){g.strokeStyle='#c3b989';g.lineWidth=1;g.setLineDash([17,20]);g.beginPath();g.moveTo(x,0);g.lineTo(x,WORLD);g.stroke();g.beginPath();g.moveTo(0,x);g.lineTo(WORLD,x);g.stroke();g.setLineDash([]);}
for(let x=OFFSET;x<WORLD;x+=STEP)for(let y=OFFSET;y<WORLD;y+=STEP){rect(g,x-58,y-58,116,116,'#41494a');for(let i=-3;i<=3;i++){rect(g,x+i*12-4,y-84,7,20,'#cbcebc');rect(g,x+i*12-4,y+64,7,20,'#cbcebc');rect(g,x-84,y+i*12-4,20,7,'#cbcebc');rect(g,x+64,y+i*12-4,20,7,'#cbcebc');}}
for(let ix=0;ix<7;ix++)for(let iy=0;iy<7;iy++){let x=OFFSET+ix*STEP+83,y=OFFSET+iy*STEP+83,w=234,h=234,k=(ix*3+iy*7)%13;rect(g,x-6,y-6,w+12,h+12,'#929c88');
if(k===2||k===8){rect(g,x,y,w,h,'#617b50');rect(g,x+w/2-7,y,14,h,'#beb397');rect(g,x,y+h/2-7,w,14,'#beb397');circle(g,x+w/2,y+h/2,26,'#d0cbb6');circle(g,x+w/2,y+h/2,20,'#648f92');for(let a=0;a<18;a++){let tx=x+17+rng()*(w-34),ty=y+17+rng()*(h-34);if(Math.abs(tx-x-w/2)>25&&Math.abs(ty-y-h/2)>25)trees.push({x:tx,y:ty,r:10+rng()*9});}continue;}
if(k===5){rect(g,x,y,w,h,'#646d68');for(let py=y+18;py<y+h;py+=40)for(let px=x+8;px<x+w-30;px+=46){rect(g,px,py,34,2,'#b2b59c');rect(g,px,py,2,30,'#b2b59c');}continue;}
let color=ix>3?(iy>3?'#797f82':'#9b8c79'):(iy>3?'#a69382':'#8a9a89');
for(let a=0;a<2;a++)for(let b=0;b<2;b++){const bx=x+a*128,by=y+b*128,bw=106,bh=106;buildings.push({x:bx,y:by,w:bw,h:bh});rect(g,bx+9,by+12,bw+4,bh+4,'#23332a55');rect(g,bx-3,by-3,bw+6,bh+6,color);rect(g,bx+5,by+5,bw-10,bh-10,iy>3?'#575b56':'#66716c');rect(g,bx+7,by+7,bw-14,3,'#c2c4a950');for(let u=0;u<4;u++){rect(g,bx+13+u*23,by-2,12,4,'#d2c796');rect(g,bx+13+u*23,by+bh-2,12,4,'#d2c796');}rect(g,bx+21,by+23,24,18,'#454f4b');rect(g,bx+20,by+21,23,17,'#9ca49a');for(let u=0;u<4;u++)rect(g,bx+22,by+23+u*4,19,1,'#535f59');circle(g,bx+76,by+72,13,'#49564e');circle(g,bx+75,by+70,11,'#88948c');rect(g,bx+9,by+bh-12,25,6,'#c9b47b');}
if((ix+iy)%3===0)textAt(g,['HOTEL','MARKET','RECORDS','DINER','MOTEL'][Math.floor(rng()*5)],x+52,y+66,10,'#e7c978');
for(let n=0;n<4;n++)trees.push({x:x+20+n*61,y:y-12,r:9});}
for(const t of trees){circle(g,t.x+5,t.y+6,t.r,'#263b3055');circle(g,t.x,t.y,t.r,'#355b40');circle(g,t.x-3,t.y-3,t.r*.7,'#557b4c');}
for(const p of garages){rect(g,p.x-30,p.y-26,60,52,'#304e3d');rect(g,p.x-27,p.y-23,54,46,'#759c68');textAt(g,'GARAGE',p.x,p.y+3,11,'#e1edbc');}

// Roofs, street furniture and district landmarks are drawn once, not every frame.
for(let i=0;i<buildings.length;i++){const b=buildings[i],x=b.x,y=b.y,k=i%9;
if(k===0){rect(g,x+11,y+43,83,37,'#434f50');for(let a=0;a<5;a++){rect(g,x+14+a*16,y+46,12,30,'#678b94');rect(g,x+14+a*16,y+60,12,1,'#a4babe');}}
if(k===1){rect(g,x+14,y+46,62,34,'#444c48');for(let a=0;a<6;a++)rect(g,x+16,y+48+a*5,57,2,'#8d927e');}
if(k===2){circle(g,x+53,y+55,29,'#4a5550');g.strokeStyle='#b9c1a0';g.lineWidth=2;g.beginPath();g.arc(x+53,y+55,25,0,TAU);g.stroke();textAt(g,'H',x+53,y+65,29,'#b9c1a0');}
if(k===3){rect(g,x+13,y+42,78,48,'#bfbdaa');rect(g,x+18,y+47,68,38,'#619ba1');for(let a=0;a<5;a++)rect(g,x+24+a*12,y+52,2,28,'#b5d2bb50');}
if(k===4){rect(g,x-3,y+82,112,15,'#be7358');for(let a=0;a<10;a++)rect(g,x+a*11,y+82,5,15,'#ddd3b4');}
if(k===5){rect(g,x+51,y+17,38,18,'#4a5550');rect(g,x+54,y+20,32,12,'#9caa97');for(let a=0;a<3;a++)circle(g,x+60+a*10,y+26,4,'#606d61');}
if(k===6){rect(g,x+15,y+40,75,49,'#6b7260');for(let a=0;a<6;a++){rect(g,x+20+a*11,y+44,6,39,'#92967a');}textAt(g,'STORAGE',x+52,y+68,10,'#e6d9a7');}
if(k===7){rect(g,x+63,y+16,29,14,'#dbb85e');textAt(g,'FM 96',x+77,y+26,8,'#3c4d41');g.strokeStyle='#c2c6b0';g.lineWidth=2;g.beginPath();g.moveTo(x+50,y+50);g.lineTo(x+50,y+22);g.moveTo(x+40,y+25);g.lineTo(x+60,y+25);g.stroke();}
if(k===8){for(let a=0;a<3;a++){rect(g,x+18+a*23,y+46,17,32,'#9eae8f');rect(g,x+20+a*23,y+48,13,28,'#647b62');}}
}
for(let x=OFFSET;x<WORLD;x+=STEP)for(let y=OFFSET;y<WORLD;y+=STEP){
for(const side of [-1,1]){rect(g,x+side*72-2,y+122,4,19,'#596858');circle(g,x+side*72,y+119,4,'#d7c789');rect(g,x+side*76-3,y+153,6,8,'#566f53');}
circle(g,x+23,y+128,7,'#354240');g.strokeStyle='#68726a';g.lineWidth=1;g.beginPath();g.arc(x+23,y+128,6,0,TAU);g.stroke();
rect(g,x+90,y-75,44,10,'#43695c');textAt(g,(y<1600?'NORTH':'SOUTH')+' '+(Math.round((x-OFFSET)/STEP)+1),x+112,y-67,6,'#e2e5bd');
if((x+y)%800===400){rect(g,x-76,y+108,12,39,'#3f5a4d');rect(g,x-77,y+109,14,5,'#cbb271');rect(g,x-73,y+120,5,23,'#839b85');}
}
for(const l of [{x:1058,y:1900},{x:2258,y:700}]){rect(g,l.x,l.y,60,110,'#776851');rect(g,l.x+3,l.y+3,54,104,'#768363');g.strokeStyle='#d3cfad';g.lineWidth=1;g.strokeRect(l.x+6,l.y+6,48,98);g.beginPath();g.moveTo(l.x+6,l.y+55);g.lineTo(l.x+54,l.y+55);g.stroke();g.beginPath();g.arc(l.x+30,l.y+55,12,0,TAU);g.stroke();}
for(let n=0;n<12000;n++){let x=rng()*WORLD,y=rng()*WORLD;rect(g,x,y,1+rng()*2,1,rng()>.5?'#eef0c309':'#142b2011');}
}makeMap();
function blocked(x,y,r=9){return x<r||y<r||x>WORLD-r||y>WORLD-r||buildings.some(b=>x>b.x-r&&x<b.x+b.w+r&&y>b.y-r&&y<b.y+b.h+r);}
function carBlocked(c,x,y,a=c.a){const ca=Math.cos(a),sa=Math.sin(a),l=c.type.w/2,w=c.type.h/2;for(const [u,v] of [[-l,-w],[-l,w],[l,-w],[l,w],[0,0]])if(blocked(x+u*ca-v*sa,y+u*sa+v*ca,2))return true;return false;}
function pathPoint(ix,iy,dir){const x=OFFSET+ix*STEP,y=OFFSET+iy*STEP;return {x:x+(dir===1?-LANE:dir===3?LANE:0),y:y+(dir===0?LANE:dir===2?-LANE:0)};}
const dx=[1,0,-1,0],dy=[0,1,0,-1];
function setNext(c,dir){c.dir=dir;c.ix+=dx[dir];c.iy+=dy[dir];c.target=pathPoint(c.ix,c.iy,dir);}
function chooseNext(c){const opts=[c.dir,(c.dir+1)%4,(c.dir+3)%4].filter(d=>c.ix+dx[d]>=0&&c.ix+dx[d]<8&&c.iy+dy[d]>=0&&c.iy+dy[d]<8);if(!opts.length)opts.push((c.dir+2)%4);let dir=opts.includes(c.dir)&&Math.random()<.62?c.dir:opts[Math.floor(Math.random()*opts.length)];if(c.police&&wanted>0){dir=opts.reduce((best,d)=>{const p=pathPoint(c.ix+dx[d],c.iy+dy[d],d),q=pathPoint(c.ix+dx[best],c.iy+dy[best],best);return dist(p,player)<dist(q,player)?d:best;},opts[0]);}setNext(c,dir);}
function spawnCar(i,police=false){let ix=Math.floor(rand(0,7)),iy=Math.floor(rand(0,7)),dir=Math.floor(rand(0,4));if(ix===0&&dir===2)dir=0;if(iy===0&&dir===3)dir=1;let p=pathPoint(ix,iy,dir),t=police?types[6]:types[[0,1,2,3,4,5,7,8][i%8]];let c={...p,a:dir*Math.PI/2,s:0,type:t,color:police?'#e1e3d5':palette[i%palette.length],hp:100,ai:true,police,ix,iy,dir,target:null,stuck:0,hit:0,age:0,parked:false,deadTime:0};setNext(c,dir);let f=rand(.05,.85);c.x+=(c.target.x-c.x)*f;c.y+=(c.target.y-c.y)*f;c.s=rand(65,110);if(!cars.some(o=>dist(o,c)<85)&&dist(c,player)>130)cars.push(c);return c;}
for(let i=0;i<135;i++)spawnCar(i);const starter={x:1660,y:1852,a:0,s:0,type:types[1],color:'#d2b66b',hp:100,ai:false,police:false,hit:0,age:0,parked:true,deadTime:0};cars.push(starter);
function spawnPed(){let p={x:0,y:0,a:rand(0,TAU),color:palette[Math.floor(rand(0,palette.length))],s:rand(18,35),panic:0,hp:40,step:rand(0,6)};for(let i=0;i<100;i++){p.x=rand(100,WORLD-100);p.y=rand(100,WORLD-100);if(!blocked(p.x,p.y,9)&&!onRoad(p.x,p.y)){peds.push(p);return;}}}for(let i=0;i<145;i++)spawnPed();
function save(){best=Math.max(best,cash);try{localStorage.setItem('crimecity-best-v2',String(best));localStorage.setItem('crimecity-cash-v2',String(cash));}catch{}}
function toast(t){$('toast').textContent=t;$('toast').style.opacity='1';toastUntil=clock+3.7;}
function crime(n){wanted=clamp(wanted+n,0,5);lastCrime=clock;}
let audio=null,engine=null,engineGain=null,soundOn=false;
function initAudio(){if(audio)return;try{audio=new(window.AudioContext||window.webkitAudioContext)();engine=audio.createOscillator();engine.type='sawtooth';engineGain=audio.createGain();engineGain.gain.value=0;engine.connect(engineGain);engineGain.connect(audio.destination);engine.start();}catch{}}
function tone(freq,duration=.1,type='square',volume=.03){if(!soundOn||!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(25,freq*.45),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function resetInput(){for(const k in keys)delete keys[k];input.x=input.y=0;input.fire=input.brake=false;input.id=null;$('stick').style.transform='';}
function pause(){if(!started||dead)return;active=!active;resetInput();$('overlay').style.display=active?'none':'flex';$('play').textContent='WRÓĆ NA ULICE →';$('intro').textContent='Gra wstrzymana. Miasto poczeka na Twój powrót.';if(!active&&engineGain)engineGain.gain.value=0;}
function start(){if(dead){player.car=null;player.x=1640;player.y=1873;player.hp=100;wanted=0;arrest=0;invincible=5;dead=false;job=null;for(const c of cars)if(c.police)c.ai=false;toast('Wracasz na ulice. Uważaj na ruch.');}active=true;started=true;frameTime=0;acc=0;$('overlay').style.display='none';resetInput();initAudio();if(audio&&soundOn)audio.resume().catch(()=>{});}
function die(reason){if(dead)return;dead=true;active=false;cash=Math.max(0,cash-150);save();resetInput();$('overlay').style.display='flex';$('intro').textContent=reason+' Koszt powrotu: do $150. Zebrana gotówka i rekord są zapisywane na tym urządzeniu.';$('play').textContent='WRÓĆ DO MIASTA →';if(engineGain)engineGain.gain.value=0;}
function hurt(n){if(invincible>0||dead)return;player.hp=Math.max(0,player.hp-n);invincible=.65;shake=6;if(player.hp<=0)die('Koniec przejażdżki.');}
function nearestCar(){let best=null,d=64;for(const c of cars)if(c.hp>0){const dd=dist(c,player);if(dd<d){best=c;d=dd;}}return best;}
function action(){if(!active)return;if(player.car){const c=player.car;if(Math.abs(c.s)>110){toast('Zwolnij przed wysiadaniem.');return;}for(const side of [1,-1,2]){let a=c.a+Math.PI/2*side,x=c.x+Math.cos(a)*40,y=c.y+Math.sin(a)*40;if(!blocked(x,y,10)&&!cars.some(o=>o!==c&&Math.hypot(o.x-x,o.y-y)<26)){player.x=x;player.y=y;player.car=null;c.s*=.3;invincible=1;toast('Pieszo · mysz celuje, R zmienia broń');return;}}toast('Brak miejsca. Odsuń auto od przeszkody.');return;}let c=nearestCar();if(!c){toast('Podejdź bliżej sprawnego auta.');return;}if(c.ai)crime(c.police?1.2:.55);c.ai=false;c.parked=false;player.car=c;player.x=c.x;player.y=c.y;toast(c.type.name+' · Shift / HAMULEC = ręczny');tone(160,.12,'triangle');}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-75,75),vy:rand(-75,75),life:rand(.2,.6),max:.6,color});if(particles.length>260)particles.splice(0,particles.length-260);}
function damageCar(c,n){if(c.hp<=0)return;c.hp=Math.max(0,c.hp-n);if(c.hp<=0){c.ai=false;c.s=0;c.deadTime=clock;explosions.push({x:c.x,y:c.y,age:0,seed:rand(0,TAU)});if(explosions.length>18)explosions.shift();burst(c.x,c.y,'#ffcb75',42);tone(70,.4,'sawtooth',.06);shake=9;if(player.car===c){player.car=null;for(const a of [c.a+Math.PI/2,c.a-Math.PI/2,c.a+Math.PI]){let x=c.x+Math.cos(a)*48,y=c.y+Math.sin(a)*48;if(!blocked(x,y)){player.x=x;player.y=y;break;}}hurt(38);invincible=2;toast('Auto zniszczone. Znajdź następne.');}}}
function shoot(){if(!active||player.car||fireCooldown>0)return;const w=weapons[weapon];fireCooldown=w.rate;crime(.14);tone(weapon===2?85:180,.075,'sawtooth',.04);for(let i=0;i<w.count;i++){let a=player.a+rand(-w.spread,w.spread);bullets.push({x:player.x+Math.cos(a)*15,y:player.y+Math.sin(a)*15,a,life:w.life,damage:w.damage});}burst(player.x+Math.cos(player.a)*18,player.y+Math.sin(player.a)*18,'#fff1b0',3);for(const p of peds)if(dist(p,player)<230){p.panic=5;p.a=Math.atan2(p.y-player.y,p.x-player.x);}}
function cycle(){weapon=(weapon+1)%3;toast(weapons[weapon].name);}
function takeJob(){if(!active)return;if(job){toast('Dojedź do żółtego celu na minimapie.');return;}if(!player.car){toast('Wsiądź do auta, aby rozpocząć przejazd.');return;}const start=jobs.find(p=>dist(p,player)<100);if(!start){toast('Podjedź do żółtego znaku $ na mapie.');return;}const candidates=jobs.filter(p=>dist(p,start)>500);const target=candidates[Math.floor(rand(0,candidates.length))];job={target,time:90,reward:500};toast('PRZEJAZD · 90 sekund · nagroda $500');tone(600,.2,'triangle');}
$('play').addEventListener('click',start);$('pause').addEventListener('click',pause);$('sound').addEventListener('click',()=>{initAudio();soundOn=!soundOn;$('sound').textContent='DŹW. '+(soundOn?'WŁ.':'WYŁ.');$('sound').setAttribute('aria-pressed',String(soundOn));$('sound').setAttribute('aria-label',soundOn?'Wyłącz dźwięk':'Włącz dźwięk');if(soundOn&&audio)audio.resume().catch(()=>{});});$('night').addEventListener('click',()=>{night=!night;$('night').textContent=night?'DZIEŃ':'NOC';$('night').setAttribute('aria-pressed',String(night));});
$('enter').addEventListener('pointerdown',e=>{e.preventDefault();action();});$('switch').addEventListener('pointerdown',e=>{e.preventDefault();cycle();});$('job').addEventListener('pointerdown',e=>{e.preventDefault();takeJob();});
for(const [id,prop] of [['fire','fire'],['brake','brake']]){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);input[prop]=true;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>input[prop]=false);}
function joyMove(e){const r=$('joy').getBoundingClientRect(),m=r.width*.34;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y);if(l>m){x*=m/l;y*=m/l;}input.x=x/m;input.y=y/m;$('stick').style.transform=`translate(${x}px,${y}px)`;mouseAim=false;}
$('joy').addEventListener('pointerdown',e=>{if(input.id!==null)return;e.preventDefault();input.id=e.pointerId;$('joy').setPointerCapture(e.pointerId);joyMove(e);});$('joy').addEventListener('pointermove',e=>{if(e.pointerId===input.id)joyMove(e);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('joy').addEventListener(ev,e=>{if(e.pointerId===input.id){input.id=null;input.x=input.y=0;$('stick').style.transform='';}});
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'||e.code==='KeyP'){pause();return;}keys[e.code]=true;if(e.code==='KeyE')action();if(e.code==='KeyR')cycle();if(e.code==='KeyF')takeJob();});addEventListener('keyup',e=>{keys[e.code]=false;});addEventListener('blur',()=>{if(active)pause();else resetInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)pause();});
cv.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){input.mouseX=e.clientX;input.mouseY=e.clientY;mouseAim=true;}});cv.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'){cv.setPointerCapture(e.pointerId);input.fire=true;}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])cv.addEventListener(ev,()=>input.fire=false);cv.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
function lightGreen(c){const phase=(clock+((c.ix+c.iy)%3)*2)%14;return c.dir%2===0?phase<6.4:phase>7&&phase<13.4;}
function traffic(c,dt){c.age+=dt;if(c.hp<=0)return;const d=dist(c,c.target);if(d<35){chooseNext(c);c.stuck=0;}let desired=Math.atan2(c.target.y-c.y,c.target.x-c.x),diff=angle(desired-c.a);if(c.police&&wanted>=.5&&dist(c,player)<440){let clear=true;for(let i=1;i<=12;i++)if(blocked(c.x+(player.x-c.x)*i/12,c.y+(player.y-c.y)*i/12,20)){clear=false;break;}if(clear){desired=Math.atan2(player.y-c.y,player.x-c.x);diff=angle(desired-c.a);}}c.a+=clamp(diff,-2.8*dt,2.8*dt);let target=c.police&&wanted>0?175+Math.ceil(wanted)*17:105+(c.type.max-200)*.10;if(Math.abs(diff)>.35)target*=.6;
if(!c.police&&d>57&&d<106&&!lightGreen(c))target=0;
for(const o of cars){if(c===o)continue;let xx=o.x-c.x,yy=o.y-c.y,forward=xx*Math.cos(c.a)+yy*Math.sin(c.a),side=Math.abs(-xx*Math.sin(c.a)+yy*Math.cos(c.a));if(forward>0&&forward<(c.type.w+o.type.w)/2+35+c.s*.25&&side<(c.type.h+o.type.h)/2+3)target=Math.min(target,Math.max(0,o.s-20));}
c.s+=(target-c.s)*Math.min(1,dt*2.5);let nx=c.x+Math.cos(c.a)*c.s*dt,ny=c.y+Math.sin(c.a)*c.s*dt;if(!carBlocked(c,nx,ny)){c.x=nx;c.y=ny;}else{c.s=0;c.stuck+=dt;}
if(c.s<8)c.stuck+=dt;else c.stuck=0;if(c.stuck>12&&dist(c,player)>700){const p=pathPoint(c.ix,c.iy,c.dir);if(!cars.some(o=>o!==c&&dist(o,p)<100)){c.x=p.x;c.y=p.y;c.a=c.dir*Math.PI/2;chooseNext(c);c.stuck=0;}}
}
function overlap(a,b){const axes=[{x:Math.cos(a.a),y:Math.sin(a.a)},{x:-Math.sin(a.a),y:Math.cos(a.a)},{x:Math.cos(b.a),y:Math.sin(b.a)},{x:-Math.sin(b.a),y:Math.cos(b.a)}];let min=Infinity,normal=null;for(const n of axes){let ra=Math.abs(n.x*Math.cos(a.a)+n.y*Math.sin(a.a))*a.type.w/2+Math.abs(-n.x*Math.sin(a.a)+n.y*Math.cos(a.a))*a.type.h/2,rb=Math.abs(n.x*Math.cos(b.a)+n.y*Math.sin(b.a))*b.type.w/2+Math.abs(-n.x*Math.sin(b.a)+n.y*Math.cos(b.a))*b.type.h/2,delta=(a.x-b.x)*n.x+(a.y-b.y)*n.y,o=ra+rb-Math.abs(delta);if(o<=0)return null;if(o<min){min=o;normal={x:n.x*(delta>=0?1:-1),y:n.y*(delta>=0?1:-1)};}}return {n:normal,d:min};}
function carCollisions(){const buckets=new Map();for(const c of cars){let k=Math.floor(c.x/100)+','+Math.floor(c.y/100);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(c);}const checked=new Set();for(let i=0;i<cars.length;i++){const a=cars[i],gx=Math.floor(a.x/100),gy=Math.floor(a.y/100);for(let xx=-1;xx<=1;xx++)for(let yy=-1;yy<=1;yy++)for(const b of buckets.get((gx+xx)+','+(gy+yy))||[]){if(a===b)continue;const j=cars.indexOf(b),key=Math.min(i,j)+':'+Math.max(i,j);if(checked.has(key))continue;checked.add(key);if(dist(a,b)>(a.type.w+b.type.w)/2)continue;const hit=overlap(a,b);if(!hit)continue;const move=hit.d*.51;if(!carBlocked(a,a.x+hit.n.x*move,a.y+hit.n.y*move)){a.x+=hit.n.x*move;a.y+=hit.n.y*move;}if(!carBlocked(b,b.x-hit.n.x*move,b.y-hit.n.y*move)){b.x-=hit.n.x*move;b.y-=hit.n.y*move;}let impact=Math.abs((Math.cos(a.a)*a.s-Math.cos(b.a)*b.s)*hit.n.x+(Math.sin(a.a)*a.s-Math.sin(b.a)*b.s)*hit.n.y);if(impact>32&&clock>a.hit&&clock>b.hit){a.hit=b.hit=clock+.45;damageCar(a,impact*.065);damageCar(b,impact*.065);burst((a.x+b.x)/2,(a.y+b.y)/2,'#e9c27b',7);if(a===player.car||b===player.car){crime(.12);shake=Math.min(10,impact/24);tone(80,.12,'sawtooth');}}a.s*=.65;b.s*=.65;}}}
function update(dt){clock+=dt;invincible=Math.max(0,invincible-dt);fireCooldown=Math.max(0,fireCooldown-dt);shake*=.9;if(clock>toastUntil)$('toast').style.opacity='0';
let ax=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),ay=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0),braking=keys.ShiftLeft||keys.ShiftRight||input.brake;
if(player.car){const c=player.car;let gas=-ay,steer=ax;if(Math.hypot(input.x,input.y)>.12){const desired=Math.atan2(input.y,input.x),dif=angle(desired-c.a);steer=clamp(dif*1.6,-1,1);gas=Math.max(.3,Math.hypot(input.x,input.y));}else if(input.fire)gas=1;let speed=Math.abs(c.s),turn=steer*c.type.grip*clamp(speed/110,0,1)*(c.s<0?-1:1)*dt;let na=c.a+turn*(braking?1.5:1);if(!carBlocked(c,c.x,c.y,na))c.a=na;c.s+=gas*c.type.acc*dt;c.s*=Math.exp(-(braking?5:gas? .23:1.2)*dt);c.s=clamp(c.s,-95,c.type.max*(c.hp<25?.65:1));let nx=c.x+Math.cos(c.a)*c.s*dt,ny=c.y+Math.sin(c.a)*c.s*dt;if(!carBlocked(c,nx,ny)){c.x=nx;c.y=ny;distance+=Math.abs(c.s)*dt;}else{if(speed>35&&clock>c.hit){damageCar(c,speed*.07);c.hit=clock+.45;shake=speed/30;burst(c.x+Math.cos(c.a)*c.type.w/2,c.y+Math.sin(c.a)*c.type.w/2,'#e8bd72');tone(75,.12,'sawtooth');}c.s*=-.24;}if(speed>90&&(braking||Math.abs(steer)>.6)&&Math.random()<.5){skids.push({x:c.x,y:c.y,a:c.a,t:clock,w:c.type.h});if(skids.length>220)skids.shift();}if(player.car){player.x=c.x;player.y=c.y;player.a=c.a;}}
else{ax+=input.x;ay+=input.y;const length=Math.hypot(ax,ay),speed=braking?175:115;if(length>.1){ax/=Math.max(1,length);ay/=Math.max(1,length);if(!mouseAim)player.a=Math.atan2(ay,ax);let nx=player.x+ax*speed*dt,ny=player.y+ay*speed*dt;if(!blocked(nx,player.y))player.x=nx;if(!blocked(player.x,ny))player.y=ny;}if(mouseAim)player.a=Math.atan2((input.mouseY-H/2)/zoom+camera.y-player.y,(input.mouseX-W/2)/zoom+camera.x-player.x);if(input.fire||keys.Space)shoot();}
for(const c of cars)if(c.ai)traffic(c,dt);else if(c!==player.car&&c.hp>0&&Math.abs(c.s)>1){let nx=c.x+Math.cos(c.a)*c.s*dt,ny=c.y+Math.sin(c.a)*c.s*dt;if(!carBlocked(c,nx,ny)){c.x=nx;c.y=ny;}c.s*=Math.exp(-3*dt);}carCollisions();if(player.car){player.x=player.car.x;player.y=player.car.y;}
for(let i=peds.length-1;i>=0;i--){const p=peds[i];p.panic=Math.max(0,p.panic-dt);p.step+=dt*(p.panic?12:5);if(Math.random()<dt*.5)p.a+=rand(-1,1);let nx=p.x+Math.cos(p.a)*p.s*(p.panic?3:1)*dt,ny=p.y+Math.sin(p.a)*p.s*(p.panic?3:1)*dt;if(!blocked(nx,ny,7)&&(!onRoad(nx,ny)||p.panic)){p.x=nx;p.y=ny;}else p.a+=2;for(const c of cars){if(dist(p,c)<c.type.w/2+8&&Math.abs(c.s)>60){p.hp=0;if(c===player.car)crime(.4);break;}}if(p.hp<=0){bodies.push({x:p.x,y:p.y,a:p.a,color:p.color});if(bodies.length>120)bodies.shift();peds.splice(i,1);}}
if(!player.car)for(const c of cars)if(dist(c,player)<c.type.w/2+8&&Math.abs(c.s)>45){hurt(Math.abs(c.s)*.09);let a=Math.atan2(player.y-c.y,player.x-c.x),x=player.x+Math.cos(a)*16,y=player.y+Math.sin(a)*16;if(!blocked(x,y)){player.x=x;player.y=y;}}
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];let hit=false;for(let step=0;step<3&&!hit;step++){b.x+=Math.cos(b.a)*670*dt/3;b.y+=Math.sin(b.a)*670*dt/3;if(blocked(b.x,b.y,1)){hit=true;burst(b.x,b.y,'#b9b5a0',3);break;}for(const c of cars){const xx=b.x-c.x,yy=b.y-c.y,ca=Math.cos(c.a),sa=Math.sin(c.a);if(Math.abs(xx*ca+yy*sa)<c.type.w/2&&Math.abs(-xx*sa+yy*ca)<c.type.h/2){damageCar(c,b.damage);hit=true;burst(b.x,b.y,'#e5c684',4);break;}}if(!hit)for(const p of peds)if(dist(p,b)<9){p.hp-=b.damage;crime(.2);hit=true;break;}}b.life-=dt;if(hit||b.life<=0)bullets.splice(i,1);}
let cops=cars.filter(c=>c.police&&c.ai&&c.hp>0);if(wanted>=.5&&cops.length<Math.ceil(wanted)+1&&Math.random()<dt*.6){let c=spawnCar(cars.length,true);if(cars.includes(c)&&dist(c,player)>1700){cars.splice(cars.indexOf(c),1);}}
let visiblePolice=cops.some(c=>dist(c,player)<430);if(wanted>0&&clock-lastCrime>10&&!visiblePolice){wanted=Math.max(0,wanted-dt*.11);if(wanted===0){cash+=100;save();toast('POŚCIG ZGUBIONY · +$100');}}
let cornered=cops.some(c=>dist(c,player)<65);if(cornered&&player.car&&Math.abs(player.car.s)<35){arrest+=dt;if(arrest>=4)die('Policja Cię zatrzymała.');}else arrest=Math.max(0,arrest-dt*2);if(cornered&&!player.car)hurt(9);
for(const g of garages)if(player.car&&dist(g,player)<64&&Math.abs(player.car.s)<22&&player.car.hp<99){player.car.hp=100;player.hp=100;toast('Warsztat · auto i zdrowie przywrócone');tone(450,.2,'triangle');}
if(job){job.time-=dt;if(job.time<=0){job=null;toast('Czas minął. Następny przejazd czeka przy $.');}else if(player.car&&dist(player,job.target)<65){cash+=job.reward;save();toast('PRZEJAZD ZAKOŃCZONY · +$'+job.reward);job=null;jobReady=clock+5;tone(700,.3,'triangle');}}else if(player.car&&clock>jobReady&&jobs.some(p=>dist(p,player)<70)&&Math.abs(player.car.s)<25){toast('Przejazd za $500 · naciśnij F / ZLECENIE');jobReady=clock+5;}
for(let i=explosions.length-1;i>=0;i--){explosions[i].age+=dt;if(explosions[i].age>3.2)explosions.splice(i,1);}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.life<=0)particles.splice(i,1);}if(peds.length<135&&Math.random()<dt*2)spawnPed();for(let i=cars.length-1;i>=0;i--)if(cars[i].hp<=0&&clock-cars[i].deadTime>20&&dist(cars[i],player)>650){cars.splice(i,1);spawnCar(i);}
if(engineGain){engineGain.gain.setTargetAtTime(soundOn&&player.car ? .018 : 0,audio.currentTime,.08);engine.frequency.setTargetAtTime(player.car?45+Math.abs(player.car.s)*.6:40,audio.currentTime,.08);if(soundOn&&visiblePolice&&Math.floor(clock*3)!==Math.floor((clock-dt)*3))tone(Math.floor(clock*3)%2?650:850,.25,'sine',.016);}
uiTimer+=dt;if(uiTimer>.1){uiTimer=0;hud();}}
function hud(){const c=player.car;$('mission').classList.toggle('job-active',!!job);$('switch').textContent=weapons[weapon].name;$('health').textContent=Math.ceil(player.hp);$('healthbar').style.width=player.hp+'%';$('healthbar').style.background=player.hp<30?'#ed8b70':'#cdeb8b';$('wanted').textContent='★ '.repeat(Math.ceil(wanted))+'☆ '.repeat(5-Math.ceil(wanted));$('money').textContent='$ '+String(cash).padStart(6,'0');$('speed').innerHTML=(c?Math.round(Math.abs(c.s)*.48):0)+' <small>KM/H</small>';$('enter').textContent=arrest>.2?'ZATRZYMANIE '+Math.min(100,Math.round(arrest*25))+'%':c?'WYJDŹ Z AUTA':'WEJDŹ DO AUTA';$('fire').textContent=c?'GAZ':'STRZAŁ';$('brake').textContent=c?'HAMULEC':'BIEG';$('district').textContent=player.x<1600?(player.y<1600?'GARDEN DISTRICT':'OLD TOWN'):(player.y<1600?'DOWNTOWN':'INDUSTRIAL');if(job)$('mission').innerHTML='<b>PRZEJAZD / $500</b>'+Math.ceil(job.time)+' s · '+Math.round(dist(player,job.target))+' m do celu<br>Jedź do żółtego okręgu.';else $('mission').innerHTML='<b>SWOBODNA JAZDA</b>Zielone G — darmowy warsztat.<br>Żółte $ — przejazd za $500.<br>'+ (wanted>0?'Zniknij policji z pola widzenia.':'F / ZLECENIE rozpoczyna przejazd.');}
function visible(p,r=80){return Math.abs(p.x-camera.x)<W/(2*zoom)+r&&Math.abs(p.y-camera.y)<H/(2*zoom)+r;}
function drawCar(c){const g=ctx,t=c.type;g.save();g.translate(c.x,c.y);g.rotate(c.a);rect(g,-t.w/2+4,-t.h/2+5,t.w,t.h,'#0b171960');rect(g,-t.w*.36,-t.h/2-3,t.w*.2,t.h+6,'#1a2120');rect(g,t.w*.2,-t.h/2-3,t.w*.2,t.h+6,'#1a2120');rect(g,-t.w/2,-t.h/2,t.w,t.h,c.hp<=0?'#333c38':c.color);rect(g,-t.w/2+3,-t.h/2+2,t.w-7,2,'#fff4');rect(g,-t.w*.15,-t.h*.40,t.w*.37,t.h*.80,'#29434b');rect(g,-t.w*.06,-t.h*.40,t.w*.17,t.h*.80,c.hp<=0?'#464a43':c.color);rect(g,-t.w*.36,-t.h*.34,t.w*.15,t.h*.68,'#344a4e');if(t===types[4]){rect(g,-t.w*.44,-t.h*.45,t.w*.58,t.h*.9,'#a7a89b');for(let x=-t.w*.4;x<t.w*.1;x+=7)rect(g,x,-t.h*.4,1,t.h*.8,'#777d73');}if(t===types[7]){for(let x=-28;x<28;x+=10){rect(g,x,-t.h/2,7,3,'#263e43');rect(g,x,t.h/2-3,7,3,'#263e43');}}if(t===types[3])rect(g,-4,-4,8,8,'#edce63');if(t===types[8]){rect(g,-7,-2,12,4,'#d4634b');rect(g,-3,-6,4,12,'#d4634b');}if(c.police){rect(g,-12,-t.h/2,10,t.h,'#253b47');rect(g,-3,-8,5,8,Math.sin(clock*12)>0?'#f57863':'#8d4946');rect(g,-3,0,5,8,Math.sin(clock*12)<0?'#85bdf1':'#48618b');}rect(g,t.w/2-2,-t.h/2+3,3,4,'#f1e7bd');rect(g,t.w/2-2,t.h/2-7,3,4,'#f1e7bd');rect(g,-t.w/2,-t.h/2+3,2,4,'#c4543c');rect(g,-t.w/2,t.h/2-7,2,4,'#c4543c');if(c.hp<30){circle(g,-t.w*.25,0,8+Math.sin(clock*5)*3,'#262b2780');}g.restore();}
// Bodies remain below live actors; bounded count protects long mobile sessions.
function drawBody(b){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.a);circle(ctx,1,3,12,'#13231c50');rect(ctx,-12,-5,12,4,'#29332d');rect(ctx,-12,2,12,4,'#29332d');rect(ctx,-2,-6,12,12,b.color);rect(ctx,0,-10,4,6,b.color);rect(ctx,4,5,4,6,b.color);circle(ctx,13,0,4,'#c3aa8b');ctx.restore();}
function drawExplosion(e){const t=e.age;ctx.save();ctx.translate(e.x,e.y);
if(t<.85){const k=t/.85,r=12+70*Math.sin(k*Math.PI/2);ctx.globalAlpha=(1-k)*.8;circle(ctx,0,0,r*1.3,'#f5b552');ctx.strokeStyle='#ffe7a2';ctx.lineWidth=3*(1-k);ctx.beginPath();ctx.arc(0,0,15+k*112,0,TAU);ctx.stroke();for(let i=0;i<7;i++){const a=e.seed+i*TAU/7;circle(ctx,Math.cos(a)*r*.38,Math.sin(a)*r*.38,r*.47,i%2?'#ff973f':'#ffd57a');}circle(ctx,0,0,r*.33,'#fff4c4');}
if(t>.18){const k=(t-.18)/3.02;ctx.globalAlpha=Math.min(1,k*6)*(1-k)*.7;for(let i=0;i<5;i++){const a=e.seed+i*TAU/5;circle(ctx,Math.cos(a)*(12+k*25)+k*22,Math.sin(a)*14-k*45,13+k*26,i%2?'#333b36':'#586059');}}
ctx.restore();}
function drawPed(p,hero=false){const g=ctx;g.save();g.translate(p.x,p.y);g.rotate(p.a);circle(g,3,4,hero?9:7,'#15241966');let step=hero?Math.sin(clock*12)*2:Math.sin(p.step)*2;rect(g,-5+step,-5,8,3,'#263633');rect(g,-5-step,2,8,3,'#263633');rect(g,-4,-6,9,12,hero?'#d7e39a':p.color);circle(g,1,0,4,hero?'#e3c79e':'#c3aa8b');if(hero){rect(g,5,3,13,3,'#252f2d');if(invincible>0){g.strokeStyle='#e0f9b0';g.lineWidth=1;g.beginPath();g.arc(0,0,14,0,TAU);g.stroke();}}g.restore();}
function marker(p,label,color){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,32+Math.sin(clock*3)*3,0,TAU);ctx.stroke();circle(ctx,p.x,p.y,13,'#122b20dc');textAt(ctx,label,p.x,p.y+5,15,color);}
function draw(){ctx.setTransform(D,0,0,D,0,0);rect(ctx,0,0,W,H,'#263d33');const targetX=clamp(player.x,Math.min(WORLD/2,W/(2*zoom)),Math.max(WORLD/2,WORLD-W/(2*zoom))),targetY=clamp(player.y,Math.min(WORLD/2,H/(2*zoom)),Math.max(WORLD/2,WORLD-H/(2*zoom)));camera.x+=(targetX-camera.x)*.12;camera.y+=(targetY-camera.y)*.12;ctx.save();ctx.translate(W/2+(active?rand(-shake,shake):0),H/2+(active?rand(-shake,shake):0));ctx.scale(zoom,zoom);ctx.translate(-camera.x,-camera.y);const sx=clamp(camera.x-W/zoom/2-20,0,WORLD),sy=clamp(camera.y-H/zoom/2-20,0,WORLD),sw=Math.min(WORLD-sx,W/zoom+40),sh=Math.min(WORLD-sy,H/zoom+40);ctx.drawImage(mapCanvas,sx,sy,sw,sh,sx,sy,sw,sh);
for(const s of skids)if(visible(s)){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);rect(ctx,-7,-s.w/2,14,2,'#202a2380');rect(ctx,-7,s.w/2,14,2,'#202a2380');ctx.restore();}
for(let ix=0;ix<8;ix++)for(let iy=0;iy<8;iy++){const p={x:OFFSET+ix*STEP,y:OFFSET+iy*STEP};if(!visible(p))continue;const phase=(clock+((ix+iy)%3)*2)%14;circle(ctx,p.x-65,p.y-63,4,phase<6.4?'#b8d37c':'#d87a64');circle(ctx,p.x+65,p.y+63,4,phase>7&&phase<13.4?'#b8d37c':'#d87a64');}
for(const g of garages)if(visible(g))marker(g,'G','#ceec92');for(const j of jobs)if(visible(j))marker(j,'$','#f1c870');if(job&&visible(job.target))marker(job.target,'↓','#fff1a9');
for(const b of bodies)if(visible(b))drawBody(b);for(const p of peds)if(visible(p))drawPed(p);for(const c of cars)if(visible(c))drawCar(c);if(!player.car)drawPed(player,true);
if(!player.car&&active){const c=nearestCar();if(c&&visible(c)){ctx.strokeStyle='#d7ec99';ctx.lineWidth=1;ctx.beginPath();ctx.arc(c.x,c.y,36,0,TAU);ctx.stroke();textAt(ctx,mobile?'AUTO':'[ E ]',c.x,c.y-42,10,'#ecf4c6');}}
for(const b of bullets){ctx.strokeStyle='#ffeba6';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-Math.cos(b.a)*11,b.y-Math.sin(b.a)*11);ctx.stroke();}for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);rect(ctx,p.x,p.y,3,3,p.color);}ctx.globalAlpha=1;for(const e of explosions)if(visible(e,160))drawExplosion(e);ctx.restore();
if(night){rect(ctx,0,0,W,H,'#06112088');ctx.save();ctx.translate(W/2,H/2);ctx.scale(zoom,zoom);ctx.translate(-camera.x,-camera.y);ctx.globalCompositeOperation='screen';for(const c of cars)if(visible(c)&&c.hp>0){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.a);let grad=ctx.createLinearGradient(15,0,160,0);grad.addColorStop(0,'#f5e7a340');grad.addColorStop(1,'#f5e7a300');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(15,-9);ctx.lineTo(160,-48);ctx.lineTo(160,48);ctx.lineTo(15,9);ctx.fill();ctx.restore();}ctx.restore();}drawMap();}
function drawMap(){const g=mc,s=180/WORLD;rect(g,0,0,180,180,'#263b32');g.strokeStyle='#6e7a69';g.lineWidth=2.5;for(let x=OFFSET;x<WORLD;x+=STEP){g.beginPath();g.moveTo(x*s,0);g.lineTo(x*s,180);g.stroke();g.beginPath();g.moveTo(0,x*s);g.lineTo(180,x*s);g.stroke();}for(const p of garages)circle(g,p.x*s,p.y*s,3,'#c7e68c');for(const p of jobs)circle(g,p.x*s,p.y*s,2.7,'#efc873');if(job){g.strokeStyle='#f5d782';g.lineWidth=1;g.setLineDash([3,3]);g.beginPath();g.moveTo(player.x*s,player.y*s);g.lineTo(job.target.x*s,job.target.y*s);g.stroke();g.setLineDash([]);g.beginPath();g.arc(job.target.x*s,job.target.y*s,6,0,TAU);g.stroke();}for(const c of cars)if(c.police&&c.ai&&wanted>0)circle(g,c.x*s,c.y*s,2.2,'#e98370');g.save();g.translate(player.x*s,player.y*s);g.rotate(player.a);g.fillStyle='#f1f8d8';g.beginPath();g.moveTo(6,0);g.lineTo(-4,-4);g.lineTo(-2,0);g.lineTo(-4,4);g.closePath();g.fill();g.restore();}
function frame(t){if(!frameTime)frameTime=t;let delta=Math.min((t-frameTime)/1000,.1);frameTime=t;if(active){acc+=delta;while(acc+1e-9>=1/60){update(1/60);acc-=1/60;if(!active){acc=0;break;}}}else acc=0;draw();requestAnimationFrame(frame);}
addEventListener('error',e=>{$('error').style.display='block';$('error').textContent='Błąd gry: '+e.message;});hud();requestAnimationFrame(frame);
})();
