'use strict';
(() => {
const $=id=>document.getElementById(id),cv=$('game'),ctx=cv.getContext('2d',{alpha:false}),mc=$('map').getContext('2d');
const TAU=Math.PI*2, WORLD=9000;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),angle=a=>Math.atan2(Math.sin(a),Math.cos(a));
let seed=7719;function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
let W=innerWidth,H=innerHeight,D=1,zoom=1,clock=0,active=false,started=false,dead=false,night=false,frameTime=0,acc=0,uiTimer=0;
let cash=0,best=0,distance=0,wanted=0,lastCrime=-100,invincible=0,job=null,jobReady=0,toastUntil=0,shake=0,fireCooldown=0,mouseAim=false;
try{best=Number(localStorage.getItem('crimecity-best-v2'))||0;cash=Number(localStorage.getItem('crimecity-cash-v2'))||0;}catch{}
const mobile=matchMedia('(pointer:coarse)').matches||W<760||new URLSearchParams(location.search).get('controls')==='touch';document.body.classList.toggle('mobile',mobile);
if(mobile)$('help').textContent='Joystick — ruch i kierunek jazdy. W aucie wychyl joystick, aby jechać. STRZAŁ celuje w kierunku ruchu; GAZ pozwala jechać prosto. HAMULEC zatrzymuje auto.';
$('record').textContent='ŚRÓDMIEŚCIE / 4.0'+(best?' · REKORD zł '+best:'');
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,1.5);cv.width=Math.round(W*D);cv.height=Math.round(H*D);zoom=mobile?(H<W?1.6:1.45):1.65;}resize();addEventListener('resize',resize);
const player={x:3123,y:4740,a:0,hp:100,car:null};let camera={x:player.x,y:player.y};
const keys={},input={x:0,y:0,fire:false,brake:false,id:null,mouseX:0,mouseY:0};
const buildings=[],trees=[],cars=[],peds=[],bullets=[],particles=[],explosions=[],bodies=[],skids=[],pickups=[];
const garages=[];const jobs=[];
const palette=['#c95b42','#7e9fb3','#dcbf66','#6a9479','#d3d5c7','#515563','#ae7379','#e69554','#689b98'];
const types=[{name:'MONARCH',w:43,h:21,max:300,acc:175,grip:3.1},{name:'STINGER GT',w:44,h:20,max:420,acc:250,grip:3.6},{name:'BOXER VAN',w:49,h:25,max:235,acc:135,grip:2.6},{name:'CITY TAXI',w:44,h:22,max:310,acc:185,grip:3},{name:'HAULER',w:66,h:27,max:210,acc:100,grip:2.1},{name:'MINI',w:35,h:19,max:290,acc:205,grip:3.5},{name:'INTERCEPTOR',w:46,h:22,max:365,acc:220,grip:3.4},{name:'CITY BUS',w:79,h:27,max:195,acc:95,grip:2},{name:'AMBULANS',w:51,h:25,max:290,acc:170,grip:2.6}];
const weapons=[{name:'PISTOLET',rate:.25,count:1,spread:.025,damage:23,life:.65},{name:'SMG',rate:.085,count:1,spread:.075,damage:12,life:.60},{name:'STRZELBA',rate:.66,count:6,spread:.25,damage:14,life:.34}];let weapon=0,arrest=0;
function rect(g,x,y,w,h,c){g.fillStyle=c;g.fillRect(x,y,w,h);}function circle(g,x,y,r,c){g.fillStyle=c;g.beginPath();g.arc(x,y,r,0,TAU);g.fill();}
function textAt(g,t,x,y,size,color){g.fillStyle=color;g.font=`bold ${size}px Arial`;g.textAlign='center';g.fillText(t,x,y);}
const geo=(lon,lat)=>({x:(lon-20.965)*68000,y:(52.275-lat)*111200});
const MAP=window.WARSAW_MAP;
if(!MAP)throw Error('Nie udało się wczytać mapy Śródmieścia. Odśwież stronę.');
function boxOf(points){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return {x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)};}
function inPoly(x,y,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function segProject(x,y,a,b){const vx=b.x-a.x,vy=b.y-a.y,l=vx*vx+vy*vy,t=l?clamp(((x-a.x)*vx+(y-a.y)*vy)/l,0,1):0;const px=a.x+vx*t,py=a.y+vy*t;return {x:px,y:py,t,d:Math.hypot(x-px,y-py)};}
class SpatialIndex{constructor(size=120){this.size=size;this.cells=new Map();}insert(o,b){for(let x=Math.floor(b.x/this.size);x<=Math.floor((b.x+b.w)/this.size);x++)for(let y=Math.floor(b.y/this.size);y<=Math.floor((b.y+b.h)/this.size);y++){const k=x+','+y;if(!this.cells.has(k))this.cells.set(k,[]);this.cells.get(k).push(o);}}near(x,y,r=0){const out=new Set();for(let xx=Math.floor((x-r)/this.size);xx<=Math.floor((x+r)/this.size);xx++)for(let yy=Math.floor((y-r)/this.size);yy<=Math.floor((y+r)/this.size);yy++)for(const o of this.cells.get(xx+','+yy)||[])out.add(o);return out;}}
const roadIndex=new SpatialIndex(),buildingIndex=new SpatialIndex(),waterIndex=new SpatialIndex(),segments=[],graph=new Map();
const roads=MAP.roads;
for(const r of roads){for(let i=1;i<r.points.length;i++){const a={x:r.points[i-1][0],y:r.points[i-1][1]},b={x:r.points[i][0],y:r.points[i][1]},length=dist(a,b);if(length<.01)continue;const s={a,b,length,road:r,from:r.nodes[i-1],to:r.nodes[i],id:segments.length};segments.push(s);const pad=r.width/2+12;roadIndex.insert(s,{x:Math.min(a.x,b.x)-pad,y:Math.min(a.y,b.y)-pad,w:Math.abs(a.x-b.x)+pad*2,h:Math.abs(a.y-b.y)+pad*2});
if(!r.foot){for(const [id,p]of [[s.from,a],[s.to,b]])if(!graph.has(id))graph.set(id,{...p,id,edges:[]});graph.get(s.from).edges.push({segment:s,reverse:false,to:s.to});if(!r.one)graph.get(s.to).edges.push({segment:s,reverse:true,to:s.from});}}
}
// Largest connected drivable component excludes isolated service yards and incomplete edge stubs.
const neighbors=new Map();for(const s of segments)if(!s.road.foot){for(const [a,b] of [[s.from,s.to],[s.to,s.from]]){if(!neighbors.has(a))neighbors.set(a,[]);neighbors.get(a).push(b);}}
let mainNodes=new Set(),visited=new Set();for(const id of graph.keys()){if(visited.has(id))continue;const ids=new Set([id]),q=[id];visited.add(id);while(q.length){const n=q.pop();for(const next of neighbors.get(n)||[])if(!visited.has(next)){visited.add(next);ids.add(next);q.push(next);}}if(ids.size>mainNodes.size)mainNodes=ids;}
const driveSegments=segments.filter(s=>!s.road.foot&&mainNodes.has(s.from));
for(const b of MAP.buildings){Object.assign(b,boxOf(b.points));buildings.push(b);buildingIndex.insert(b,b);}
for(const p of MAP.water){Object.assign(p,boxOf(p.points));waterIndex.insert(p,p);}
function nearStreet(x,y,r=0,bridgeOnly=false){for(const s of roadIndex.near(x,y,r))if((!bridgeOnly||s.road.bridge)&&segProject(x,y,s.a,s.b).d<s.road.width/2-r)return s;return null;}
function onRoad(x,y){return !!nearStreet(x,y);}
function water(x,y,r=0){if(nearStreet(x,y,r,true))return false;for(const p of waterIndex.near(x,y,r)){if(inPoly(x,y,p.points))return true;if(r>0)for(let i=1;i<p.points.length;i++)if(segProject(x,y,{x:p.points[i-1][0],y:p.points[i-1][1]},{x:p.points[i][0],y:p.points[i][1]}).d<r)return true;}return false;}
function blocked(x,y,r=9){if(x<r||y<r||x>WORLD-r||y>WORLD-r||water(x,y,r))return true;if(nearStreet(x,y,r-3))return false;for(const b of buildingIndex.near(x,y,r)){if(x<b.x-r||x>b.x+b.w+r||y<b.y-r||y>b.y+b.h+r)continue;if(inPoly(x,y,b.points))return true;for(let i=1;i<b.points.length;i++)if(segProject(x,y,{x:b.points[i-1][0],y:b.points[i-1][1]},{x:b.points[i][0],y:b.points[i][1]}).d<r)return true;}return false;}
const landmarks=[
[21.0069,52.2318,'PAŁAC KULTURY','palace'],[21.0033,52.2287,'WARSZAWA CENTRALNA','station'],[21.0122,52.2497,'RYNEK STAREGO MIASTA','oldtown'],[21.0148,52.2479,'ZAMEK KRÓLEWSKI','castle'],[21.0287,52.2419,'CENTRUM NAUKI KOPERNIK','science'],[21.0076,52.2413,'OGRÓD SASKI','park'],[21.0062,52.2512,'OGRÓD KRASIŃSKICH','park'],[21.0356,52.2152,'ŁAZIENKI KRÓLEWSKIE','garden'],[21.0228,52.2283,'PLAC TRZECH KRZYŻY','square'],[21.0172,52.2198,'PLAC ZBAWICIELA','square'],[21.0159,52.2229,'PLAC KONSTYTUCJI','square'],[21.0170,52.2456,'KRAKOWSKIE PRZEDMIEŚCIE','street'],[21.0215,52.2317,'RONDO DE GAULLE’A','square'],[21.0116,52.2293,'RONDO DMOWSKIEGO','square'],[21.0120,52.2394,'ZACHĘTA','museum'],[21.0104,52.2431,'TEATR WIELKI','theatre'],[21.0235,52.2300,'MUZEUM NARODOWE','museum']
].map(([lon,lat,name,kind])=>({...geo(lon,lat),name,kind}));
// District staging envelope follows its major boundary streets; not an administrative survey.
const stageOutline=[[20.991,52.263],[21.007,52.261],[21.016,52.258],[21.027,52.246],[21.043,52.227],[21.058,52.212],[21.049,52.207],[21.033,52.207],[21.023,52.209],[21.011,52.213],[21.001,52.216],[20.997,52.229],[20.986,52.250],[20.991,52.263]].map(([x,y])=>{const p=geo(x,y);return [p.x,p.y];});
function district(p){if(inPoly(p.x,p.y,stageOutline)){const lat=52.275-p.y/111200,lon=20.965+p.x/68000;if(lat>52.247&&lon>21.008)return 'STARE / NOWE MIASTO';if(lat>52.246)return 'MURANÓW';if(lon>21.026&&lat>52.227)return 'POWIŚLE';if(lat<52.221)return 'UJAZDÓW';return 'ŚRÓDMIEŚCIE';}return 'KOLEJNY ETAP';}
const bridges=roads.filter(r=>r.bridge&&r.name).filter((r,i,a)=>a.findIndex(v=>v.name===r.name)===i).map(r=>({name:r.name,...{x:r.points[0][0],y:r.points[0][1]}}));
function polygon(g,pts,fill,stroke=null,width=1){g.beginPath();pts.forEach((p,i)=>i?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1]));g.closePath();if(fill){g.fillStyle=fill;g.fill();}if(stroke){g.strokeStyle=stroke;g.lineWidth=width;g.stroke();}}
function line(g,pts,color,width,dash=[]){g.beginPath();pts.forEach((p,i)=>i?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1]));g.strokeStyle=color;g.lineWidth=width;g.setLineDash(dash);g.stroke();g.setLineDash([]);}
const mapCanvas=document.createElement('canvas');mapCanvas.width=3000;mapCanvas.height=3000;const mapCtx=mapCanvas.getContext('2d',{alpha:false}),CACHE_SCALE=mapCanvas.width/WORLD;
function paintBuilding(g,b){const old=b.y<3300&&b.x>2800,colors=old?['#9e604c','#b7805e','#87584b']:['#717b79','#7b827d','#7c827e','#697879'];g.save();g.translate(4,7);polygon(g,b.points,'#152c2948');g.restore();polygon(g,b.points,colors[b.id%colors.length],'#c6c5af',1.6);if(b.w>20&&b.h>20){const x=b.x+b.w*.5,y=b.y+b.h*.5;if(inPoly(x,y,b.points)){rect(g,x-3,y-3,6,6,'#b3bbae');rect(g,x-2,y-2,4,2,'#526661');}}}
function makeMap(){const g=mapCtx;g.scale(CACHE_SCALE,CACHE_SCALE);rect(g,0,0,WORLD,WORLD,'#718276');polygon(g,stageOutline,'#a3a692');for(const p of MAP.parks)polygon(g,p.points,'#52774f','#759063',3);for(const p of MAP.water)polygon(g,p.points,'#3b7884','#aac3b2',7);
for(const b of buildings)paintBuilding(g,b);
g.lineCap='round';g.lineJoin='round';for(const r of roads)line(g,r.points,r.bridge?'#c9c7b4':'#c0bdac',r.width+10);for(const r of roads)line(g,r.points,r.foot?'#b9ac92':r.tunnel?'#555e5d':'#424e52',r.width);for(const r of roads)if(!r.foot&&!r.one&&r.width>=30)line(g,r.points,'#c9bd9660',1,[9,11]);
// Deterministic trees stay inside park footprints and clear paths/buildings.
for(const p of MAP.parks){const b=boxOf(p.points);for(let i=0;i<Math.min(500,b.w*b.h/500);i++){const x=b.x+rng()*b.w,y=b.y+rng()*b.h;if(!inPoly(x,y,p.points)||blocked(x,y,10)||onRoad(x,y))continue;circle(g,x+3,y+4,7,'#29463255');circle(g,x,y,7,'#345d40');circle(g,x-2,y-2,4,'#668d50');}}
// Labels follow their streets rather than a repeated square grid.
const named=new Map();for(const r of roads)if(r.name){const len=r.points.slice(1).reduce((v,p,i)=>v+Math.hypot(p[0]-r.points[i][0],p[1]-r.points[i][1]),0);if(!named.has(r.name)||named.get(r.name).len<len)named.set(r.name,{r,len});}for(const {r,len} of named.values()){if(len<90)continue;const i=Math.floor(r.points.length/2),a=r.points[Math.max(0,i-1)],b=r.points[i];let ang=Math.atan2(b[1]-a[1],b[0]-a[0]);if(ang>Math.PI/2||ang<-Math.PI/2)ang+=Math.PI;g.save();g.translate(b[0],b[1]);g.rotate(ang);textAt(g,r.name.toUpperCase(),0,-r.width/2-7,11,'#f0e9cf');g.restore();}
for(const l of landmarks){circle(g,l.x,l.y,5,'#d3b47c');textAt(g,l.name,l.x,l.y-18,14,'#f0e1b5');if(l.kind==='palace'){rect(g,l.x-14,l.y-20,28,40,'#ddc99c');rect(g,l.x-6,l.y-12,12,24,'#f0deb3');line(g,[[l.x,l.y],[l.x,l.y-38]],'#f1e6bc',3);}}
g.save();g.setLineDash([18,14]);polygon(g,stageOutline,null,'#c9db9660',3);g.restore();textAt(g,'WOLA · KOLEJNY ETAP',1400,4200,30,'#dae2c28a');textAt(g,'PRAGA · KOLEJNY ETAP',6800,3800,30,'#dae2c28a');textAt(g,'MOKOTÓW · KOLEJNY ETAP',3700,8200,30,'#dae2c28a');textAt(g,'ŻOLIBORZ · KOLEJNY ETAP',3000,900,30,'#dae2c28a');}
makeMap();
// Full-resolution nearby map tiles; the overview remains small enough for mobile memory.
const detailTiles=new Map(),TILE=512;
function detailTile(tx,ty){const key=tx+','+ty;if(detailTiles.has(key)){const c=detailTiles.get(key);detailTiles.delete(key);detailTiles.set(key,c);return c;}const c=document.createElement('canvas');c.width=c.height=TILE;const g=c.getContext('2d',{alpha:false}),x=tx*TILE,y=ty*TILE;g.drawImage(mapCanvas,x*CACHE_SCALE,y*CACHE_SCALE,TILE*CACHE_SCALE,TILE*CACHE_SCALE,0,0,TILE,TILE);g.translate(-x,-y);const nearby=[...roadIndex.near(x+TILE/2,y+TILE/2,TILE*.72)];for(const b of buildingIndex.near(x+TILE/2,y+TILE/2,TILE*.72))paintBuilding(g,b);g.lineCap='round';g.lineJoin='round';for(const edge of nearby)line(g,[[edge.a.x,edge.a.y],[edge.b.x,edge.b.y]],edge.road.bridge?'#c9c7b4':'#c0bdac',edge.road.width+10);for(const edge of nearby)line(g,[[edge.a.x,edge.a.y],[edge.b.x,edge.b.y]],edge.road.foot?'#b9ac92':'#424e52',edge.road.width);for(const edge of nearby)if(!edge.road.one&&!edge.road.foot&&edge.road.width>=30)line(g,[[edge.a.x,edge.a.y],[edge.b.x,edge.b.y]],'#d8cda175',1,[9,11]);detailTiles.set(key,c);if(detailTiles.size>32)detailTiles.delete(detailTiles.keys().next().value);return c;}
function drawDetail(g,sx,sy,sw,sh){for(let tx=Math.floor(sx/TILE);tx<=Math.floor((sx+sw)/TILE);tx++)for(let ty=Math.floor(sy/TILE);ty<=Math.floor((sy+sh)/TILE);ty++)if(tx>=0&&ty>=0&&tx*TILE<WORLD&&ty*TILE<WORLD)g.drawImage(detailTile(tx,ty),tx*TILE,ty*TILE);const labels=new Map();for(const edge of roadIndex.near(camera.x,camera.y,Math.max(W,H)/zoom/2)){if(!edge.road.name||edge.length<65)continue;const p={x:(edge.a.x+edge.b.x)/2,y:(edge.a.y+edge.b.y)/2};if(!visible(p,0))continue;const old=labels.get(edge.road.name);if(!old||dist(p,camera)<dist(old.p,camera))labels.set(edge.road.name,{edge,p});}for(const [name,{edge,p}] of labels){let a=Math.atan2(edge.b.y-edge.a.y,edge.b.x-edge.a.x);if(Math.abs(a)>Math.PI/2)a+=Math.PI;g.save();g.translate(p.x,p.y);g.rotate(a);g.font='bold 8px Arial';g.textAlign='center';const width=g.measureText(name.toUpperCase()).width;rect(g,-width/2-3,-edge.road.width/2-13,width+6,11,'#263a35b0');textAt(g,name.toUpperCase(),0,-edge.road.width/2-5,8,'#e5ddc0');g.restore();}}
function nearestRoad(p){let best=null,d=Infinity;for(const s of driveSegments){const q=segProject(p.x,p.y,s.a,s.b);if(q.d<d){d=q.d;best={...q,segment:s};}}return best;}
function lanePosition(s,reverse,t){const a=reverse?s.b:s.a,b=reverse?s.a:s.b,vx=(b.x-a.x)/s.length,vy=(b.y-a.y)/s.length,offset=s.road.one?0:Math.min(7,s.road.width*.22);return {x:a.x+(b.x-a.x)*t-vy*offset,y:a.y+(b.y-a.y)*t+vx*offset,a:Math.atan2(vy,vx)};}
function routeNodes(start,end){if(start===end)return [start];const heap=[{id:start,cost:0,score:0}],costs=new Map([[start,0]]),prev=new Map();let count=0;while(heap.length&&count++<30000){heap.sort((a,b)=>b.score-a.score);const n=heap.pop();if(n.cost!==costs.get(n.id))continue;if(n.id===end){const route=[end];while(route[0]!==start)route.unshift(prev.get(route[0]));return route;}for(const e of graph.get(n.id)?.edges||[]){const cost=n.cost+e.segment.length;if(cost<(costs.get(e.to)??Infinity)){costs.set(e.to,cost);prev.set(e.to,n.id);heap.push({id:e.to,cost,score:cost+dist(graph.get(e.to),graph.get(end))});}}}return [];}
function roadRoute(from,to){const a=nearestRoad(from),b=nearestRoad(to);if(!a||!b)return [];const start=a.segment.road.one?a.segment.to:(dist(from,a.segment.a)<dist(from,a.segment.b)?a.segment.from:a.segment.to),end=b.segment.from;const ids=routeNodes(start,end);return ids.length?[from,{x:a.x,y:a.y},...ids.map(id=>graph.get(id)),{x:b.x,y:b.y},to]:[];}
function assignEdge(c,s,reverse=false,t=0){c.edge=s;c.reverse=reverse;c.progress=t;c.target=reverse?s.a:s.b;c.dir=s.id+(reverse?.5:0);}
function chooseNext(c){const id=c.reverse?c.edge.from:c.edge.to;let opts=(graph.get(id)?.edges||[]).filter(e=>mainNodes.has(e.to));const forward=opts.filter(e=>e.segment!==c.edge);if(forward.length)opts=forward;if(!opts.length){assignEdge(c,c.edge,!c.reverse,0);return;}let choice=opts[Math.floor(rand(0,opts.length))];if(c.police&&wanted>0){if(!c.pursuit||clock>c.repath){const goal=nearestRoad(player);c.pursuit=goal?routeNodes(id,goal.segment.from):[];c.repath=clock+3;}const index=c.pursuit.indexOf(id),next=c.pursuit[index+1];choice=opts.find(e=>e.to===next)||opts.reduce((a,b)=>dist(graph.get(a.to),player)<dist(graph.get(b.to),player)?a:b);}assignEdge(c,choice.segment,choice.reverse,0);}
function spawnCar(i,police=false){for(let tries=0;tries<30;tries++){const s=driveSegments[Math.floor(rand(0,driveSegments.length))];if(s.length<24)continue;const reverse=!s.road.one&&Math.random()<.5,t=rand(.15,.85),p=lanePosition(s,reverse,t),type=police?types[6]:types[[0,1,2,3,4,5,7,8][i%8]],c={...p,s:rand(38,65),type,color:police?'#c1d0d2':type===types[7]?'#d6ae4d':palette[i%palette.length],hp:100,ai:true,police,stuck:0,hit:0,age:0,parked:false,deadTime:0};assignEdge(c,s,reverse,t);if(!carBlocked(c,c.x,c.y)&&!cars.some(o=>dist(o,c)<55)&&dist(c,player)>100){cars.push(c);return c;}}return null;}

// Circle against the rotated body, including a small wheel clearance.
function pedestrianContact(x,y,c,r=8){const ca=Math.cos(c.a),sa=Math.sin(c.a),dx=x-c.x,dy=y-c.y,lx=dx*ca+dy*sa,ly=-dx*sa+dy*ca,hx=c.type.w/2+2,hy=c.type.h/2+2;const qx=clamp(lx,-hx,hx),qy=clamp(ly,-hy,hy);let nx=lx-qx,ny=ly-qy,d=Math.hypot(nx,ny),depth;if(d>=r)return null;if(d>.0001){nx/=d;ny/=d;depth=r-d;}else{const ex=hx-Math.abs(lx),ey=hy-Math.abs(ly);if(ex<ey){nx=lx>=0?1:-1;ny=0;depth=ex+r;}else{nx=0;ny=ly>=0?1:-1;depth=ey+r;}}return {x:nx*ca-ny*sa,y:nx*sa+ny*ca,depth};}
function pedestrianBlocked(x,y,ignore=null){return blocked(x,y,8)||cars.some(c=>c!==ignore&&pedestrianContact(x,y,c));}
function movePedestrian(mx,my){let x=player.x+mx,y=player.y+my;for(let pass=0;pass<3;pass++)for(const c of cars){const h=pedestrianContact(x,y,c);if(!h)continue;const into=mx*h.x+my*h.y;if(into<0){mx-=into*h.x;my-=into*h.y;x=player.x+mx;y=player.y+my;}}if(!pedestrianBlocked(x,y)){player.x=x;player.y=y;return;}if(!pedestrianBlocked(player.x+mx,player.y))player.x+=mx;if(!pedestrianBlocked(player.x,player.y+my))player.y+=my;}
function resolvePedestrianCars(){if(player.car)return;for(let pass=0;pass<3;pass++){let touched=false;for(const c of cars){const hit=pedestrianContact(player.x,player.y,c);if(!hit)continue;touched=true;const speed=Math.abs(c.s);if(speed>45)hurt(speed*.09);const x=player.x+hit.x*(hit.depth+.05),y=player.y+hit.y*(hit.depth+.05);if(!pedestrianBlocked(x,y,c)){player.x=x;player.y=y;}else c.s=0;}if(!touched)break;}}
function carBlocked(c,x,y,a=c.a){const ca=Math.cos(a),sa=Math.sin(a),l=c.type.w/2,w=c.type.h/2;for(const [u,v] of [[-l,-w],[-l,w],[l,-w],[l,w],[0,0]])if(blocked(x+u*ca-v*sa,y+u*sa+v*ca,2))return true;return false;}
for(const t of types){t.w*=.55;t.h*=.55;}
// Start at the east side of Palace of Culture, on the mapped Marszałkowska carriageway.
const startRoad=nearestRoad(geo(21.0112,52.2305));
const starter={...lanePosition(startRoad.segment,false,startRoad.t),s:0,type:types[1],color:'#d2b66b',hp:100,ai:false,police:false,hit:0,age:0,parked:true,deadTime:0};
const spawnPoint={x:starter.x+Math.cos(starter.a+Math.PI/2)*27,y:starter.y+Math.sin(starter.a+Math.PI/2)*27};
if(blocked(spawnPoint.x,spawnPoint.y,9)){spawnPoint.x=starter.x;spawnPoint.y=starter.y;}
player.x=spawnPoint.x;player.y=spawnPoint.y;camera={...spawnPoint};
for(let i=0;i<180;i++)spawnCar(i);cars.push(starter);
for(const p of [[21.008,52.224],[20.995,52.245],[21.033,52.225]]){const q=nearestRoad(geo(...p));garages.push({x:q.x,y:q.y});}
function spawnPed(){let p={x:0,y:0,a:rand(0,TAU),color:palette[Math.floor(rand(0,palette.length))],s:rand(18,35),panic:0,hp:40,step:rand(0,6)};for(let i=0;i<100;i++){p.x=rand(100,WORLD-100);p.y=rand(100,WORLD-100);if(!blocked(p.x,p.y,9)&&!onRoad(p.x,p.y)){peds.push(p);return;}}}for(let i=0;i<145;i++)spawnPed();
function save(){best=Math.max(best,cash);try{localStorage.setItem('crimecity-best-v2',String(best));localStorage.setItem('crimecity-cash-v2',String(cash));}catch{}}
function toast(t){$('toast').textContent=t;$('toast').style.opacity='1';toastUntil=clock+3.7;}
function crime(n){wanted=clamp(wanted+n,0,5);lastCrime=clock;}
let audio=null,engine=null,engineGain=null,soundOn=false,musicOn=true,musicBus=null,noiseBuffer=null,nextMusicTime=0,musicStep=0;const musicVoices=new Set();
function initAudio(){if(audio)return;try{audio=new(window.AudioContext||window.webkitAudioContext)();engine=audio.createOscillator();engine.type='sawtooth';engineGain=audio.createGain();engineGain.gain.value=0;engine.connect(engineGain);engineGain.connect(audio.destination);engine.start();musicBus=audio.createGain();musicBus.gain.value=.7;musicBus.connect(audio.destination);noiseBuffer=audio.createBuffer(1,audio.sampleRate*.15,audio.sampleRate);const samples=noiseBuffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1)*(1-i/samples.length);nextMusicTime=audio.currentTime+.08;}catch{}}
function tone(freq,duration=.1,type='square',volume=.03){if(!soundOn||!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(25,freq*.45),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
// Original eight-bar synth-pop loop: A minor, F, C, G at 108 BPM.
const leadMelody=[76,0,79,81,0,79,76,72, 74,76,0,72,71,0,69,0, 72,0,76,77,0,76,72,69, 71,72,0,69,67,0,69,0, 76,0,79,84,0,83,79,76, 74,76,79,0,76,74,72,0, 74,0,79,81,0,79,74,71, 72,74,0,71,69,0,67,0];
const chords=[[57,60,64],[53,57,60],[48,52,55],[55,59,62]];
function rememberVoice(o){musicVoices.add(o);o.onended=()=>{musicVoices.delete(o);o.disconnect();};}
function musicNote(note,at,duration,volume,type='triangle'){const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=440*Math.pow(2,(note-69)/12);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(volume,at+.015);g.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(g);g.connect(musicBus);rememberVoice(o);o.onended=()=>{musicVoices.delete(o);o.disconnect();g.disconnect();};o.start(at);o.stop(at+duration+.02);}
function drum(at,kick=false,snare=false){const g=audio.createGain();g.connect(musicBus);const o=kick?audio.createOscillator():audio.createBufferSource();if(kick){o.frequency.setValueAtTime(130,at);o.frequency.exponentialRampToValueAtTime(42,at+.15);o.connect(g);}else{o.buffer=noiseBuffer;const filter=audio.createBiquadFilter();filter.type='highpass';filter.frequency.value=snare?1500:6500;o.connect(filter);filter.connect(g);}const dur=kick?.18:snare?.12:.045;g.gain.setValueAtTime(kick?.13:snare?.075:.025,at);g.gain.exponentialRampToValueAtTime(.001,at+dur);rememberVoice(o);o.onended=()=>{musicVoices.delete(o);o.disconnect();g.disconnect();};o.start(at);o.stop(at+dur);}
function stopMusic(){for(const o of musicVoices){try{o.stop();}catch{}}musicVoices.clear();if(audio)nextMusicTime=audio.currentTime+.05;}
function pumpMusic(){if(!audio||audio.state!=='running'||!musicOn||!active)return;const eighth=60/108/2;if(nextMusicTime<audio.currentTime)nextMusicTime=audio.currentTime+.04;while(nextMusicTime<audio.currentTime+.14){const step=musicStep%64,beat=step%8,chord=chords[Math.floor(step/16)],at=nextMusicTime;if(leadMelody[step]){musicNote(leadMelody[step],at,eighth*1.7,.042);musicNote(leadMelody[step],at+eighth*.75,eighth,.011,'sine');}if(beat%2===0)musicNote(chord[0]-12+(beat===6?7:0),at,eighth*1.6,.09,'sine');if(beat===0)for(const n of chord)musicNote(n,at,eighth*7.5,.014,'triangle');if(beat===0||beat===4)drum(at,true);if(beat===2||beat===6)drum(at,false,true);drum(at);musicStep++;nextMusicTime+=eighth;}}
$('music').addEventListener('click',()=>{initAudio();musicOn=!musicOn;$('music').textContent=musicOn?'MUZ. WŁ.':'MUZ. WYŁ.';$('music').setAttribute('aria-pressed',String(musicOn));$('music').setAttribute('aria-label',musicOn?'Wyłącz muzykę':'Włącz muzykę');if(!musicOn)stopMusic();else if(audio){nextMusicTime=audio.currentTime+.05;audio.resume().catch(()=>{});}});
function resetInput(){for(const k in keys)delete keys[k];input.x=input.y=0;input.fire=input.brake=false;input.id=null;$('stick').style.transform='';}
function pause(){if(!started||dead)return;active=!active;resetInput();$('overlay').style.display=active?'none':'flex';$('play').textContent='WRÓĆ NA ULICE →';$('intro').textContent='Gra wstrzymana. Miasto poczeka na Twój powrót.';if(!active){stopMusic();if(engineGain)engineGain.gain.value=0;}}
function start(){if(dead){player.car=null;player.x=spawnPoint.x;player.y=spawnPoint.y;player.hp=100;wanted=0;arrest=0;invincible=5;dead=false;job=null;officers.length=0;policeBullets.length=0;navRoute=[];for(const c of cars)if(c.police){c.ai=false;c.deployed=0;}toast('Wracasz na ulice. Uważaj na ruch.');}active=true;started=true;frameTime=0;acc=0;$('overlay').style.display='none';resetInput();initAudio();if(audio&&(soundOn||musicOn)){nextMusicTime=audio.currentTime+.05;audio.resume().catch(()=>{});}}
function die(reason){if(dead)return;dead=true;active=false;cash=Math.max(0,cash-150);save();resetInput();$('overlay').style.display='flex';$('intro').textContent=reason+' Koszt powrotu: do 150 zł. Zebrana gotówka i rekord są zapisywane na tym urządzeniu.';$('play').textContent='WRÓĆ DO MIASTA →';stopMusic();if(engineGain)engineGain.gain.value=0;}
function hurt(n){if(invincible>0||dead)return;player.hp=Math.max(0,player.hp-n);invincible=.65;shake=6;if(player.hp<=0)die('Koniec przejażdżki.');}
function nearestCar(){let best=null,d=64;for(const c of cars)if(c.hp>0){const dd=dist(c,player);if(dd<d){best=c;d=dd;}}return best;}
function action(){if(!active)return;if(player.car){const c=player.car;if(Math.abs(c.s)>110){toast('Zwolnij przed wysiadaniem.');return;}for(const side of [1,-1,2]){let a=c.a+Math.PI/2*side,x=c.x+Math.cos(a)*40,y=c.y+Math.sin(a)*40;if(!blocked(x,y,10)&&!cars.some(o=>o!==c&&Math.hypot(o.x-x,o.y-y)<26)){player.x=x;player.y=y;player.car=null;c.s*=.3;invincible=1;toast('Pieszo · mysz celuje, R zmienia broń');return;}}toast('Brak miejsca. Odsuń auto od przeszkody.');return;}let c=nearestCar();if(!c){toast('Podejdź bliżej sprawnego auta.');return;}if(c.ai)crime(c.police?1.2:.55);c.ai=false;c.parked=false;player.car=c;player.x=c.x;player.y=c.y;toast(c.type.name+' · Shift / HAMULEC = ręczny');tone(160,.12,'triangle');}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-75,75),vy:rand(-75,75),life:rand(.2,.6),max:.6,color});if(particles.length>260)particles.splice(0,particles.length-260);}
function damageCar(c,n){if(c.hp<=0)return;c.hp=Math.max(0,c.hp-n);if(c.hp<=0){c.ai=false;c.s=0;c.deadTime=clock;explosions.push({x:c.x,y:c.y,age:0,seed:rand(0,TAU)});if(explosions.length>18)explosions.shift();burst(c.x,c.y,'#ffcb75',42);tone(70,.4,'sawtooth',.06);shake=9;if(player.car===c){player.car=null;for(const a of [c.a+Math.PI/2,c.a-Math.PI/2,c.a+Math.PI]){let x=c.x+Math.cos(a)*48,y=c.y+Math.sin(a)*48;if(!blocked(x,y)){player.x=x;player.y=y;break;}}hurt(38);invincible=2;toast('Auto zniszczone. Znajdź następne.');}}}
function shoot(){if(!active||player.car||fireCooldown>0)return;const w=weapons[weapon];fireCooldown=w.rate;crime(.14);tone(weapon===2?85:180,.075,'sawtooth',.04);for(let i=0;i<w.count;i++){let a=player.a+rand(-w.spread,w.spread);bullets.push({x:player.x+Math.cos(a)*15,y:player.y+Math.sin(a)*15,a,life:w.life,damage:w.damage});}burst(player.x+Math.cos(player.a)*18,player.y+Math.sin(player.a)*18,'#fff1b0',3);for(const p of peds)if(dist(p,player)<230){p.panic=5;p.a=Math.atan2(p.y-player.y,p.x-player.x);}}
function cycle(){weapon=(weapon+1)%3;toast(weapons[weapon].name);}
function missionPoint(lon,lat,label,mode){const q=nearestRoad(geo(lon,lat));return {x:q.x,y:q.y,label,mode};}
const missionDefs=[
{id:'taxi',title:'01 / Kurs przez centrum',description:'Odbierz pasażera przy Pałacu Kultury. Zawieź go na Miodową, przy wjeździe na Stare Miasto.',reward:650,time:240,steps:[{x:starter.x,y:starter.y,label:'Odbierz pasażera przy Pałacu Kultury',mode:'car'},missionPoint(21.010,52.246,'Zatrzymaj się na Miodowej','car')]},
{id:'courier',title:'02 / Starówka — Powiśle',description:'Dwie dostawy: przy Zamku Królewskim i Centrum Nauki Kopernik. Paczki oddaj pieszo.',reward:900,time:300,steps:[missionPoint(21.0145,52.247,'Dostarcz paczkę przy placu Zamkowym — wysiądź','foot'),missionPoint(21.0272,52.2414,'Dostarcz paczkę przy Koperniku — wysiądź','foot')]},
{id:'bridges',title:'03 / Śródmiejskie place',description:'Przejedź przez plac Zbawiciela, plac Trzech Krzyży i rondo de Gaulle’a.',reward:1200,time:270,steps:[missionPoint(21.0172,52.2198,'Zatrzymaj się przy placu Zbawiciela','car'),missionPoint(21.0228,52.2283,'Dotrzyj na plac Trzech Krzyży','car'),missionPoint(21.0215,52.2317,'Przejedź przez rondo de Gaulle’a','car')]},
{id:'escape',title:'04 / Zniknąć na Muranowie',description:'Zgub pościg w ulicach Śródmieścia. Po zniknięciu gwiazdek wróć do warsztatu.',reward:1500,time:300,steps:[{...garages[1],label:'Zgub pościg i wróć do warsztatu','mode':'escape'}]},
{id:'explore',title:'05 / Od Starówki do Łazienek',description:'Odwiedź Stare Miasto, a potem wejście do Łazienek od Alej Ujazdowskich. Bez limitu czasu.',reward:800,time:0,steps:[missionPoint(21.0108,52.2497,'Dotrzyj pieszo w okolice Rynku Starego Miasta','foot'),missionPoint(21.0285,52.215,'Dotrzyj pieszo do wejścia do Łazienek','foot')]}
];
const completed=new Set();try{const a=JSON.parse(localStorage.getItem('crimecity-srodmiescie-missions')||'[]');if(Array.isArray(a))for(const id of a)if(missionDefs.some(m=>m.id===id))completed.add(id);}catch{}
let panelOpen=null,panelWasActive=false,navRoute=[],navRefresh=0;
function pauseForPanel(name){if(!started||dead)return;if(panelOpen)closePanel();panelWasActive=active;active=false;resetInput();stopMusic();if(engineGain)engineGain.gain.value=0;panelOpen=name;$(name).hidden=false;if(name==='atlas')drawAtlas();else renderMissions();}
function closePanel(){if(!panelOpen)return;$(panelOpen).hidden=true;panelOpen=null;active=panelWasActive;frameTime=0;acc=0;if(active&&audio&&(musicOn||soundOn))audio.resume().catch(()=>{});}
function renderMissions(){$('missionList').innerHTML=missionDefs.map(m=>'<article class="missionCard"><div><b>'+m.title+'</b><p>'+m.description+'</p><small>'+m.reward+' zł · '+(m.time?m.time+' sekund':'bez limitu')+(completed.has(m.id)?' · UKOŃCZONA':'')+'</small></div><button class="small acceptMission" data-id="'+m.id+'">'+(job&&job.id===m.id?'AKTYWNA':'START')+'</button></article>').join('');$('missionProgress').textContent=completed.size+' / '+missionDefs.length+' misji ukończonych';$('cancelMission').hidden=!job;}
function beginMission(id){const m=missionDefs.find(v=>v.id===id);if(!m)return;if(job&&job.id===id){closePanel();return;}job={id:m.id,index:0,time:m.time||Infinity,reward:m.reward,target:m.steps[0]};navRoute=roadRoute(player,job.target);navRefresh=clock+2;closePanel();if(m.id==='escape'){crime(Math.max(0,2-wanted));dispatchPatrol();dispatchPatrol();}toast(m.title+' · '+job.target.label);hud();}
function advanceMission(dt){if(!job)return;const m=missionDefs.find(v=>v.id===job.id);job.time-=dt;if(job.time<=0){job=null;navRoute=[];toast('Czas minął. Misję możesz powtórzyć w panelu MISJE.');return;}const target=job.target,mode=target.mode,near=dist(player,target)<(mode==='foot'?30:58),stopped=!player.car||Math.abs(player.car.s)<28,valid=mode==='foot'?!player.car:mode==='escape'?!!player.car&&wanted===0:!!player.car;if(near&&stopped&&valid){job.index++;tone(620,.2,'triangle');if(job.index>=m.steps.length){cash+=job.reward;completed.add(m.id);try{localStorage.setItem('crimecity-srodmiescie-missions',JSON.stringify([...completed]));}catch{}save();toast('MISJA UKOŃCZONA · +'+job.reward+' zł');job=null;navRoute=[];}else{job.target=m.steps[job.index];navRoute=roadRoute(player,job.target);toast(job.target.label);}}if(job&&clock>navRefresh){navRefresh=clock+2;navRoute=roadRoute(player,job.target);}}
function takeJob(){pauseForPanel('missions');}
$('missionList').addEventListener('click',e=>{const button=e.target.closest('[data-id]');if(button)beginMission(button.dataset.id);});$('closeMissions').addEventListener('click',closePanel);$('closeAtlas').addEventListener('click',closePanel);$('cancelMission').addEventListener('click',()=>{job=null;navRoute=[];renderMissions();hud();});$('mapWrap').addEventListener('click',()=>pauseForPanel('atlas'));$('mapWrap').addEventListener('keydown',e=>{if(e.code==='Enter'||e.code==='Space'){e.preventDefault();pauseForPanel('atlas');}});
let atlasScale=1,atlasCenter={x:3650,y:4400};
function drawAtlas(){const g=$('atlasCanvas').getContext('2d'),size=800,span=6800/atlasScale,s=size/span,left=atlasCenter.x-span/2,top=atlasCenter.y-span/2;rect(g,0,0,size,size,'#172e29');g.save();g.beginPath();g.rect(0,0,size,size);g.clip();g.translate(-left*s,-top*s);g.scale(s,s);g.drawImage(mapCanvas,0,0,WORLD,WORLD);if(job&&navRoute.length){line(g,navRoute.map(p=>[p.x,p.y]),'#ffdb80',3/s);circle(g,job.target.x,job.target.y,6/s,'#f5b65e');}g.restore();const placed=[];for(const l of landmarks){const x=(l.x-left)*s,y=(l.y-top)*s;if(x<20||y<15||x>780||y>780)continue;circle(g,x,y,3,'#ffe2a8');g.font='bold 11px Arial';const width=g.measureText(l.name).width+8;let yy=y-15;for(let n=0;n<6&&placed.some(b=>Math.abs(x-b.x)<(width+b.w)/2&&Math.abs(yy-b.y)<16);n++)yy-=16;if(yy<8)continue;rect(g,x-width/2,yy-11,width,15,'#102721eb');textAt(g,l.name,x,yy,11,'#f3eacb');placed.push({x,y:yy,w:width});}
for(const p of garages){const x=(p.x-left)*s,y=(p.y-top)*s;circle(g,x,y,6,'#d4e88c');textAt(g,'G',x,y+3,9,'#29432b');}const x=(player.x-left)*s,y=(player.y-top)*s;circle(g,x,y,6,'#fff');circle(g,x,y,3,'#dc7347');textAt(g,'TY',x,y+17,11,'#fff');$('atlasGoal').textContent=job?job.target.label:'Etap 1: Śródmieście. Przeciągnij mapę, aby przesunąć widok.';}
$('atlasPlus').addEventListener('click',()=>{atlasScale=Math.min(6,atlasScale*1.5);drawAtlas();});$('atlasMinus').addEventListener('click',()=>{atlasScale=Math.max(.75,atlasScale/1.5);drawAtlas();});$('atlasPlayer').addEventListener('click',()=>{atlasCenter={x:player.x,y:player.y};atlasScale=3;drawAtlas();});$('atlasReset').addEventListener('click',()=>{atlasCenter={x:3650,y:4400};atlasScale=1;drawAtlas();});
let atlasDrag=null;$('atlasCanvas').addEventListener('pointerdown',e=>{e.preventDefault();atlasDrag={id:e.pointerId,x:e.clientX,y:e.clientY};$('atlasCanvas').setPointerCapture(e.pointerId);});$('atlasCanvas').addEventListener('pointermove',e=>{if(!atlasDrag||atlasDrag.id!==e.pointerId)return;const span=6800/atlasScale,w=$('atlasCanvas').getBoundingClientRect().width;atlasCenter.x=clamp(atlasCenter.x-(e.clientX-atlasDrag.x)*span/w,0,WORLD);atlasCenter.y=clamp(atlasCenter.y-(e.clientY-atlasDrag.y)*span/w,0,WORLD);atlasDrag.x=e.clientX;atlasDrag.y=e.clientY;drawAtlas();});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('atlasCanvas').addEventListener(event,()=>atlasDrag=null);
const officers=[],policeBullets=[];
function clearPath(a,b,r=9){const n=Math.ceil(dist(a,b)/16);for(let i=1;i<=n;i++)if(blocked(a.x+(b.x-a.x)*i/n,a.y+(b.y-a.y)*i/n,r))return false;return true;}
function walkRoute(a,b){const S=24,N=WORLD/S;const nearest=p=>{let best=null,score=Infinity;for(let x=Math.round(p.x/S)-2;x<=Math.round(p.x/S)+2;x++)for(let y=Math.round(p.y/S)-2;y<=Math.round(p.y/S)+2;y++){let q={x:x*S,y:y*S,gx:x,gy:y};if(x<1||y<1||x>=N||y>=N||blocked(q.x,q.y,9)||!clearPath(p,q))continue;let d=dist(p,q);if(d<score){score=d;best=q;}}return best;};let start=nearest(a),goal=nearest(b);if(!start||!goal)return [];const key=p=>p.gx+','+p.gy,open=[{...start,cost:0,score:dist(start,goal)}],prev=new Map(),costs=new Map([[key(start),0]]);let found=null;for(let count=0;open.length&&count<1800;count++){open.sort((a,b)=>a.score-b.score);const n=open.shift();if(n.gx===goal.gx&&n.gy===goal.gy){found=n;break;}for(const [xx,yy] of [[1,0],[-1,0],[0,1],[0,-1]]){const q={gx:n.gx+xx,gy:n.gy+yy,x:(n.gx+xx)*S,y:(n.gy+yy)*S},k=key(q),cost=n.cost+S;if(blocked(q.x,q.y,9)||!clearPath(n,q)||cost>=(costs.get(k)??Infinity))continue;costs.set(k,cost);prev.set(k,n);open.push({...q,cost,score:cost+dist(q,goal)});}}if(!found)return [];const path=[b];while(found){path.push(found);found=prev.get(key(found));}return path.reverse();}
function dispatchPatrol(){let c=spawnCar(cars.length,true);if(!c)return;const slots=driveSegments.filter(s=>s.length>40&&dist(s.a,player)>420&&dist(s.a,player)<800);for(let i=0;i<30&&slots.length;i++){const s=slots[Math.floor(rand(0,slots.length))],p=lanePosition(s,false,.5);if(cars.some(o=>o!==c&&dist(o,p)<65)||carBlocked(c,p.x,p.y,p.a))continue;Object.assign(c,p);assignEdge(c,s,false,.5);return;}}
function dismount(c){if(c.deployed||clock<(c.nextDismount||0)||officers.length>=12)return;c.s=0;c.deployed=0;for(const side of [-1,1]){const a=c.a+side*Math.PI/2,p={x:c.x+Math.cos(a)*31,y:c.y+Math.sin(a)*31};if(pedestrianBlocked(p.x,p.y))continue;officers.push({...p,a,home:c,hp:70,color:'#31516b',s:103,path:[],repath:0,shot:clock+2,step:0,grab:0});c.deployed++;}c.nextDismount=clock+8;}
function updateOfficers(dt){for(const c of cars)if(c.police&&c.ai&&c.hp>0&&wanted>=.5&&!player.car&&dist(c,player)<165&&Math.abs(c.s)<75)dismount(c);
for(let i=officers.length-1;i>=0;i--){const o=officers[i];if(o.hp<=0){bodies.push({x:o.x,y:o.y,a:o.a,color:o.color});if(bodies.length>120)bodies.shift();o.home.deployed=Math.max(0,(o.home.deployed||1)-1);officers.splice(i,1);continue;}const returning=wanted===0||(player.car&&dist(o,player)>430),target=returning?o.home:player;if(returning&&dist(o,o.home)<46&&o.home.hp>0){o.home.deployed=Math.max(0,(o.home.deployed||1)-1);o.home.nextDismount=clock+6;officers.splice(i,1);continue;}if(dist(o,player)>1200){o.home.deployed=Math.max(0,(o.home.deployed||1)-1);officers.splice(i,1);continue;}
let goal=target;if(!clearPath(o,target)){if(clock>o.repath){o.path=walkRoute(o,target);o.repath=clock+1.1;}while(o.path.length&&dist(o,o.path[0])<18)o.path.shift();goal=o.path[0]||o;}else o.path=[];const a=Math.atan2(goal.y-o.y,goal.x-o.x),speed=returning?80:103;for(const offset of [0,.6,-.6,1.2,-1.2]){const x=o.x+Math.cos(a+offset)*speed*dt,y=o.y+Math.sin(a+offset)*speed*dt;if(!pedestrianBlocked(x,y)){o.x=x;o.y=y;o.a=a+offset;break;}}o.step+=dt*9;
if(!returning&&dist(o,player)<23&&!player.car){o.grab+=dt;toastUntil=Math.max(toastUntil,clock+.2);$('toast').textContent='POLICJA · uciekaj sprintem!';$('toast').style.opacity='1';if(o.grab>1.8)die('Zatrzymany przez pieszy patrol.');}else o.grab=Math.max(0,o.grab-dt*2);
if(!returning&&wanted>=3&&dist(o,player)<210&&dist(o,player)>45&&clock>o.shot&&clearPath(o,player)){o.shot=clock+1.5;const a=Math.atan2(player.y-o.y,player.x-o.x)+rand(-.1,.1);policeBullets.push({x:o.x+Math.cos(a)*14,y:o.y+Math.sin(a)*14,a,life:.7});tone(125,.06,'square',.018);}
}
for(let i=policeBullets.length-1;i>=0;i--){const b=policeBullets[i];b.x+=Math.cos(b.a)*430*dt;b.y+=Math.sin(b.a)*430*dt;b.life-=dt;let hit=blocked(b.x,b.y,1);for(const c of cars)if(pedestrianContact(b.x,b.y,c,1)){damageCar(c,7);hit=true;break;}if(!player.car&&dist(b,player)<10){hurt(10);hit=true;}if(hit||b.life<=0)policeBullets.splice(i,1);}}
$('play').addEventListener('click',start);$('pause').addEventListener('click',pause);$('sound').addEventListener('click',()=>{initAudio();soundOn=!soundOn;$('sound').textContent='DŹW. '+(soundOn?'WŁ.':'WYŁ.');$('sound').setAttribute('aria-pressed',String(soundOn));$('sound').setAttribute('aria-label',soundOn?'Wyłącz dźwięk':'Włącz dźwięk');if(soundOn&&audio)audio.resume().catch(()=>{});});$('night').addEventListener('click',()=>{night=!night;$('night').textContent=night?'DZIEŃ':'NOC';$('night').setAttribute('aria-pressed',String(night));});
$('enter').addEventListener('pointerdown',e=>{e.preventDefault();action();});$('switch').addEventListener('pointerdown',e=>{e.preventDefault();cycle();});$('job').addEventListener('pointerdown',e=>{e.preventDefault();takeJob();});
for(const [id,prop] of [['fire','fire'],['brake','brake']]){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);input[prop]=true;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>input[prop]=false);}
function joyMove(e){const r=$('joy').getBoundingClientRect(),m=r.width*.34;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y);if(l>m){x*=m/l;y*=m/l;}input.x=x/m;input.y=y/m;$('stick').style.transform=`translate(${x}px,${y}px)`;mouseAim=false;}
$('joy').addEventListener('pointerdown',e=>{if(input.id!==null)return;e.preventDefault();input.id=e.pointerId;$('joy').setPointerCapture(e.pointerId);joyMove(e);});$('joy').addEventListener('pointermove',e=>{if(e.pointerId===input.id)joyMove(e);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('joy').addEventListener(ev,e=>{if(e.pointerId===input.id){input.id=null;input.x=input.y=0;$('stick').style.transform='';}});
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'&&panelOpen){closePanel();return;}if(e.code==='KeyM'){pauseForPanel('atlas');return;}if(e.code==='Escape'||e.code==='KeyP'){pause();return;}if(panelOpen)return;keys[e.code]=true;if(e.code==='KeyE')action();if(e.code==='KeyR')cycle();if(e.code==='KeyF')takeJob();});addEventListener('keyup',e=>{keys[e.code]=false;});addEventListener('blur',()=>{if(active)pause();else resetInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)pause();});
cv.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){input.mouseX=e.clientX;input.mouseY=e.clientY;mouseAim=true;}});cv.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'){cv.setPointerCapture(e.pointerId);input.fire=true;}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])cv.addEventListener(ev,()=>input.fire=false);cv.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
function traffic(c,dt){c.age+=dt;if(c.deployed||c.hp<=0){c.s=0;return;}let target=c.police&&wanted>0?110:62+(c.type.max-200)*.045;
for(const o of cars){if(c===o)continue;const xx=o.x-c.x,yy=o.y-c.y,forward=xx*Math.cos(c.a)+yy*Math.sin(c.a),side=Math.abs(-xx*Math.sin(c.a)+yy*Math.cos(c.a));if(forward>0&&forward<(c.type.w+o.type.w)/2+14+c.s*.25&&side<(c.type.h+o.type.h)/2+2)target=Math.min(target,Math.max(0,o.s-12));}
if(c.police&&wanted>=.5&&!player.car&&dist(c,player)<120)target=Math.min(target,18);
c.s+=(target-c.s)*Math.min(1,dt*3);let travel=c.s*dt;const before={edge:c.edge,reverse:c.reverse,progress:c.progress};let n=0;while(travel>0&&n++<30){const remaining=(1-c.progress)*c.edge.length;if(travel<remaining){c.progress+=travel/c.edge.length;travel=0;}else{travel-=remaining;chooseNext(c);}}
const p=lanePosition(c.edge,c.reverse,c.progress);const nextAngle=c.a+clamp(angle(p.a-c.a),-6*dt,6*dt);
if(!carBlocked(c,p.x,p.y,nextAngle)){c.x=p.x;c.y=p.y;c.a=nextAngle;}else{assignEdge(c,before.edge,before.reverse,before.progress);c.s=0;}
if(c.s<5)c.stuck+=dt;else c.stuck=0;
if(c.stuck>16&&dist(c,player)>600){const other=spawnCar(cars.length,c.police);if(other){cars.splice(cars.indexOf(other),1);Object.assign(c,other);}}
}
function overlap(a,b){const axes=[{x:Math.cos(a.a),y:Math.sin(a.a)},{x:-Math.sin(a.a),y:Math.cos(a.a)},{x:Math.cos(b.a),y:Math.sin(b.a)},{x:-Math.sin(b.a),y:Math.cos(b.a)}];let min=Infinity,normal=null;for(const n of axes){let ra=Math.abs(n.x*Math.cos(a.a)+n.y*Math.sin(a.a))*a.type.w/2+Math.abs(-n.x*Math.sin(a.a)+n.y*Math.cos(a.a))*a.type.h/2,rb=Math.abs(n.x*Math.cos(b.a)+n.y*Math.sin(b.a))*b.type.w/2+Math.abs(-n.x*Math.sin(b.a)+n.y*Math.cos(b.a))*b.type.h/2,delta=(a.x-b.x)*n.x+(a.y-b.y)*n.y,o=ra+rb-Math.abs(delta);if(o<=0)return null;if(o<min){min=o;normal={x:n.x*(delta>=0?1:-1),y:n.y*(delta>=0?1:-1)};}}return {n:normal,d:min};}
function carCollisions(){const buckets=new Map();for(const c of cars){let k=Math.floor(c.x/100)+','+Math.floor(c.y/100);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(c);}const checked=new Set();for(let i=0;i<cars.length;i++){const a=cars[i],gx=Math.floor(a.x/100),gy=Math.floor(a.y/100);for(let xx=-1;xx<=1;xx++)for(let yy=-1;yy<=1;yy++)for(const b of buckets.get((gx+xx)+','+(gy+yy))||[]){if(a===b)continue;const j=cars.indexOf(b),key=Math.min(i,j)+':'+Math.max(i,j);if(checked.has(key))continue;checked.add(key);if(dist(a,b)>(a.type.w+b.type.w)/2)continue;const hit=overlap(a,b);if(!hit)continue;const move=hit.d*.51;if(!carBlocked(a,a.x+hit.n.x*move,a.y+hit.n.y*move)){a.x+=hit.n.x*move;a.y+=hit.n.y*move;}if(!carBlocked(b,b.x-hit.n.x*move,b.y-hit.n.y*move)){b.x-=hit.n.x*move;b.y-=hit.n.y*move;}let impact=Math.abs((Math.cos(a.a)*a.s-Math.cos(b.a)*b.s)*hit.n.x+(Math.sin(a.a)*a.s-Math.sin(b.a)*b.s)*hit.n.y);if(impact>32&&clock>a.hit&&clock>b.hit){a.hit=b.hit=clock+.45;damageCar(a,impact*.065);damageCar(b,impact*.065);burst((a.x+b.x)/2,(a.y+b.y)/2,'#e9c27b',7);if(a===player.car||b===player.car){crime(.12);shake=Math.min(10,impact/24);tone(80,.12,'sawtooth');}}a.s*=.65;b.s*=.65;}}}
function update(dt){pumpMusic();clock+=dt;invincible=Math.max(0,invincible-dt);fireCooldown=Math.max(0,fireCooldown-dt);shake*=.9;if(clock>toastUntil)$('toast').style.opacity='0';
let ax=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),ay=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0),braking=keys.ShiftLeft||keys.ShiftRight||input.brake;
if(player.car){const c=player.car;let gas=-ay,steer=ax;if(Math.hypot(input.x,input.y)>.12){const desired=Math.atan2(input.y,input.x),dif=angle(desired-c.a);steer=clamp(dif*1.6,-1,1);gas=Math.max(.3,Math.hypot(input.x,input.y));}else if(input.fire)gas=1;let speed=Math.abs(c.s),turn=steer*c.type.grip*clamp(speed/110,0,1)*(c.s<0?-1:1)*dt;let na=c.a+turn*(braking?1.5:1);if(!carBlocked(c,c.x,c.y,na))c.a=na;c.s+=gas*c.type.acc*dt;c.s*=Math.exp(-(braking?5:gas? .23:1.2)*dt);c.s=clamp(c.s,-95,c.type.max*(c.hp<25?.65:1));let nx=c.x+Math.cos(c.a)*c.s*dt,ny=c.y+Math.sin(c.a)*c.s*dt;if(!carBlocked(c,nx,ny)){c.x=nx;c.y=ny;distance+=Math.abs(c.s)*dt;}else{if(speed>35&&clock>c.hit){damageCar(c,speed*.07);c.hit=clock+.45;shake=speed/30;burst(c.x+Math.cos(c.a)*c.type.w/2,c.y+Math.sin(c.a)*c.type.w/2,'#e8bd72');tone(75,.12,'sawtooth');}c.s*=-.24;}if(speed>90&&(braking||Math.abs(steer)>.6)&&Math.random()<.5){skids.push({x:c.x,y:c.y,a:c.a,t:clock,w:c.type.h});if(skids.length>220)skids.shift();}if(player.car){player.x=c.x;player.y=c.y;player.a=c.a;}}
else{ax+=input.x;ay+=input.y;const length=Math.hypot(ax,ay),speed=braking?175:115;if(length>.1){ax/=Math.max(1,length);ay/=Math.max(1,length);if(!mouseAim)player.a=Math.atan2(ay,ax);movePedestrian(ax*speed*dt,ay*speed*dt);}if(mouseAim)player.a=Math.atan2((input.mouseY-H/2)/zoom+camera.y-player.y,(input.mouseX-W/2)/zoom+camera.x-player.x);if(input.fire||keys.Space)shoot();}
for(const c of cars)if(c.ai)traffic(c,dt);else if(c!==player.car&&c.hp>0&&Math.abs(c.s)>1){let nx=c.x+Math.cos(c.a)*c.s*dt,ny=c.y+Math.sin(c.a)*c.s*dt;if(!carBlocked(c,nx,ny)){c.x=nx;c.y=ny;}c.s*=Math.exp(-3*dt);}carCollisions();if(player.car){player.x=player.car.x;player.y=player.car.y;}
for(let i=peds.length-1;i>=0;i--){const p=peds[i];p.panic=Math.max(0,p.panic-dt);p.step+=dt*(p.panic?12:5);if(Math.random()<dt*.5)p.a+=rand(-1,1);let nx=p.x+Math.cos(p.a)*p.s*(p.panic?3:1)*dt,ny=p.y+Math.sin(p.a)*p.s*(p.panic?3:1)*dt;if(!blocked(nx,ny,7)&&(!onRoad(nx,ny)||p.panic)){p.x=nx;p.y=ny;}else p.a+=2;for(const c of cars){if(dist(p,c)<c.type.w/2+8&&Math.abs(c.s)>60){p.hp=0;if(c===player.car)crime(.4);break;}}if(p.hp<=0){bodies.push({x:p.x,y:p.y,a:p.a,color:p.color});if(bodies.length>120)bodies.shift();peds.splice(i,1);}}
resolvePedestrianCars();
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];let hit=false;for(let step=0;step<3&&!hit;step++){b.x+=Math.cos(b.a)*670*dt/3;b.y+=Math.sin(b.a)*670*dt/3;if(blocked(b.x,b.y,1)){hit=true;burst(b.x,b.y,'#b9b5a0',3);break;}for(const c of cars){const xx=b.x-c.x,yy=b.y-c.y,ca=Math.cos(c.a),sa=Math.sin(c.a);if(Math.abs(xx*ca+yy*sa)<c.type.w/2&&Math.abs(-xx*sa+yy*ca)<c.type.h/2){damageCar(c,b.damage);hit=true;burst(b.x,b.y,'#e5c684',4);break;}}if(!hit)for(const o of officers)if(dist(o,b)<10){o.hp-=b.damage;crime(.35);hit=true;break;}if(!hit)for(const p of peds)if(dist(p,b)<9){p.hp-=b.damage;crime(.2);hit=true;break;}}b.life-=dt;if(hit||b.life<=0)bullets.splice(i,1);}
updateOfficers(dt);let cops=cars.filter(c=>c.police&&c.ai&&c.hp>0);if(wanted>=.5&&cops.length<Math.ceil(wanted)+1&&Math.random()<dt*.4)dispatchPatrol();
let visiblePolice=cops.some(c=>dist(c,player)<430)||officers.some(o=>dist(o,player)<340&&clearPath(o,player));if(wanted>0&&clock-lastCrime>10&&!visiblePolice){wanted=Math.max(0,wanted-dt*.11);if(wanted===0){cash+=100;save();toast('POŚCIG ZGUBIONY · +100 zł');}}
let cornered=cops.some(c=>dist(c,player)<65);if(cornered&&player.car&&Math.abs(player.car.s)<35){arrest+=dt;if(arrest>=4)die('Policja Cię zatrzymała.');}else arrest=Math.max(0,arrest-dt*2);
for(const g of garages)if(player.car&&dist(g,player)<64&&Math.abs(player.car.s)<22&&player.car.hp<99){player.car.hp=100;player.hp=100;toast('Warsztat · auto i zdrowie przywrócone');tone(450,.2,'triangle');}
advanceMission(dt);
for(let i=explosions.length-1;i>=0;i--){explosions[i].age+=dt;if(explosions[i].age>3.2)explosions.splice(i,1);}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.life<=0)particles.splice(i,1);}if(peds.length<135&&Math.random()<dt*2)spawnPed();for(let i=cars.length-1;i>=0;i--)if(cars[i].hp<=0&&clock-cars[i].deadTime>20&&dist(cars[i],player)>650){cars.splice(i,1);spawnCar(i);}
if(engineGain){engineGain.gain.setTargetAtTime(soundOn&&player.car ? .018 : 0,audio.currentTime,.08);engine.frequency.setTargetAtTime(player.car?45+Math.abs(player.car.s)*.6:40,audio.currentTime,.08);if(soundOn&&visiblePolice&&Math.floor(clock*3)!==Math.floor((clock-dt)*3))tone(Math.floor(clock*3)%2?650:850,.25,'sine',.016);}
uiTimer+=dt;if(uiTimer>.1){uiTimer=0;hud();}}
function hud(){const c=player.car;$('mission').classList.toggle('job-active',!!job);$('switch').textContent=weapons[weapon].name;$('health').textContent=Math.ceil(player.hp);$('healthbar').style.width=player.hp+'%';$('healthbar').style.background=player.hp<30?'#ed8b70':'#cdeb8b';$('wanted').textContent='★ '.repeat(Math.ceil(wanted))+'☆ '.repeat(5-Math.ceil(wanted));$('money').textContent=String(cash).padStart(5,'0')+' zł';$('speed').innerHTML=(c?Math.round(Math.abs(c.s)*.48):0)+' <small>KM/H</small>';$('enter').textContent=arrest>.2?'ZATRZYMANIE '+Math.min(100,Math.round(arrest*25))+'%':c?'WYJDŹ Z AUTA':'WEJDŹ DO AUTA';$('fire').textContent=c?'GAZ':'STRZAŁ';$('brake').textContent=c?'HAMULEC':'BIEG';$('district').textContent=district(player);if(job)$('mission').innerHTML='<b>'+missionDefs.find(m=>m.id===job.id).title+'</b>'+job.target.label+'<br>'+(Number.isFinite(job.time)?Math.ceil(job.time)+' s · ':'')+(job.index+1)+' / '+missionDefs.find(m=>m.id===job.id).steps.length;else $('mission').innerHTML='<b>WARSZAWA / '+completed.size+' Z 5 MISJI</b>MISJE / F — wybór zadania.<br>Dotknij minimapy — plan miasta.';}
function visible(p,r=80){return Math.abs(p.x-camera.x)<W/(2*zoom)+r&&Math.abs(p.y-camera.y)<H/(2*zoom)+r;}
function drawCar(c){const g=ctx,t=c.type;g.save();g.translate(c.x,c.y);g.rotate(c.a);rect(g,-t.w/2+4,-t.h/2+5,t.w,t.h,'#0b171960');rect(g,-t.w*.36,-t.h/2-3,t.w*.2,t.h+6,'#1a2120');rect(g,t.w*.2,-t.h/2-3,t.w*.2,t.h+6,'#1a2120');rect(g,-t.w/2,-t.h/2,t.w,t.h,c.hp<=0?'#333c38':c.color);rect(g,-t.w/2+3,-t.h/2+2,t.w-7,2,'#fff4');rect(g,-t.w*.15,-t.h*.40,t.w*.37,t.h*.80,'#29434b');rect(g,-t.w*.06,-t.h*.40,t.w*.17,t.h*.80,c.hp<=0?'#464a43':c.color);rect(g,-t.w*.36,-t.h*.34,t.w*.15,t.h*.68,'#344a4e');if(t===types[4]){rect(g,-t.w*.44,-t.h*.45,t.w*.58,t.h*.9,'#a7a89b');for(let x=-t.w*.4;x<t.w*.1;x+=7)rect(g,x,-t.h*.4,1,t.h*.8,'#777d73');}if(t===types[7]){for(let x=-28;x<28;x+=10){rect(g,x,-t.h/2,7,3,'#263e43');rect(g,x,t.h/2-3,7,3,'#263e43');}}if(t===types[3])rect(g,-4,-4,8,8,'#edce63');if(t===types[8]){rect(g,-7,-2,12,4,'#d4634b');rect(g,-3,-6,4,12,'#d4634b');}if(c.police){rect(g,-12,-t.h/2,10,t.h,'#253b47');rect(g,-3,-8,5,8,Math.sin(clock*12)>0?'#f57863':'#8d4946');rect(g,-3,0,5,8,Math.sin(clock*12)<0?'#85bdf1':'#48618b');}rect(g,t.w/2-2,-t.h/2+3,3,4,'#f1e7bd');rect(g,t.w/2-2,t.h/2-7,3,4,'#f1e7bd');rect(g,-t.w/2,-t.h/2+3,2,4,'#c4543c');rect(g,-t.w/2,t.h/2-7,2,4,'#c4543c');if(c.hp<30){circle(g,-t.w*.25,0,8+Math.sin(clock*5)*3,'#262b2780');}g.restore();}
// Bodies remain below live actors; bounded count protects long mobile sessions.
function drawBody(b){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.a);circle(ctx,1,3,12,'#13231c50');rect(ctx,-12,-5,12,4,'#29332d');rect(ctx,-12,2,12,4,'#29332d');rect(ctx,-2,-6,12,12,b.color);rect(ctx,0,-10,4,6,b.color);rect(ctx,4,5,4,6,b.color);circle(ctx,13,0,4,'#c3aa8b');ctx.restore();}
function drawExplosion(e){const t=e.age;ctx.save();ctx.translate(e.x,e.y);
if(t<.85){const k=t/.85,r=12+70*Math.sin(k*Math.PI/2);ctx.globalAlpha=(1-k)*.8;circle(ctx,0,0,r*1.3,'#f5b552');ctx.strokeStyle='#ffe7a2';ctx.lineWidth=3*(1-k);ctx.beginPath();ctx.arc(0,0,15+k*112,0,TAU);ctx.stroke();for(let i=0;i<7;i++){const a=e.seed+i*TAU/7;circle(ctx,Math.cos(a)*r*.38,Math.sin(a)*r*.38,r*.47,i%2?'#ff973f':'#ffd57a');}circle(ctx,0,0,r*.33,'#fff4c4');}
if(t>.18){const k=(t-.18)/3.02;ctx.globalAlpha=Math.min(1,k*6)*(1-k)*.7;for(let i=0;i<5;i++){const a=e.seed+i*TAU/5;circle(ctx,Math.cos(a)*(12+k*25)+k*22,Math.sin(a)*14-k*45,13+k*26,i%2?'#333b36':'#586059');}}
ctx.restore();}
function drawPed(p,hero=false){const g=ctx;g.save();g.translate(p.x,p.y);g.rotate(p.a);circle(g,3,4,hero?9:7,'#15241966');let step=hero?Math.sin(clock*12)*2:Math.sin(p.step)*2;rect(g,-5+step,-5,8,3,'#263633');rect(g,-5-step,2,8,3,'#263633');rect(g,-4,-6,9,12,hero?'#d7e39a':p.color);circle(g,1,0,4,hero?'#e3c79e':'#c3aa8b');if(hero){rect(g,5,3,13,3,'#252f2d');if(invincible>0){g.strokeStyle='#e0f9b0';g.lineWidth=1;g.beginPath();g.arc(0,0,14,0,TAU);g.stroke();}}g.restore();}
function marker(p,label,color){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,32+Math.sin(clock*3)*3,0,TAU);ctx.stroke();circle(ctx,p.x,p.y,13,'#122b20dc');textAt(ctx,label,p.x,p.y+5,15,color);}
function draw(){ctx.setTransform(D,0,0,D,0,0);rect(ctx,0,0,W,H,'#263d33');const targetX=clamp(player.x,Math.min(WORLD/2,W/(2*zoom)),Math.max(WORLD/2,WORLD-W/(2*zoom))),targetY=clamp(player.y,Math.min(WORLD/2,H/(2*zoom)),Math.max(WORLD/2,WORLD-H/(2*zoom)));camera.x+=(targetX-camera.x)*.12;camera.y+=(targetY-camera.y)*.12;ctx.save();ctx.translate(W/2+(active?rand(-shake,shake):0),H/2+(active?rand(-shake,shake):0));ctx.scale(zoom,zoom);ctx.translate(-camera.x,-camera.y);const sx=clamp(camera.x-W/zoom/2-20,0,WORLD),sy=clamp(camera.y-H/zoom/2-20,0,WORLD),sw=Math.min(WORLD-sx,W/zoom+40),sh=Math.min(WORLD-sy,H/zoom+40);ctx.drawImage(mapCanvas,sx*CACHE_SCALE,sy*CACHE_SCALE,sw*CACHE_SCALE,sh*CACHE_SCALE,sx,sy,sw,sh);drawDetail(ctx,sx,sy,sw,sh);
for(const s of skids)if(visible(s)){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);rect(ctx,-7,-s.w/2,14,2,'#202a2380');rect(ctx,-7,s.w/2,14,2,'#202a2380');ctx.restore();}
for(const g of garages)if(visible(g))marker(g,'G','#ceec92');if(job&&visible(job.target))marker(job.target,'↓','#fff1a9');
for(const b of bodies)if(visible(b))drawBody(b);for(const p of peds)if(visible(p))drawPed(p);for(const c of cars)if(visible(c))drawCar(c);for(const o of officers)if(visible(o)){drawPed(o);textAt(ctx,'POLICJA',o.x,o.y-16,7,'#aecde9');}for(const b of policeBullets){circle(ctx,b.x,b.y,2,'#f69378');}if(!player.car)drawPed(player,true);
if(!player.car&&active){const c=nearestCar();if(c&&visible(c)){ctx.strokeStyle='#d7ec99';ctx.lineWidth=1;ctx.beginPath();ctx.arc(c.x,c.y,36,0,TAU);ctx.stroke();textAt(ctx,mobile?'AUTO':'[ E ]',c.x,c.y-42,10,'#ecf4c6');}}
for(const b of bullets){ctx.strokeStyle='#ffeba6';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-Math.cos(b.a)*11,b.y-Math.sin(b.a)*11);ctx.stroke();}for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);rect(ctx,p.x,p.y,3,3,p.color);}ctx.globalAlpha=1;for(const e of explosions)if(visible(e,160))drawExplosion(e);ctx.restore();
if(night){rect(ctx,0,0,W,H,'#06112088');ctx.save();ctx.translate(W/2,H/2);ctx.scale(zoom,zoom);ctx.translate(-camera.x,-camera.y);ctx.globalCompositeOperation='screen';for(const c of cars)if(visible(c)&&c.hp>0){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.a);let grad=ctx.createLinearGradient(15,0,160,0);grad.addColorStop(0,'#f5e7a340');grad.addColorStop(1,'#f5e7a300');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(15,-9);ctx.lineTo(160,-48);ctx.lineTo(160,48);ctx.lineTo(15,9);ctx.fill();ctx.restore();}ctx.restore();}drawMap();}
function drawMap(){const g=mc,s=180/WORLD;g.drawImage(mapCanvas,0,0,180,180);rect(g,0,0,180,180,'#0c29272b');for(const p of garages)circle(g,p.x*s,p.y*s,3,'#d5f192');if(job){g.strokeStyle='#ffe399';g.lineWidth=1.5;g.beginPath();navRoute.forEach((p,i)=>i?g.lineTo(p.x*s,p.y*s):g.moveTo(p.x*s,p.y*s));g.stroke();circle(g,job.target.x*s,job.target.y*s,4,'#ffd782');}for(const c of cars)if(c.police&&c.ai&&wanted>0)circle(g,c.x*s,c.y*s,2,'#eb8b78');for(const o of officers)circle(g,o.x*s,o.y*s,1.7,'#82c2ed');g.save();g.translate(player.x*s,player.y*s);g.rotate(player.a);g.fillStyle='#fff9d2';g.beginPath();g.moveTo(6,0);g.lineTo(-4,-4);g.lineTo(-2,0);g.lineTo(-4,4);g.closePath();g.fill();g.restore();}

function frame(t){if(!frameTime)frameTime=t;let delta=Math.min((t-frameTime)/1000,.1);frameTime=t;if(active){acc+=delta;while(acc+1e-9>=1/60){update(1/60);acc-=1/60;if(!active){acc=0;break;}}}else acc=0;draw();requestAnimationFrame(frame);}
addEventListener('error',e=>{$('error').style.display='block';$('error').textContent='Błąd gry: '+e.message;});hud();requestAnimationFrame(frame);
})();
