function configureUI(){document.querySelector('#who').textContent=p.name;document.querySelector('#className').textContent=cfg().name;document.querySelector('#manaPill').classList.toggle('nomagic',!hasMagic());document.querySelector('#cw').classList.toggle('nomagic',!hasMagic());renderSpellbar()}function availableSpells(){return SPELLS.filter(s=>cfg().allowed.includes(s.id))}function unlockedSpells(){return availableSpells().filter(s=>p.lvl>=s.lvl)}function renderSpellbar(){let bar=document.querySelector('#spellbar');bar.innerHTML='';if(!hasMagic()){bar.classList.add('nomagic');p.spellId=null;return}bar.classList.remove('nomagic');availableSpells().forEach((s,i)=>{let b=document.createElement('button');b.className='spell'+(p.lvl<s.lvl?' locked':'');b.textContent=`${i+1} ${s.n} · ${s.cost}`;b.onclick=()=>p.lvl>=s.lvl&&selectSpell(s.id);bar.appendChild(b)});let u=unlockedSpells();if(!p.spellId||!u.some(s=>s.id===p.spellId))p.spellId=u[0]?.id||null;paintSpellSelection()}function selectSpell(id){p.spellId=id;paintSpellSelection()}function paintSpellSelection(){let list=availableSpells();document.querySelectorAll('#spellbar .spell').forEach((b,i)=>b.classList.toggle('sel',list[i]?.id===p.spellId));let s=SPELLS.find(x=>x.id===p.spellId);if(s){document.querySelector('#cast').style.background=s.col;updateRing()}}
function difficulty(){return{hp:Math.pow(1.08,floor-1),dmg:Math.pow(1.10,floor-1),sp:Math.pow(1.02,floor-1),aggro:Math.min(900,420+(floor-1)*32),elite:floor<3?0:Math.min(.28,.08+(floor-3)*.012)}}
function gen(){rooms=[];cors=[];ms=[];decor=[];shots=[];enemyShots=[];fx=[];chests=[];drops=[];let x=100,y=100;for(let i=0;i<10;i++){let r={x,y,w:250+Math.random()*80,h:190+Math.random()*70};rooms.push(r);for(let j=0;j<3;j++)decor.push({x:r.x+25+Math.random()*(r.w-50),y:r.y+25+Math.random()*(r.h-50),t:Math.floor(Math.random()*4)});if(i>1&&Math.random()<.22)chests.push({x:r.x+r.w*.5+(Math.random()-.5)*90,y:r.y+r.h*.5+(Math.random()-.5)*70,open:false});if(i){let a=rooms[i-1],ax=a.x+a.w/2,ay=a.y+a.h/2,bx=r.x+r.w/2,by=r.y+r.h/2;cors.push({x:Math.min(ax,bx)-30,y:ay-30,w:Math.abs(bx-ax)+60,h:60},{x:bx-30,y:Math.min(ay,by)-30,w:60,h:Math.abs(by-ay)+60})}if(Math.random()<.5){x+=340;y+=(Math.random()-.5)*150}else{y+=290;x+=(Math.random()-.5)*180}}p.x=rooms[0].x+100;p.y=rooms[0].y+90;let r=rooms.at(-1);stairs={x:r.x+r.w/2,y:r.y+r.h/2,active:false};buildNav();let boss=floor%5===0;for(let i=1;i<rooms.length;i++){let extra=Math.floor((floor-1)/3),n=(boss&&i===rooms.length-1?0:1+Math.floor(Math.random()*2)+Math.floor(floor/4))+Math.min(3,extra);for(let j=0;j<n;j++)spawn(rooms[i])}if(boss){let r=rooms.at(-1),bossNo=Math.floor(floor/5),bossScale=Math.pow(1.35,bossNo-1),d=difficulty(),b=baseMob('boss',r.x+r.w/2,r.y+r.h/2,Math.round(650*bossScale*d.hp),35,55*bossScale*d.sp,28*bossScale*d.dmg);b.tough=bossScale;b.phase=0;b.bossNo=bossNo;ms.push(b);sfx('boss')}}
function baseMob(type,x,y,hp,r,sp,dmg){return{x,y,hp,max:hp,r,sp,dmg,type,cd:0,shotCd:Math.random(),slow:0,elite:false,trait:null}}
function makeElite(m){let traits=['swift','armored','furious','regen'];m.elite=true;m.max=m.hp=Math.round(m.hp*2);m.dmg*=1.55;m.sp*=1.15;m.r*=1.18;m.trait=traits[Math.floor(Math.random()*traits.length)];if(m.trait==='swift')m.sp*=1.3;if(m.trait==='armored')m.tough=1.5;if(m.trait==='furious')m.dmg*=1.35;if(m.trait==='regen')m.eliteRegen=Math.max(1,m.max*.012);return m}
function spawn(r){let d=difficulty(),roll=Math.random(),t=roll<.12?'ghost':roll<.24?'shooter':roll<.42?'roach':['goblin','skeleton','spider','orc'][Math.floor(Math.random()*4)],x=r.x+40+Math.random()*(r.w-80),y=r.y+40+Math.random()*(r.h-80),created=[];if(t==='roach'){let count=3+Math.floor(Math.random()*4);for(let k=0;k<count;k++)created.push(baseMob('roach',x+(Math.random()-.5)*35,y+(Math.random()-.5)*35,Math.round((10+floor*3)*d.hp),8,(145+floor*3)*d.sp,(4+floor*.55)*d.dmg))}else if(t==='ghost')created.push(baseMob(t,x,y,Math.round((22+floor*6)*d.hp),15,(82+floor*2)*d.sp,(7+floor)*d.dmg));else if(t==='shooter')created.push(baseMob(t,x,y,Math.round((24+floor*7)*d.hp),15,0,(8+floor*.9)*d.dmg));else created.push(baseMob(t,x,y,Math.round((25+floor*8)*d.hp),15,(60+Math.random()*25)*d.sp,(7+floor)*d.dmg));created.forEach(m=>{if(Math.random()<d.elite)makeElite(m);ms.push(m)})}
function inside(x,y){return rooms.concat(cors).some(r=>x>r.x+8&&x<r.x+r.w-8&&y>r.y+8&&y<r.y+r.h-8)}
function buildNav(){navCells.clear();const s=28,all=rooms.concat(cors);let minX=Math.min(...all.map(r=>r.x)),maxX=Math.max(...all.map(r=>r.x+r.w)),minY=Math.min(...all.map(r=>r.y)),maxY=Math.max(...all.map(r=>r.y+r.h));for(let gx=Math.floor(minX/s);gx<=Math.ceil(maxX/s);gx++)for(let gy=Math.floor(minY/s);gy<=Math.ceil(maxY/s);gy++){let x=gx*s+s/2,y=gy*s+s/2;if(inside(x,y))navCells.add(gx+','+gy)}}
function rebuildFlow(){const s=28,tgx=Math.floor(p.x/s),tgy=Math.floor(p.y/s),start=tgx+','+tgy;flow=new Map();let q=[start],head=0;flow.set(start,0);while(head<q.length){let key=q[head++],[gx,gy]=key.split(',').map(Number),d=flow.get(key)+1;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let nk=(gx+dx)+','+(gy+dy);if(navCells.has(nk)&&!flow.has(nk)){flow.set(nk,d);q.push(nk)}}}}
function pathVec(m){const s=28,gx=Math.floor(m.x/s),gy=Math.floor(m.y/s);let best=null,bd=Infinity;for(const [dx,dy] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]){let k=(gx+dx)+','+(gy+dy),d=flow.get(k);if(d!==undefined&&d<bd){bd=d;best=[gx+dx,gy+dy]}}if(!best)return{x:p.x-m.x,y:p.y-m.y};return{x:best[0]*s+s/2-m.x,y:best[1]*s+s/2-m.y}}
function lineOfSight(a,b){let d=Math.hypot(b.x-a.x,b.y-a.y),steps=Math.ceil(d/18);for(let i=1;i<steps;i++){let t=i/steps;if(!inside(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t))return false}return true}
function hit(d,m){let dealt=d/(m.tough||1);m.hp-=dealt;if(p.vamp&&cfg().vamp)p.hp=Math.min(p.max,p.hp+dealt*p.vamp)}function attack(){if(!p||atkcd>0)return;atkcd=.38;sfx('attack');let range=weaponRange();ms.forEach(m=>{let dx=m.x-p.x,dy=m.y-p.y,d=Math.hypot(dx,dy),a=Math.atan2(dy,dx);if(d<range+18&&Math.abs(Math.atan2(Math.sin(a-p.f),Math.cos(a-p.f)))<1.15){let z=weaponDamage();if(Math.random()<p.crit)z*=p.critMul;hit(z,m)}})}
function cast(){if(!p||!hasMagic()||castcd>0||!p.spellId)return;let s=SPELLS.find(x=>x.id===p.spellId);if(!s||p.lvl<s.lvl||p.mana<s.cost)return;p.mana-=s.cost;castcd=s.cd;sfx('cast');if(s.id==='heal'){let amount=32+p.lvl*3;p.hp=Math.min(p.max,p.hp+amount);fx.push({x:p.x,y:p.y,r:10,max:75,t:.45,col:s.col});return}let bonus=cfg().spell*(1+p.spellBonus);if(s.id==='nova'){ms.forEach(m=>Math.hypot(m.x-p.x,m.y-p.y)<150&&hit((28+p.power*.6)*bonus,m));fx.push({x:p.x,y:p.y,r:10,max:150,t:.35,col:s.col})}else shots.push({x:p.x,y:p.y,vx:Math.cos(p.f)*420,vy:Math.sin(p.f)*420,t:1.3,id:s.id,col:s.col,bonus})}function updateRing(){if(!hasMagic()||!p.spellId)return;let s=SPELLS.find(x=>x.id===p.spellId),ready=1-Math.min(1,castcd/s.cd),deg=ready*360;document.querySelector('#cw').style.background=`conic-gradient(${s.col} ${deg}deg,#ffffff20 ${deg}deg)`}
