function gen(){rooms=[];cors=[];ms=[];decor=[];shots=[];enemyShots=[];fx=[];chests=[];drops=[];let x=100,y=100;for(let i=0;i<10;i++){let r={x,y,w:250+Math.random()*80,h:190+Math.random()*70};rooms.push(r);for(let j=0;j<3;j++)decor.push({x:r.x+25+Math.random()*(r.w-50),y:r.y+25+Math.random()*(r.h-50),t:Math.floor(Math.random()*4)});if(i>1&&Math.random()<.22)chests.push({x:r.x+r.w*.5+(Math.random()-.5)*90,y:r.y+r.h*.5+(Math.random()-.5)*70,open:false});if(i){let a=rooms[i-1],ax=a.x+a.w/2,ay=a.y+a.h/2,bx=r.x+r.w/2,by=r.y+r.h/2;cors.push({x:Math.min(ax,bx)-30,y:ay-30,w:Math.abs(bx-ax)+60,h:60},{x:bx-30,y:Math.min(ay,by)-30,w:60,h:Math.abs(by-ay)+60})}if(Math.random()<.5){x+=340;y+=(Math.random()-.5)*150}else{y+=290;x+=(Math.random()-.5)*180}}p.x=rooms[0].x+100;p.y=rooms[0].y+90;let r=rooms.at(-1);stairs={x:r.x+r.w/2,y:r.y+r.h/2,active:false};buildNav();let boss=floor%5===0;for(let i=1;i<rooms.length;i++){let n=boss&&i===rooms.length-1?0:1+Math.floor(Math.random()*2)+Math.floor(floor/4);for(let j=0;j<n;j++)spawn(rooms[i])}if(boss){let r=rooms.at(-1),bossNo=Math.floor(floor/5),bossScale=Math.pow(1.35,bossNo-1),b=baseMob('boss',r.x+r.w/2,r.y+r.h/2,Math.round(650*bossScale),35,55*bossScale,28*bossScale);b.tough=bossScale;ms.push(b);sfx('boss')}}
function baseMob(type,x,y,hp,r,sp,dmg){return{x,y,hp,max:hp,r,sp,dmg,type,cd:0,shotCd:Math.random(),slow:0}}
function spawn(r){let roll=Math.random(),t=roll<.12?'ghost':roll<.24?'shooter':roll<.42?'roach':['goblin','skeleton','spider','orc'][Math.floor(Math.random()*4)],x=r.x+40+Math.random()*(r.w-80),y=r.y+40+Math.random()*(r.h-80);if(t==='roach'){let count=3+Math.floor(Math.random()*4);for(let k=0;k<count;k++)ms.push(baseMob('roach',x+(Math.random()-.5)*35,y+(Math.random()-.5)*35,10+floor*3,8,145+floor*3,4+floor*.55));return}if(t==='ghost')ms.push(baseMob(t,x,y,22+floor*6,15,82+floor*2,7+floor));else if(t==='shooter')ms.push(baseMob(t,x,y,24+floor*7,15,0,8+floor*.9));else ms.push(baseMob(t,x,y,25+floor*8,15,60+Math.random()*25,7+floor))}
function inside(x,y){return rooms.concat(cors).some(r=>x>r.x+8&&x<r.x+r.w-8&&y>r.y+8&&y<r.y+r.h-8)}
function buildNav(){navCells.clear();const s=28,all=rooms.concat(cors);let minX=Math.min(...all.map(r=>r.x)),maxX=Math.max(...all.map(r=>r.x+r.w)),minY=Math.min(...all.map(r=>r.y)),maxY=Math.max(...all.map(r=>r.y+r.h));for(let gx=Math.floor(minX/s);gx<=Math.ceil(maxX/s);gx++)for(let gy=Math.floor(minY/s);gy<=Math.ceil(maxY/s);gy++){let x=gx*s+s/2,y=gy*s+s/2;if(inside(x,y))navCells.add(gx+','+gy)}}
function rebuildFlow(){const s=28,tgx=Math.floor(p.x/s),tgy=Math.floor(p.y/s),start=tgx+','+tgy;flow=new Map();let q=[start],head=0;flow.set(start,0);while(head<q.length){let key=q[head++],[gx,gy]=key.split(',').map(Number),d=flow.get(key)+1;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let nk=(gx+dx)+','+(gy+dy);if(navCells.has(nk)&&!flow.has(nk)){flow.set(nk,d);q.push(nk)}}}}
function pathVec(m){const s=28,gx=Math.floor(m.x/s),gy=Math.floor(m.y/s);let best=null,bd=Infinity;for(const [dx,dy] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]){let k=(gx+dx)+','+(gy+dy),d=flow.get(k);if(d!==undefined&&d<bd){bd=d;best=[gx+dx,gy+dy]}}if(!best)return{x:p.x-m.x,y:p.y-m.y};return{x:best[0]*s+s/2-m.x,y:best[1]*s+s/2-m.y}}
function lineOfSight(a,b){let d=Math.hypot(b.x-a.x,b.y-a.y),steps=Math.ceil(d/18);for(let i=1;i<steps;i++){let t=i/steps;if(!inside(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t))return false}return true}
function hit(d,m){let dealt=d/(m.tough||1);m.hp-=dealt;if(p.vamp&&cfg().vamp)p.hp=Math.min(p.max,p.hp+dealt*p.vamp)}function attack(){if(!p||atkcd>0)return;atkcd=.38;sfx('attack');let range=weaponRange();ms.forEach(m=>{let dx=m.x-p.x,dy=m.y-p.y,d=Math.hypot(dx,dy),a=Math.atan2(dy,dx);if(d<range+18&&Math.abs(Math.atan2(Math.sin(a-p.f),Math.cos(a-p.f)))<1.15){let z=weaponDamage();if(Math.random()<p.crit)z*=p.critMul;hit(z,m)}})}
function cast(){if(!p||!hasMagic()||castcd>0||!p.spellId)return;let s=SPELLS.find(x=>x.id===p.spellId);if(!s||p.lvl<s.lvl||p.mana<s.cost)return;p.mana-=s.cost;castcd=s.cd;sfx('cast');if(s.id==='heal'){let amount=32+p.lvl*3;p.hp=Math.min(p.max,p.hp+amount);fx.push({x:p.x,y:p.y,r:10,max:75,t:.45,col:s.col});return}let bonus=cfg().spell*(1+p.spellBonus);if(s.id==='nova'){ms.forEach(m=>Math.hypot(m.x-p.x,m.y-p.y)<150&&hit((28+p.power*.6)*bonus,m));fx.push({x:p.x,y:p.y,r:10,max:150,t:.35,col:s.col})}else shots.push({x:p.x,y:p.y,vx:Math.cos(p.f)*420,vy:Math.sin(p.f)*420,t:1.3,id:s.id,col:s.col,bonus})}function updateRing(){if(!hasMagic()||!p.spellId)return;let s=SPELLS.find(x=>x.id===p.spellId),ready=1-Math.min(1,castcd/s.cd),deg=ready*360;document.querySelector('#cw').style.background=`conic-gradient(${s.col} ${deg}deg,#ffffff20 ${deg}deg)`}
function gain(v){p.xp+=v;while(p.xp>=p.next){p.xp-=p.next;p.lvl++;p.next=Math.floor(p.next*1.45);renderSpellbar();skills();break}}const SK=[{n:'Twardziel',d:'+25 HP',ok:()=>true,a:()=>{p.max+=25;p.hp+=25}},{n:'Berserker',d:'+5 obrażeń fizycznych',ok:()=>true,a:()=>p.power+=5},{n:'Lekka stopa',d:'+12% szybkości',ok:()=>true,a:()=>p.speed*=1.12},{n:'Regeneracja',d:'+1 HP/s',ok:()=>true,a:()=>p.regen++},{n:'Wampiryzm',d:'Lecz 5% zadanych obrażeń',ok:()=>cfg().vamp,a:()=>p.vamp+=.05},{n:'Precyzja',d:'+10% szansy na krytyk',ok:()=>true,a:()=>p.crit+=.10},{n:'Mag',d:'+25 maks. many',ok:()=>hasMagic(),a:()=>{p.mmax+=25;p.mana+=25}}];function skills(){let pool=SK.filter(s=>s.ok()),box=document.querySelector('#skills');box.innerHTML='';[...pool].sort(()=>Math.random()-.5).slice(0,3).forEach(s=>{let b=document.createElement('button');b.className='card';b.innerHTML='<b>'+s.n+'</b><small>'+s.d+'</small>';b.onclick=()=>{s.a();lu.style.display='none'};box.appendChild(b)});lu.style.display='flex'}
