const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const file=require('node:path').join(__dirname,'../game.js');
function boot(mobile=false){const els={},events={},gradient={addColorStop(){}};const draw=new Proxy({measureText:t=>({width:t.length*6}),createLinearGradient:()=>gradient},{get:(t,k)=>k in t?t[k]:()=>{}});function el(id){return els[id]??={style:{},textContent:'',innerHTML:'',handlers:{},classList:{toggle(){}},getContext:()=>draw,addEventListener(n,f){(this.handlers[n]??=[]).push(f)},setPointerCapture(){},setAttribute(){},getBoundingClientRect:()=>({left:22,top:694,width:126,height:126})};}const math=Object.create(Math);let seed=53;math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const box={console,URLSearchParams,location:{search:""},Math:math,document:{getElementById:el,createElement:()=>el('mapcache'),body:el('body'),addEventListener(){}},innerWidth:mobile?390:1280,innerHeight:mobile?844:800,devicePixelRatio:1,matchMedia:()=>({matches:mobile}),localStorage:{getItem:()=>null,setItem(){}},addEventListener:(n,f)=>{events[n]=f},requestAnimationFrame(){}};box.window=box;vm.createContext(box);const code=fs.readFileSync(file,'utf8').replace('hud();requestAnimationFrame(frame);','globalThis.test={start,update,frame,player,cars,peds,keys,input,action,shoot,damageCar,garages,jobs,takeJob,carBlocked,overlap,traffic,spawnCar,buildings,resetInput,pause,draw,resize,hud,pedestrianContact,pedestrianBlocked,resolvePedestrianCars,pumpMusic,stopMusic,blocked,water,bridges,riverCenter,missionDefs,beginMission,advanceMission,roadRoute,edgeValid,walkRoute,clearPath,officers,dismount,updateOfficers,dispatchPatrol,drawAtlas,pauseForPanel,closePanel,get:()=>({active,dead,wanted,cash,job,clock,bullets:bullets.length,explosions:explosions.length,bodies:bodies.length}),setTime:t=>{clock=t},setWanted:v=>{wanted=v},setCamera:(x,y)=>{camera.x=x;camera.y=y}};hud();requestAnimationFrame(frame);');vm.runInContext(code,box);return {t:box.test,els,events};}
function ticks(t,n){for(let i=0;i<n;i++)t.update(1/60)}
let {t,els}=boot();t.start();assert(t.get().active);assert(!t.carBlocked(t.cars.at(-1),t.cars.at(-1).x,t.cars.at(-1).y));t.action();assert(t.player.car,'starter car can be entered');t.action();assert(!t.player.car,'safe exit');t.action();const car=t.player.car;t.cars.splice(0,t.cars.length,car);car.x=1200;car.y=1425;car.a=0;car.s=0;t.player.x=1200;t.player.y=1425;t.keys.KeyW=true;ticks(t,120);assert(car.x>1400);assert(car.s>200);t.keys.KeyW=false;t.input.brake=true;ticks(t,60);assert(Math.abs(car.s)<3,'brake stops car');t.input.brake=false;t.action();assert(!t.player.car);t.shoot();assert.equal(t.get().bullets,1);t.shoot();assert.equal(t.get().bullets,1,'cooldown');t.pause();assert.equal(t.get().active,false);t.start();
t.action();assert(t.player.car);ticks(t,70);t.damageCar(car,101);assert(!t.player.car,'destroyed car ejects');assert.equal(t.get().explosions,1,'destroyed car explodes once');t.damageCar(car,100);assert.equal(t.get().explosions,1);t.draw();assert(t.player.hp<100);assert(!t.get().dead);t.draw();
({t}=boot());t.start();t.action();t.player.car.x=t.garages[0].x;t.player.car.y=t.garages[0].y;t.player.car.hp=20;t.player.x=t.garages[0].x;t.player.y=t.garages[0].y;t.update(1/60);assert.equal(t.player.car.hp,100,'garage heals');t.pauseForPanel('missions');t.beginMission('taxi');assert(t.get().job);for(let i=0;i<2;i++){const goal=t.get().job.target;t.player.car.x=goal.x;t.player.car.y=goal.y;t.player.car.s=0;t.player.x=goal.x;t.player.y=goal.y;t.advanceMission(1/60);}assert.equal(t.get().cash,650);assert.equal(t.get().job,null);
({t}=boot(true));t.start();t.action();t.input.x=1;ticks(t,60);assert(t.player.car.s>50,'mobile joystick accelerates');t.resetInput();assert.equal(t.input.x,0);
for(const fps of [30,60,120]){({t}=boot());t.start();t.action();const c=t.player.car;t.cars.splice(0,t.cars.length,c);t.peds.length=0;c.x=1200;c.y=1425;c.a=0;c.s=0;t.player.x=c.x;t.player.y=c.y;t.keys.KeyW=true;for(let i=0;i<=fps*2;i++)t.frame(1000+i*1000/fps);console.log('fps',fps,'x',c.x.toFixed(2),'speed',c.s.toFixed(2));assert(c.x>1600&&c.x<1650);}
({t}=boot());t.start();let turns=0;const dirs=new Map(t.cars.map(c=>[c,c.dir]));for(let i=0;i<3600;i++){t.update(1/60);if(i%60===0){for(const c of t.cars){assert(Number.isFinite(c.x)&&Number.isFinite(c.y));assert(!t.water(c.x,c.y),"traffic stays out of river");if(dirs.has(c)&&dirs.get(c)!==c.dir)turns++;dirs.set(c,c.dir);}}}assert(turns>5,'traffic turns');console.log('PASS: start, entry/exit, throttle/brake, cooldown, pause, destruction, garage, job reward, touch input, frame-rate consistency, 60s traffic simulation; turns',turns);

({t}=boot());t.start();t.peds.splice(1);t.peds[0].hp=0;t.update(1/60);assert.equal(t.get().bodies,1);ticks(t,180);assert.equal(t.get().bodies,1,"body stays after death");t.draw();console.log("PASS: explosion lifecycle and persistent bodies");

({t}=boot());t.start();const parked=t.cars.at(-1);t.cars.splice(0,t.cars.length,parked);parked.x=1200;parked.y=1425;parked.a=Math.PI/4;parked.s=0;t.player.x=1200;t.player.y=1470;t.keys.KeyW=true;for(let i=0;i<60;i++){t.update(1/60);assert(!t.pedestrianContact(t.player.x,t.player.y,parked),"no overlap during approach");}assert(!t.pedestrianContact(t.player.x,t.player.y,parked),"cannot walk through rotated car");assert(Math.abs(t.player.x-1200)>10,"slides along angled body");t.keys.KeyW=false;t.keys.KeyD=true;ticks(t,120);assert(t.player.x>1280,"can walk around car");t.player.x=parked.x;t.player.y=parked.y;t.resolvePedestrianCars();assert(!t.pedestrianContact(t.player.x,t.player.y,parked),"moving car pushes pedestrian out");parked.hp=0;assert(t.pedestrianBlocked(parked.x,parked.y),"wreck remains solid");console.log("PASS: pedestrian collision, sliding, depenetration and wrecks");

({t}=boot());t.start();for(const m of t.missionDefs)for(const p of m.steps)assert(!t.blocked(p.x,p.y,9),m.id+" objective accessible");for(const b of t.bridges)assert(!t.water(t.riverCenter(b.y),b.y,28));assert(t.water(t.riverCenter(1200),1200));const route=t.roadRoute({x:1400,y:1800},{x:2800,y:1600});assert(route.length>3);for(let i=2;i<route.length-1;i++)assert(t.clearPath(route[i-1],route[i],2),"route traversable");const path=t.walkRoute({x:1100,y:1600},{x:1300,y:1600});assert(path.length>2,"officer routes around palace");for(let i=1;i<path.length;i++)assert(t.clearPath(path[i-1],path[i]));
let police;for(let i=0;i<20&&!police;i++)police=t.spawnCar(i,true);assert(police);police.x=1400;police.y=1825;police.a=0;police.s=0;t.player.x=1400;t.player.y=1870;t.cars.splice(0,t.cars.length,police);t.setWanted(2);t.dismount(police);assert(t.officers.length>0,"officers leave car");assert(police.deployed>0);const initial=Math.min(...t.officers.map(o=>Math.hypot(o.x-t.player.x,o.y-t.player.y)));for(let i=0;i<30;i++)t.updateOfficers(1/60);assert(Math.min(...t.officers.map(o=>Math.hypot(o.x-t.player.x,o.y-t.player.y)))<initial,"officers chase player");t.setWanted(0);for(let i=0;i<300;i++)t.updateOfficers(1/60);assert.equal(t.officers.length,0,"officers return to car");assert.equal(police.deployed,0);t.drawAtlas();console.log("PASS: Warsaw river, four bridges, objectives, navigation and dismount/chase/reboard");
