const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
function boot(mobile=false){const els={},events={},gradient={addColorStop(){}};const draw=new Proxy({measureText:t=>({width:t.length*6}),createLinearGradient:()=>gradient},{get:(t,k)=>k in t?t[k]:()=>{}});function el(id){return els[id]??={style:{},textContent:'',innerHTML:'',handlers:{},classList:{toggle(){}},getContext:()=>draw,addEventListener(n,f){(this.handlers[n]??=[]).push(f)},setPointerCapture(){},setAttribute(){},getBoundingClientRect:()=>({left:22,top:694,width:126,height:126})};}const math=Object.create(Math);let seed=53;math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const box={console,URLSearchParams,location:{search:''},Math:math,document:{getElementById:el,createElement:()=>el('mapcache'),body:el('body'),addEventListener(){}},innerWidth:mobile?390:1280,innerHeight:mobile?844:800,devicePixelRatio:1,matchMedia:()=>({matches:mobile}),localStorage:{getItem:()=>null,setItem(){}},addEventListener:(n,f)=>{events[n]=f},requestAnimationFrame(){}};box.window=box;vm.createContext(box);for(const file of ['srodmiescie-data.js','buildings-1.js','buildings-2.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../maps/'+file),'utf8'),box);const hooks='start,update,frame,player,cars,peds,keys,input,action,shoot,damageCar,garages,carBlocked,overlap,traffic,spawnCar,buildings,resetInput,pause,draw,resize,hud,pedestrianContact,pedestrianBlocked,resolvePedestrianCars,blocked,water,bridges,missionDefs,beginMission,advanceMission,roadRoute,walkRoute,clearPath,officers,dismount,updateOfficers,dispatchPatrol,drawAtlas,pauseForPanel,closePanel,geo,MAP,roads,segments,driveSegments,graph,mainNodes,nearestRoad,lanePosition,starter,spawnPoint,maintainPopulation,nearbyRoads';const code=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8').replace('hud();requestAnimationFrame(frame);',`globalThis.test={${hooks},get:()=>({active,dead,wanted,cash,job,clock,bullets:bullets.length,explosions:explosions.length,bodies:bodies.length}),setWanted:v=>{wanted=v}};hud();requestAnimationFrame(frame);`);vm.runInContext(code,box);return {t:box.test,els,events};}
const {t,els}=boot();console.log('Loaded',t.roads.length,'roads',t.buildings.length,'buildings',t.graph.size,'graph nodes',t.driveSegments.length,'drivable segments');
assert(t.roads.length>1000);assert(t.buildings.length>5000);assert(t.MAP.water.length>0,'Vistula geometry loaded');
for(const name of ['Marszałkowska','Mokotowska','Koszykowa','Nowy Świat','Krakowskie Przedmieście','Plac Zbawiciela'])assert(t.roads.some(r=>r.name===name),name);
const diagonal=t.segments.filter(s=>Math.abs(s.b.x-s.a.x)>3&&Math.abs(s.b.y-s.a.y)>3);assert(diagonal.length>500,'actual non-orthogonal street geometry');
console.log('Local population',t.cars.length,t.peds.length,'within 350',t.cars.filter(c=>Math.hypot(c.x-t.player.x,c.y-t.player.y)<350).length,t.peds.filter(c=>Math.hypot(c.x-t.player.x,c.y-t.player.y)<350).length);
assert(t.cars.filter(c=>Math.hypot(c.x-t.player.x,c.y-t.player.y)<350).length>=5,'visible neighborhood has cars');assert(t.peds.filter(c=>Math.hypot(c.x-t.player.x,c.y-t.player.y)<350).length>=12,'visible neighborhood has pedestrians');assert(t.roads.every(r=>r.foot||r.width>=38),'minimum drivable road width');
t.start();assert(t.get().active);assert(!t.blocked(t.player.x,t.player.y,8),'safe spawn');assert(!t.carBlocked(t.starter,t.starter.x,t.starter.y),'starter car on street');t.action();assert(t.player.car,'starter accessible');t.action();assert(!t.player.car,'safe exit');t.action();assert(t.player.car);
for(const m of t.missionDefs)for(const p of m.steps){assert(!t.blocked(p.x,p.y,8),m.id+' target not in building/water');const r=t.roadRoute(t.player,p);assert(r.length>2,m.id+' route found');for(let i=2;i<r.length-2;i++)assert(!t.water(r[i].x,r[i].y,2),m.id+' road avoids water');}
console.log('PASS: real geometry, spawning, enter/exit, mission accessibility and routes');
// Touch reverse must move backward, stop when released, and survive input cancellation.
const originalCars=t.cars.slice(),originalPeds=t.peds.slice();t.cars.splice(0,t.cars.length,t.starter);t.peds.length=0;const edge=t.driveSegments.find(e=>e.length>160&&!e.road.bridge),rp=t.lanePosition(edge,false,.7);Object.assign(t.starter,rp,{s:0});t.player.x=rp.x;t.player.y=rp.y;t.player.car=t.starter;
els.switch.handlers.pointerdown[0]({preventDefault(){},pointerId:7});assert(t.input.reverse);for(let i=0;i<25;i++)t.update(1/60);assert(t.starter.s<-20,'touch reverse reaches negative speed');assert((t.starter.x-rp.x)*Math.cos(rp.a)+(t.starter.y-rp.y)*Math.sin(rp.a)<-5,'touch reverse moves backward');t.resetInput();assert(!t.input.reverse,'cancel clears reverse');t.hud();assert.equal(els.switch.textContent,'COFAJ');
t.starter.s=0;Object.assign(t.starter,rp);t.player.x=rp.x;t.player.y=rp.y;t.keys.KeyS=true;for(let i=0;i<20;i++)t.update(1/60);assert(t.starter.s<0,'keyboard reverse');t.resetInput();t.cars.splice(0,t.cars.length,...originalCars);t.peds.splice(0,t.peds.length,...originalPeds);console.log('PASS: nearby population, street widths, touch and keyboard reverse');
for(const m of t.missionDefs){t.beginMission(m.id);t.setWanted(0);for(let i=0;i<m.steps.length;i++){const p=t.get().job.target;t.player.car=p.mode==='foot'?null:t.starter;t.player.x=p.x;t.player.y=p.y;t.starter.s=0;t.advanceMission(.01);}assert(!t.get().job,m.id+' completes');}assert(t.get().cash>=4900);t.beginMission('taxi');t.advanceMission(1000);assert(!t.get().job,'time limit');t.pauseForPanel('atlas');assert(!t.get().active);t.closePanel();assert(t.get().active);console.log('PASS: all five mission completions, timeout and map pause');
t.player.car=null;t.player.x=t.spawnPoint.x;t.player.y=t.spawnPoint.y;t.starter.x=t.spawnPoint.x+30;t.starter.y=t.spawnPoint.y;t.starter.a=.6;assert(t.pedestrianBlocked(t.starter.x,t.starter.y));t.player.x=t.starter.x;t.player.y=t.starter.y;t.resolvePedestrianCars();assert(!t.pedestrianContact(t.player.x,t.player.y,t.starter),'car contact resolved');t.damageCar(t.starter,110);assert.equal(t.get().explosions,1);t.damageCar(t.starter,110);assert.equal(t.get().explosions,1);t.draw();t.drawAtlas();
let turns=0;const dirs=new Map(t.cars.map(c=>[c,c.dir]));for(let i=0;i<1800;i++){for(const c of [...t.cars])if(c.ai)t.traffic(c,1/60);if(i%60===0)for(const c of t.cars){assert(Number.isFinite(c.x)&&Number.isFinite(c.y));assert(!t.water(c.x,c.y),'traffic avoids river');if(c.dir!==dirs.get(c))turns++;dirs.set(c,c.dir);}}assert(turns>30);console.log('PASS: collision, explosions, rendering and 30 seconds traffic;',turns,'edge transitions');
